Ru translate
Anuken/Mindustry pull request #10069
Opened 2024-07-28 21:18 UTC by adkostatt

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2024-07-29 08:37 UTC, Slotterleet commented
Боже мой, тут весь перевод с ошибками. Сперва выучи русский язык ради Бога.

2024-07-29 10:37 UTC, adkostatt commented
> Боже мой, тут весь перевод с ошибками. Сперва выучи русский язык ради Бога.

Где же ошибки?

2024-08-08 19:33 UTC, 5GameMaker requested changes
Есть ляпы

2024-08-08 19:33 UTC, 5GameMaker commented on core/assets/bundles/bundle_ru.properties
> +ability.shieldregenfield.description = восстанавливает щит ближайших единиц
Рандомная смена регистра :/

2024-08-08 19:33 UTC, 5GameMaker commented on core/assets/bundles/bundle_ru.properties
> +editor.savechanges = [scarlet]Есть несохраненные изменения!\n\n[]Сохранить их?
👉🏻 `ё`

2024-08-08 19:33 UTC, 5GameMaker commented on core/assets/bundles/bundle_ru.properties
> +ability.stat.repairspeed = [stat]{0}/sec[lightgray] скорость починки
А единицы, по всей видимости, не переводим.

В ru локали для секунд используется {t}/сек

https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle_ru.properties#L1104

2024-12-20 14:56 UTC, closed without merging