Formatting Icons
Anuken/Mindustry pull request #10359
Opened 2024-12-02 10:43 UTC by MEEPofFaith

<img width="171" alt="20241202-023526-java" src="https://github.com/user-attachments/assets/82eb16a6-9933-437b-bb4d-49470e986b98">

This method replaces `:duo:` with the duo icon (and similarly with other content), without the need to check for character id. I originally wanted to override `Core.bundle` so that I could override `get` and `format` to automatically do this to every bundle entry; that way it'd be easier to create bundles and potentially have modded content icon support. However I could not find an easy way to do that, so for now it's just this method.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2024-12-02 10:47 UTC, MEEPofFaith commented
hm what would be the best way to check for the end

2024-12-02 10:56 UTC, MEEPofFaith commented
![image](https://github.com/user-attachments/assets/3adeabc0-36e5-4d63-b4aa-f410978adb59)

2024-12-02 10:58 UTC, MEEPofFaith commented
Hm but I don't want to have to do two colons every time I want a colon if a string does have an icon in it.

2024-12-02 21:49 UTC, MEEPofFaith commented
![image](https://github.com/user-attachments/assets/19ea91de-acaa-4751-a699-f24477362b26)
![image](https://github.com/user-attachments/assets/61e495c7-ffb2-44bd-8ec3-026929775e03)

2024-12-02 21:58 UTC, MEEPofFaith commented
Where else would it be sensible to throw `UI::formatIcons` calls?

2025-02-09 04:43 UTC, MEEPofFaith commented
oh jeez conflicts

2025-02-09 04:44 UTC, MEEPofFaith commented
maybe I shouldn't have applied this to every other bundle before merge

2025-02-09 04:50 UTC, Anuken requested changes

2025-02-09 04:50 UTC, Anuken commented on core/src/mindustry/core/UI.java
> +    public static StringBuilder buffer = new StringBuilder();
Should be private.

2025-02-09 04:50 UTC, Anuken commented on core/src/mindustry/ui/fragments/ChatFragment.java
> +            String message = UI.formatIcons(messages.get(i));
Don't change the way the chat displays. On desktop, you can already type :alpha: and have it show up as you type. Inject the formatting code into the chat message sending code instead, so it is formatted right before you send it.

2025-02-09 05:05 UTC, merged