more info in crash reports
Anuken/Mindustry pull request #2609
Opened 2020-09-19 08:59 UTC by DeltaNedas

add oh no, mindustry version, mod list and a link to create a bug report (using template)

2020-09-19 09:38 UTC, sk7725 commented
Oh no, Mindustry crashed!\n" + "Please report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md\n\n" 

This...is not a good idea...at least the wording.
If a mod crashes some poorly-educated people/mod owner will head straight to Anuke, when the issue is the mod and not the game(or does Anuke accept mod issues?)

2020-09-19 09:39 UTC, sk7725 commented
Also try making it that it uses bundles and not hardcoded text?

2020-09-19 09:46 UTC, DeltaNedas commented
anuke would then need to translate the crash log to make use of it
like with translating official / release /etc in the version

2020-09-19 09:50 UTC, DeltaNedas commented
modded reports wont suggest to report crashes now

2020-09-20 18:19 UTC, DeltaNedas commented
@Anuken

2020-09-20 18:23 UTC, Anuken commented
If you're going to add more info to crash reports, there needs to be a lot more than this. See what I send to the crash report server, for example.

2020-09-20 19:18 UTC, DeltaNedas commented
ok ill add more

2020-09-21 20:03 UTC, DeltaNedas commented
@Anuken  any other info that should be added?

2020-09-21 20:14 UTC, Anuken requested changes

2020-09-21 20:14 UTC, Anuken commented on core/src/mindustry/net/CrashSender.java
> +            + "OS: " + System.getProperty("os.name") + "x" + (OS.is64Bit ? "64" : "32") + "\n"
```suggestion
            + "OS: " + System.getProperty("os.name") + " x" + (OS.is64Bit ? "64" : "32") + "\n"
```

2020-09-21 20:14 UTC, Anuken commented on core/src/mindustry/net/CrashSender.java
> +            + mods.list().size + " Mods: " + mods.list().toString(", ", mod -> mod.name)
mod version would be nice too, e.g. `examplemod:1.0`

2020-09-21 20:14 UTC, Anuken commented on core/src/mindustry/net/CrashSender.java
> +                System.exit(0);
But the application still *crashed*, it should exit with 1 or at least a non-zero code.

2020-09-22 06:17 UTC, DeltaNedas commented
@Anuken done

2020-09-22 06:46 UTC, DeltaNedas reviewed
done pls go away bad box

2020-09-22 13:30 UTC, merged