New liquid turret - Tsunami
Anuken/Mindustry pull request #2723
Opened 2020-09-25 08:54 UTC by Slava0135

A lot of new units but only 2 new turrets. Wave is not particularly useful cos of it's range. It's still useful against fire but we need something better in late game.

2020-09-25 09:55 UTC, Slava0135 commented
oopsie forgot to add it to the research tree

2020-09-25 09:56 UTC, Quezler commented on core/src/mindustry/content/Blocks.java
> +        tsunami = new LiquidTurret("tsunami") {{
```suggestion
        tsunami = new LiquidTurret("tsunami"){{
```

2020-09-29 15:18 UTC, Anuken commented
- This turret should be 3x3, not 4x4. 4x4 is reserved only for the highest tier of combat turrets, and the sprite is not detailed enough to fit in with other 4x4 turrets.
- Missing a `-top` sprite for the liquid.
- Should be near the other 3x3 turrets, not next to the wave in building menu.
- Too cheap, should require a higher tier material like thorium at least.

2020-09-29 15:29 UTC, Slava0135 commented
Ok then. I'll try to fix the issues

2020-09-29 18:29 UTC, Slava0135 commented
Everything should be fine now. It's fine to me but you always can modify it

2020-09-30 14:09 UTC, Anuken commented
Are you going to use EoD's sprite for this?

2020-09-30 14:14 UTC, Slava0135 commented
Not sure really. The problem with my sprite is that it has more thin lines compared to other turrets.

2020-09-30 14:17 UTC, Slava0135 commented
But I refused to add pipes to the sides as it looks weird to me.

2020-09-30 14:19 UTC, Anuken commented
I prefer EoD's version; I think it's slightly cleaner and more consistent with the Wave sprite.

2020-09-30 14:20 UTC, Slava0135 commented
I feel the same but those pipes... idk about them

2020-09-30 14:22 UTC, Anuken commented
They're fine.

2020-09-30 15:50 UTC, Slava0135 commented
Everything is ready I guess

2020-09-30 15:52 UTC, Slava0135 commented
oh no forgot comma in Blocks

2020-09-30 15:58 UTC, SnakkiZXZ commented
as I see you cannot solve with the texture, so I specially drew this sprite for this, if there are 2 images.
![tsunami](https://user-images.githubusercontent.com/62109325/94709702-69fe9300-035f-11eb-9810-d278cda2e7d6.png)
![tsunami-liquid](https://user-images.githubusercontent.com/62109325/94709706-6a972980-035f-11eb-8421-e358a7ba280e.png)
Criticism is welcome.
P.S. you can add ```plastanium``` to craft, it is more expensive than ```titanium```.

2020-09-30 15:59 UTC, SnakkiZXZ commented
oh no i am late?

2020-09-30 16:02 UTC, Slava0135 commented
too late but this looks more like a unit and not a turret

2020-09-30 16:08 UTC, SnakkiZXZ commented
oh no

2020-09-30 17:06 UTC, Anuken requested changes

2020-09-30 17:06 UTC, Anuken commented on core/src/mindustry/content/Blocks.java
> +                    Liquids.water, Bullets.waterShot,
Should use different bullet variants that deal more damage, draw larger and have more knockback.

2020-09-30 17:06 UTC, Anuken commented on core/src/mindustry/content/Blocks.java
> +            reloadTime = 1f;
This won't work. The reload should be at least 2-3; turrets can only shoot once per frame, so any FPS below 60 would make this turret fire slower than it should.

2020-09-30 17:32 UTC, Slava0135 commented
Made the changes

2020-09-30 17:40 UTC, Slava0135 commented
something went wrong and puddle/bullet size is so small

2020-09-30 18:19 UTC, Slava0135 commented
nvm everything is fine after repacking. The stats are somewhat reasonable

2020-09-30 20:42 UTC, merged