Update bundle_pt_BR.properties
Anuken/Mindustry pull request #2948
Opened 2020-10-14 14:33 UTC by xXextremeduro69420Xx

Small changes and fixed some typos.

2020-10-14 20:49 UTC, wiiteh commented
🧠

2020-10-14 23:01 UTC, Pietro303HD reviewed
test

2020-10-14 23:16 UTC, Pietro303HD requested changes
> blocks.reload = Tempo de recarga

Por que tempo de recarga? O block.reload mostra a quantidade de tiros por segundo (aka tps). Não faz sentido.

> keybind.respawn.name = Reaparecer

Reaparecer? Tipo, não faz muito sentido, e não teria muito como fazer. As unicas duas ocasiões que isso aparece são quando você controla uma unit, ou quando você controla uma turret. Eu acho que ficaria melhor se fosse algo tipo, destransformar.

>block.parallax.name = Paralaxe
block.cliff.name = Relevo

PARALAXE? O nome em inglês faria mais sentido.
Relevo não faz sentido, algo como montanha seria melhor.

>block.overflow-gate.name = Portão de Fluxo
block.underflow-gate.name = Portão de Fluxo invertido

portão de fluxo? sério? tipo, faz um pouco de sentido mas, portão de Sobrecarga praticamente fala oque o bloco faz.

>block.segment.name = Segmento

Mesmo motivo do Paralaxe. vou dar um pouco de explicação, por enquanto, a comunidade pt-br não tem uma organização suficiente pra mudar os nomes das turrets. Por enquanto deixe elas assim, até que nomes sejam decididos pela comunidade.

2020-10-14 23:36 UTC, xXextremeduro69420Xx commented
> > blocks.reload = Tempo de recarga
> 
> Por que tempo de recarga? O block.reload mostra a quantidade de tiros por segundo (aka tps). Não faz sentido.
> 
> > keybind.respawn.name = Reaparecer
> 
> Reaparecer? Tipo, não faz muito sentido, e não teria muito como fazer. As unicas duas ocasiões que isso aparece são quando você controla uma unit, ou quando você controla uma turret. Eu acho que ficaria melhor se fosse algo tipo, destransformar.
> 
> > block.parallax.name = Paralaxe
> > block.cliff.name = Relevo
> 
> PARALAXE? O nome em inglês faria mais sentido.
> Relevo não faz sentido, algo como montanha seria melhor.
> 
> > block.overflow-gate.name = Portão de Fluxo
> > block.underflow-gate.name = Portão de Fluxo invertido
> 
> portão de fluxo? sério? tipo, faz um pouco de sentido mas, portão de Sobrecarga praticamente fala oque o bloco faz.
> 
> > block.segment.name = Segmento
> 
> Mesmo motivo do Paralaxe. vou dar um pouco de explicação, por enquanto, a comunidade pt-br não tem uma organização suficiente pra mudar os nomes das turrets. Por enquanto deixe elas assim, até que nomes sejam decididos pela comunidade.

1: Então cadência de tiros encaixaria melhor.
2: Destransformar nem existe, restabelecer ficaria bem melhor 
3: Montanha é um relevo
4: Sobrecarga é mais pra peso excessivo 
5: A questão das armas você até que tem um ponto

2020-10-14 23:51 UTC, Pietro303HD commented
> 1: Então cadência de tiros encaixaria melhor.
2: Destransformar nem existe, restabelecer ficaria bem melhor
3: Montanha é um relevo
4: Sobrecarga é mais pra peso excessivo

meio q como tudo isso faz sentido, pode deixar esses do jeito q tá ;)

2020-10-16 15:42 UTC, Derkkkk commented
Tu

2020-10-23 13:47 UTC, merged