send mindustry to brazil
Anuken/Mindustry pull request #3194
Opened 2020-10-30 20:05 UTC by DeltaNedas

tinanium press

2020-10-30 20:07 UTC, Anuken approved these changes

2020-10-30 20:19 UTC, summetdev approved these changes

2020-10-30 20:28 UTC, DeltaNedas commented
whats taking travis so long its been 20 mins

2020-10-30 20:38 UTC, summetdev commented
![imgonline-com-ua-PicOnPic-bOdzwBJkPSd](https://user-images.githubusercontent.com/55251897/97754718-0eaff400-1b09-11eb-96c3-c07f8c51ebf1.jpg)

2020-10-30 20:48 UTC, Quezler commented
is this some peasant joke i do not understand?

2020-10-30 20:55 UTC, ThePythonGuy3 commented
i just dont get it, but whatever. 🇧🇷

2020-10-30 21:07 UTC, Pietro303HD commented
tinanium won

2020-10-30 21:17 UTC, DeltaNedas commented
holy shit travis

2020-10-30 23:42 UTC, markozajc commented
travis took so long because he had a trip to brazil

2020-10-31 01:22 UTC, z0mbiesrock commented
bad egg cat

2020-10-31 12:26 UTC, Catchears commented
> is this some peasant joke i do not understand?

Kind of

2020-10-31 12:26 UTC, Catchears approved these changes
10/10 would merge

2020-10-31 12:30 UTC, ThePythonGuy3 approved these changes

2020-10-31 12:45 UTC, Ilya246 approved these changes

2020-10-31 13:32 UTC, summetdev commented
~~Quezler could you approve these changes~~

2020-10-31 13:36 UTC, BlueWolf3682 commented
nani

2020-10-31 15:20 UTC, DeltaNedas commented
@Quezler please review

2020-10-31 15:27 UTC, ILiekMelons approved these changes
brazil

2020-10-31 15:29 UTC, QmelZ approved these changes

2020-10-31 15:29 UTC, QmelZ commented
amazing lmao

2020-10-31 15:31 UTC, ThePythonGuy3 commented
i love how #github is getting bloated of reviews lmao

2020-10-31 15:34 UTC, braainsiogame approved these changes

2020-10-31 15:34 UTC, Quezler approved these changes

2020-10-31 15:35 UTC, summetdev commented
We got it.

2020-10-31 15:35 UTC, ThePythonGuy3 commented
oh yes

2020-10-31 15:44 UTC, BlueWolf3682 reviewed
yes

2020-10-31 15:45 UTC, braainsiogame commented
@BlueWolf3682 APPROVE IT

2020-10-31 15:46 UTC, Pogreu commented
Ah não

2020-10-31 15:51 UTC, Pogreu approved these changes

2020-10-31 15:52 UTC, Ilya246 approved these changes

2020-10-31 15:52 UTC, Ilya246 approved these changes

2020-10-31 15:53 UTC, braainsiogame approved these changes

2020-10-31 15:53 UTC, QmelZ approved these changes

2020-10-31 15:53 UTC, braainsiogame approved these changes

2020-10-31 15:54 UTC, braainsiogame approved these changes

2020-10-31 15:54 UTC, braainsiogame approved these changes

2020-10-31 15:54 UTC, QmelZ approved these changes
third time is a charm

2020-10-31 15:54 UTC, Pogreu commented
Anuke is charming*

2020-10-31 15:55 UTC, braainsiogame commented
why

2020-10-31 15:56 UTC, ThePythonGuy3 commented
~~will this ever get merged~~

2020-10-31 15:57 UTC, Catchears approved these changes
so subtle yet so game-changing

i love it

2020-10-31 15:59 UTC, summetdev commented
Stop

2020-10-31 16:00 UTC, YellOw139 requested changes
Also see line 557. Otherwise great PR. Greatly improves the game.

2020-10-31 16:21 UTC, TheSlaylord approved these changes

2020-10-31 17:22 UTC, DeltaNedas commented on core/assets/bundles/bundle.properties
>  block.armored-conveyor.description = Moves items at the same speed as titanium conveyors, but possesses more armor. Does not accept inputs from the sides from anything but other conveyor belts.
ok will fix very sorry

2020-10-31 17:44 UTC, genNAowl approved these changes

2020-10-31 18:32 UTC, the-kido commented
I would be lying if I said I knew what was going on

2020-10-31 23:19 UTC, Pietro303HD approved these changes

2020-10-31 23:20 UTC, markozajc commented
brazil man sent me to mindustry
![image](https://user-images.githubusercontent.com/30626847/97791917-070b5080-1bd8-11eb-9aff-02148e341273.png)

2020-11-01 19:22 UTC, Erisfiregamer1 commented
merge this already

2020-11-03 16:35 UTC, Erisfiregamer1 commented
OH NOO A CONFLICT OH GOD

2020-11-03 16:36 UTC, Erisfiregamer1 approved these changes
yes

2020-11-03 16:38 UTC, the-kido commented
After thoughtful consideration, I deem this worthy of a merge.

2020-11-03 16:38 UTC, the-kido approved these changes

2020-11-04 00:19 UTC, sample-text-here approved these changes
ye es i want to go to brazil

2020-11-04 00:26 UTC, ItsJonyBoi approved these changes
Yes

2020-11-04 00:43 UTC, notrealn approved these changes

2020-11-04 06:15 UTC, Catchears approved these changes

2020-11-04 07:02 UTC, TheSlaylord commented
conflicting file detected

2020-11-04 11:58 UTC, ritzip approved these changes

2020-11-04 12:20 UTC, QmelZ approved these changes

2020-11-17 03:59 UTC, TheMrAlbert approved these changes

2020-11-17 03:59 UTC, TheMrAlbert commented
Ah yes...

2020-11-17 17:51 UTC, Erisfiregamer1 requested changes
There seems to be errors.
I think maybe the sprite names are causing this. It needs to be fixed.
Otherwise 10/10 would merge

2020-11-30 17:50 UTC, Erisfiregamer1 approved these changes
Force a push to the latest  commit, and anooke will mergg

2020-12-07 15:12 UTC, AJCM-git approved these changes
Game changing, thanks you so much for this.

2020-12-08 02:30 UTC, Volas171 approved these changes

2020-12-08 02:33 UTC, Violet-Scarelli commented
Ah shit, here we go again.

2020-12-09 15:36 UTC, Volas171 commented
lol the conflict still broke

2020-12-09 15:37 UTC, Volas171 commented
: facepalm :

2020-12-18 14:08 UTC, Erisfiregamer1 approved these changes
When do we merge this again?

2020-12-19 05:09 UTC, Volas171 commented
idk , when the conflict gets fixed maybe

2021-01-19 16:05 UTC, Anuken commented
the end

2021-01-19 16:05 UTC, closed without merging

2021-01-19 16:07 UTC, DeltaNedas commented
ono pull got stale

2021-01-19 16:08 UTC, markozajc commented
no anuke you can't just close this nooo

2021-01-19 16:39 UTC, Volas171 commented
nooooooo

2021-02-16 02:25 UTC, catatagun commented
I say anuke die for this