Merge ChargeTurret into Turret
Anuken/Mindustry pull request #3221
Opened 2020-11-01 07:46 UTC by MEEPofFaith

Give any turret the ability to charge. Want a charge burst turret? Now you can. Charge LaserTurret? Yes.
[Video Demonstration](https://youtu.be/c8WeakO-kkM)
(Changes made to blocks shown in this video not included in this pull request.)

2020-11-01 09:19 UTC, SirMachinegun commented
> No no no no non onoonon
> 
> 1. Not really necessary; if you are _that_ desperate for charge liquid/burst turrets, use scripting.
> 2. You will break mods. A lot of them.

alot of mods will be already broken in v6

2020-11-01 09:23 UTC, SirMachinegun commented
> You will break mods. A lot of them.

Most mods will be broken in v6 already (mainly because of the new unit production system).I don't think breaking more mods in v6 will be a problem because alot of them are already broken. Also issues because of this can be fixed easily.

2020-11-01 09:45 UTC, Gdeft requested changes

2020-11-01 09:45 UTC, Gdeft commented on core/src/mindustry/world/blocks/defense/turrets/Turret.java
> +    /** Charging related stuff*/
This won't end well on the java documentation. It'll show like this:

`float chargeTime Charging related stuff`

I assume you are confused by the "Currently used for artillery only" which is for the `minRange` field. You can see it [here](https://mindustrygame.github.io/docs/mindustry/world/blocks/defense/turrets/Turret.html#minRange).

2020-11-01 09:58 UTC, sk7725 commented
No no no no non onoonon
1. Not really necessary; if you are *that* desperate for charge liquid/burst turrets, use scripting.
2. You will break mods. A lot of them.

2020-11-01 09:59 UTC, MEEPofFaith commented
It's not a big break. Just change every ChargeTurret to PowerTurret. And not everyone knows how to script.

2020-11-01 10:12 UTC, summetdev commented on core/src/mindustry/world/blocks/defense/turrets/Turret.java
> +            }
I don't know what Anuke prefer, but with ternary operator it looks cleaner.

```suggestion
            return chargeTurn ? true : !charging;
```

2020-11-01 10:12 UTC, summetdev commented on core/src/mindustry/world/blocks/defense/turrets/Turret.java
> +                        float i = (shotCounter % shots) - (shots-1)/2f;
```suggestion
                        float i = (shotCounter % shots) - (shots - 1) / 2f;
```

2020-11-01 12:48 UTC, sk7725 commented
> It's not a big break. Just change every ChargeTurret to PowerTurret. And not everyone knows how to script.

How can you be so sure?
"And not everyone knows how to script." this argument is invalid, *not everyone knows how to mod* either.

2020-11-01 14:21 UTC, Anuken commented
> You will break mods. A lot of them.

Every single non-trivial mod is already broken. I've already merged many of the turret types into one; legacy support is not a good reason to keep things as they are.

2020-11-01 20:03 UTC, MEEPofFaith commented
So is that a yes, no, vertical, or horizontal?

2020-11-09 02:46 UTC, GlennFolker commented
diagonal

2020-11-29 11:09 UTC, MEEPofFaith commented
Anuke did it himself, closing pull request.

2020-11-29 11:09 UTC, closed without merging