Update bundle_es.properties
Anuken/Mindustry pull request #3451
Opened 2020-11-18 19:48 UTC by Angel-24

2020-11-19 02:22 UTC, Volas171 commented
Duplicate of #3448

2020-11-19 06:31 UTC, ThePythonGuy3 commented
Not exactly a duplicate. I guess he doesnt know how to edit PRs once submitted. (Esquema -> Plantilla)

2020-11-19 13:25 UTC, Volas171 commented
yes lol

2020-11-19 15:14 UTC, Volas171 requested changes

2020-11-19 15:14 UTC, Volas171 commented on core/assets/bundles/bundle_es.properties
> +waves.every =
agregar nuevamente cada

2020-11-19 18:30 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +waves.every =
Hecho, mañana seguiré revisándolo otro rato. Gracias por avisar.  ☺

2020-11-20 02:36 UTC, Volas171 approved these changes

2020-11-20 06:15 UTC, ThePythonGuy3 approved these changes

2020-11-20 06:43 UTC, GlennFolker commented
Bundle [ES]

2020-11-20 07:51 UTC, Angel-24 commented
> Bundle [ES]

I don't get it... Does this mean that I missed to write something specific as the title of the commit?

2020-11-21 03:00 UTC, GlennFolker commented
> > Bundle [ES]
> 
> I don't get it... Does this mean that I missed to write something specific as the title of the commit?

Of course not. It's unrelated

2020-11-22 21:58 UTC, Anuken commented
Should this be merged?

2020-11-23 03:49 UTC, Volas171 commented
yes i guess

2020-11-25 20:58 UTC, Pronink commented on core/assets/bundles/bundle_es.properties
> +waves.every =
Hola! Tengo una pregunta y en el readme de la carpeta bundle no encuentro la respuesta. ¿Usais algún programa especial para averiguar las diferencias entre la versión en inglés y la de español? He comparado ambos archivos y veo que las propiedades cambian de sitio a veces. Saludos :relaxed: !!

2020-11-25 22:15 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +waves.every =
Buenas noches. Pues no sé el resto, pero lo único que uso es el editor propio de GitHub. Me fijo en el número de línea de abajo del fichero, y si para una línea no coincide su número, la diferencia con el número de línea de la versión original es el número de líneas que me faltan o sobran en el documento.
Luego para comprobar la precisión que tendrá el texto en el juego, voy revisando cada línea una por una... Hasta encontrar faltas de ortografía, expresiones mal formadas, e intentando encontrar un vocabulario que encaje mejor con el estilo del Juego, para que quede perfecto.

2020-11-27 02:31 UTC, Volas171 approved these changes

2020-11-28 14:02 UTC, Angel-24 commented
> 
> 
> Should this be merged?

Yes

2020-11-28 14:46 UTC, merged