1st translation bundle
Anuken/Mindustry pull request #3616
Opened 2020-11-26 16:32 UTC by AmateurPotion

Please do not merge yet. Not all translated.

2020-11-26 16:37 UTC, Quezler commented
might i suggest pressing the button "convert to draft"?

2020-11-26 16:42 UTC, AmateurPotion commented
I was still new to GitHub, so I didn't know there was such a feature. Thanks for letting me know there is such a feature.

2020-11-28 02:11 UTC, sk7725 commented
숨기기 / 열기는 열기 / 닫기 또는 숨기기 / 보이기로 수정

2020-11-28 02:11 UTC, sk7725 commented
> stats = 전투 결과
이거 원본이 어떻게 되나요?

2020-11-28 02:14 UTC, sk7725 commented
지역 -> 구역
host는 주최자가 아닌, 호스트로 번역할 것
이상입니다 ㅎㅎ

맞다 stats번역이 빠진거 같던데...stats.description 같은 거 말이에요

2020-11-28 02:15 UTC, sk7725 commented
아 자원과 블록 설명과 새로 추가된 .details도 번역해야 해요. 많은 블록과 모든 자원의 설명과 디테일이 바뀌었을 거니깐 그거 개편해주세요

2020-11-28 02:15 UTC, sk7725 requested changes
Read above.

2020-11-29 09:43 UTC, AmateurPotion commented
Bundle Contributor : sk7725, sharlotte-mobile, Mandu(It's not a Github nickname.)

2020-11-29 12:37 UTC, sk7725 requested changes
reign = 레인
corvus = 코르버스(콜버섯?)
시차는 왜...이미 익었음에다가 시차가 더 말하기 편함
하얀나무는 나무 이름임(띄어쓰기 없는 이유)
전그림자도 이미 눈에 익음...궂이?
민키...?
예 아니오는 O X로 하면 안 될 텐데...워낙 광범위하게 쓰여서 안될거임 비추
코어에서 부활보다 코어로 귀환이 더 나은듯
재구성기는...좀 더 생각 필요...미친...

2020-11-29 12:38 UTC, sk7725 commented
저 제 위 댓글들도 읽고 해결해 주세요

2020-11-30 23:30 UTC, Anuken commented
assuming fixed, ask for a revert if not

2020-11-30 23:30 UTC, merged

2020-12-02 02:25 UTC, sk7725 commented
1. It was not fixed, neither of the requested changes.
2. I am guessing Potion does not know how to read the changes request. Also, this calls for an additional PR, not a revert...