Update bundle_es.properties
Anuken/Mindustry pull request #3652
Opened 2020-11-29 17:36 UTC by Volas171

added last stuff i guess

2020-11-30 12:16 UTC, Angel-24 commented
Hi! Well, I think turrets and units should keep their original name, without translating it, since they're the own name of that unit / turret (Cliff, Fuse, and Arc). Also, the result look very weird translated to spanish.

2020-11-30 13:24 UTC, Angel-24 requested changes
I suggest to leave Fuse and Arc unstranslated, as they look better this way.

2020-11-30 13:25 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +block.cliff.name = Acantilado
block.cliff.name = Cliff

2020-11-30 13:25 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +block.fuse.name = Fusible
block.fuse.name = Fuse

2020-11-30 13:25 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +block.arc.name = Arco
block.arc.name = Arc

2020-12-01 01:24 UTC, Volas171 commented on core/assets/bundles/bundle_es.properties
> +block.fuse.name = Fusible
ok

2020-12-01 06:18 UTC, ThePythonGuy3 commented
The names for the teams in spanish feel... Too odd.
1. They arent capitalized (dunno in english tho)
2. "amarillo" "abandonado" "rojo" just no...

2020-12-01 07:12 UTC, Angel-24 reviewed
> The names for the teams in spanish feel... Too odd.
> 
> 1. They arent capitalized (dunno in english tho)
> 2. "amarillo" "abandonado" "rojo" just no...

I think they're not capitalized because it would look like:  "Equipo Amarillo" instead of "Equipo amarillo". And it isn't the team's name, but the team's color.

Also Identifying teams by it's color is a good idea.

2020-12-01 07:22 UTC, ThePythonGuy3 commented
Well yes but in English they arent color identified, unless it got changed recently. (abandonado just sounds too off)

2020-12-01 08:14 UTC, Angel-24 commented
> Well yes but in English they arent color identified, unless it got changed recently. (abandonado just sounds too off)

yes, that's true.

2020-12-01 08:14 UTC, Angel-24 commented
but should we change it?

2020-12-01 16:40 UTC, closed without merging