shock mine improvements
Anuken/Mindustry pull request #3664
Opened 2020-11-30 15:23 UTC by Slava0135

Now shock mines won't trigger if it's on low hp (less than 1 charge). They will blink if so.

2020-11-30 15:30 UTC, Slava0135 commented
*not my fault

2020-11-30 15:34 UTC, summetdev requested changes

2020-11-30 15:34 UTC, summetdev commented on core/src/mindustry/world/blocks/defense/ShockMine.java
> +            }
it's better to use `else` here.
```suggestion
            }else{
                progress += delta();
                progress %= blinkDelay;
            }
```

2020-11-30 15:34 UTC, summetdev commented on core/src/mindustry/world/blocks/defense/ShockMine.java
empty line in top of class.
```suggestion
```

2020-11-30 15:34 UTC, summetdev commented on core/src/mindustry/world/blocks/defense/ShockMine.java
> +            if(enabled && unit.team != team && timer(timerDamage, cooldown) && isActive()){
maybe put `isActive()` after `enabled`? so it doesn't need to execute more height statements.

2020-11-30 15:53 UTC, Slava0135 commented on core/src/mindustry/world/blocks/defense/ShockMine.java
> +            }
this will break stuff

2020-11-30 17:39 UTC, DeltaNedas commented
good

2020-11-30 20:45 UTC, joshuaptfan commented
The square light is ugly, how about a smaller circle light, same size as the 4 holes? And it should be red, no need for team color as it will already have the team marker when it belongs to another team.

2020-12-03 18:23 UTC, sample-text-here commented
[I don't think shock mines are supposed to show their team color](https://github.com/Anuken/Mindustry/blob/d64f603e08ea27804bdc25026392ad30b1470563/core/src/mindustry/world/blocks/defense/ShockMine.java#L33-L35)

2020-12-06 22:31 UTC, Bohaska commented
@Slava0135 update this pr

2020-12-09 08:13 UTC, sk7725 requested changes
1. Why not only render the blink by `if Time.time % certainamount > certainamount / 2`?
2. Shock mines are supposed to be hard to spot. Make the blink only draw for mines on your team, and keep the led "off" by default, so it is hard to tell your shock mines from the enemy's(which is why team indicators are nonexistant on this block)
3. Why not use a textureregion instead of a solid square, for mods and aesthetics?

2020-12-09 08:23 UTC, Slava0135 commented
> 1. Why not only render the blink by `if Time.time % certainamount > certainamount / 2`?
> 2. Shock mines are supposed to be hard to spot. Make the blink only draw for mines on your team, and keep the led "off" by default, so it is hard to tell your shock mines from the enemy's(which is why team indicators are nonexistant on this block)
> 3. Why not use a textureregion instead of a solid square, for mods and aesthetics?

2 is Pretty reasonable. I will move the blink effect to drawTeam. Idk about 3. People could just override draw methods if they want. And 1 - there is 2 divisions, while

2020-12-09 08:26 UTC, Slava0135 commented
Oh I forgot what drawTeam does. It is called on block if you are on enemy team not ally.

2020-12-09 17:15 UTC, Slava0135 commented
![image](https://user-images.githubusercontent.com/40753025/101663000-34f77680-3a5b-11eb-9531-45741c6cf534.png)
idk if it's bright enough to be noticable at close look but not too obvious

2020-12-09 17:46 UTC, Slava0135 commented
![Peek 2020-12-09 20-16](https://user-images.githubusercontent.com/40753025/101666689-93265880-3a5f-11eb-8d51-ff8e371bc380.gif)

Is there a way to remove "breaking" layer?

2020-12-16 11:25 UTC, Slava0135 commented
![Peek 2020-12-16 14-18](https://user-images.githubusercontent.com/40753025/102342608-8bf4d280-3faa-11eb-8683-1e02ddccc3d9.gif)
no cracks for now

2021-01-20 07:26 UTC, Slava0135 commented
*perhaps I should just copy unit blinking health bar thing

2021-01-20 13:00 UTC, closed without merging