Require graphite for making lancers and arcs
Anuken/Mindustry pull request #3734
Opened 2020-12-03 08:59 UTC by Bohaska

Nothing more needed

2020-12-03 09:02 UTC, Quezler approved these changes

2020-12-03 09:03 UTC, Quezler requested changes

2020-12-03 09:03 UTC, Quezler commented on core/src/mindustry/content/Blocks.java
> +            requirements(Category.turret, with(Items.copper, 25, Items.lead, 50, Items.silicon, 45 Items.graphite, 30));
```suggestion
            requirements(Category.turret, with(Items.copper, 25, Items.lead, 50, Items.silicon, 45, Items.graphite, 30));
```

2020-12-03 10:01 UTC, GreyMario commented
Uh... wait, _why,_ exactly? Is this because you got your ass whipped in PVP by Arcs and Lancers by sending ground units? 👀

2020-12-03 10:25 UTC, GreyMario commented
Oh.

Found why this PR exists.

It's being submitted by proxy from _that_ guy ([1](https://github.com/Anuken/Mindustry-Suggestions/issues/1402), [2](https://github.com/Anuken/Mindustry-Suggestions/issues/1400)). The one who wants "balance changes" (read: nerfing things so hard that they effectively become banned in practice) because he can't deal with them in PVP.

2020-12-03 11:50 UTC, BlueWolf3682 commented
making these turrets cost graphite makes sense only for lancer, as any good player can use lancer a little *too* effectively against ground swarms. also @GreyMario these people have valid points, and theres absolutely no reason to be toxic to them. if youre wondering, ive played all gamemodes and i find them to be pretty much right with their actions. a lot of things need rebalancing.
take any arguments with me to discord. i dont want to litter the comments with peoples tantrums.

2020-12-03 12:55 UTC, GreyMario commented
Sorry, but "I can't figure out how to send an air unit to go deal with the Lancer" isn't a valid reason to nerf the building with obscene build costs.

2020-12-03 22:09 UTC, Bohaska commented
> Sorry, but "I can't figure out how to send an air unit to go deal with the Lancer" isn't a valid reason to nerf the building with obscene build costs.

I do not play pvp

2020-12-03 22:10 UTC, Bohaska commented
> making these turrets cost graphite makes sense only for lancer, as any good player can use lancer a little _too_ effectively against ground swarms. also @GreyMario these people have valid points, and theres absolutely no reason to be toxic to them. if youre wondering, ive played all gamemodes and i find them to be pretty much right with their actions. a lot of things need rebalancing.
> take any arguments with me to discord. i dont want to litter the comments with peoples tantrums.

Ok.

2020-12-05 23:07 UTC, Bohaska commented
Guys, are you all dead?

2020-12-06 18:42 UTC, Quezler approved these changes

2020-12-06 23:08 UTC, Bohaska commented
@Anuken this is ready for review

2020-12-07 04:05 UTC, BlueWolf3682 commented
how is the build cost of lancer obscene? copper, lead, and silicon, all below 75 is extremely easy to build. if you cant get that much stuff, then actually make production.

2020-12-07 20:52 UTC, Anuken commented
I don't think graphite should be involved. Increasing lead/copper requirements for longer build time should be enough.

2020-12-07 20:52 UTC, closed without merging