Add new server's
Anuken/Mindustry pull request #3793
Opened 2020-12-05 09:43 UTC by MindustryRu

=)

2020-12-05 09:48 UTC, Gdeft commented
=(

2020-12-05 10:38 UTC, Ilya246 commented
this puts .ru on top of the serverlist

2020-12-05 10:40 UTC, BlueWolf3682 commented
third time doing this. stop it. get some help.

2020-12-05 10:40 UTC, GreyMario commented
Maybe if you follow alphabetical order...

And rearrange the rest of the server list so that it's in alphabetical order...

So that you're not just quietly self-promoting by shoving your server onto the top of the list...

2020-12-05 10:54 UTC, Voz-Duh commented
@MindustryRu stop it.

2020-12-05 13:00 UTC, summetdev commented
position in list doesn't matter, servers are sorted by ping.

2020-12-05 13:09 UTC, TheSlaylord commented
Duplicate of #3039 and #3072. Stop.

2020-12-05 13:29 UTC, Makc-Carbon commented
А смысл? Ваш сервер никому не нужен, +учитывая его историю и как он вел себя. +Донат. Хоть Анюку по боку, но комьюнити не наплевать на чадо Анюка. И допустить вот такой сервер в глобал они не допустят. Против удаление вашего сервера с глобалов было выдвинуто пару пуллов, ваш пулл с добавлением в глобал потерпел фиаско. Что в этот раз изменено? Да собственно ничего. Я не хочу разводить тут срач, потому что будет плохо всем. Просто говорю факт — комьюнити против вашего сервера. +Из-за вашего сервера и понижается оценка игры в плеймаркете, что играет ключевую роль в продвижении игры в маркете. Никто же не хочет играть в игру, где плохие отзывы? И в последний раз. Нормальное, продвинутое комьюнити(а это все комьюнити миндастри) против вас и вашего сервера, потому что из-за него кучу бед.

2020-12-05 13:30 UTC, SkinH commented
# **Use hub**,  _lol_

2020-12-05 13:32 UTC, ifritdiezel commented
**stop committing**
**stay inactive for several years**

You do not have permission to send messages in this channel.

2020-12-05 13:33 UTC, MrByars commented
Seriously??

2020-12-05 13:34 UTC, Slava0135 commented
GO OUT OF HERE FREAKS

2020-12-05 13:34 UTC, Ilya246 commented
> 
> 
> (position in list doesn't matter, servers are sorted by ping)

no they aren't - the new server system sorts them by position in list

2020-12-05 13:35 UTC, iutisteli commented
This will put Mindustry.ru at the top of the server list, which is awful. #removeMindustry.ru

2020-12-05 13:35 UTC, DeltaNedas commented
1. there is already pandorum good server
2. paying for admin is bad
3. recommends installing malware launcher
4. this is third pull go away

2020-12-05 13:43 UTC, Fatonndev commented
Please do not add this server.
#removeMindustry.ru

2020-12-05 13:47 UTC, Cobbet2 commented
> А смысл? Ваш сервер никому не нужен, +учитывая его историю и как он вел себя. +Донат. Хоть Анюку по боку, но комьюнити не наплевать на чадо Анюка. И допустить вот такой сервер в глобал они не допустят. Против удаление вашего сервера с глобалов было выдвинуто пару пуллов, ваш пулл с добавлением в глобал потерпел фиаско. Что в этот раз изменено? Да собственно ничего. Я не хочу разводить тут срач, потому что будет плохо всем. Просто говорю факт — комьюнити против вашего сервера. +Из-за вашего сервера и понижается оценка игры в плеймаркете, что играет ключевую роль в продвижении игры в маркете. Никто же не хочет играть в игру, где плохие отзывы? И в последний раз. Нормальное, продвинутое комьюнити(а это все комьюнити миндастри) против вас и вашего сервера, потому что из-за него кучу бед.

что они делали? @Makc-Carbon

2020-12-05 13:47 UTC, RebornTrack970 commented
Please Anuke. Do not the ru.

2020-12-05 13:50 UTC, Dexapnow commented
a mimir .ru

2020-12-05 13:51 UTC, Makc-Carbon commented
> > А смысл? Ваш сервер никому не нужен, +учитывая его историю и как он вел себя. +Донат. Хоть Анюку по боку, но комьюнити не наплевать на чадо Анюка. И допустить вот такой сервер в глобал они не допустят. Против удаление вашего сервера с глобалов было выдвинуто пару пуллов, ваш пулл с добавлением в глобал потерпел фиаско. Что в этот раз изменено? Да собственно ничего. Я не хочу разводить тут срач, потому что будет плохо всем. Просто говорю факт — комьюнити против вашего сервера. +Из-за вашего сервера и понижается оценка игры в плеймаркете, что играет ключевую роль в продвижении игры в маркете. Никто же не хочет играть в игру, где плохие отзывы? И в последний раз. Нормальное, продвинутое комьюнити(а это все комьюнити миндастри) против вас и вашего сервера, потому что из-за него кучу бед.
> 
> что они делали? @Makc-Carbon 

Как что? Пиарились даже на серверах других серверов, пропихивали свой лаунчер, в котором кстати есть вирусы, продавали админки, даже доступ к консоли, использовали хаб человека, которого же и забанили в этом хабе(я знаком с человеком, которого забанили), даже дестабилизация других серверов была. И после такого(и это не все) они достойны быть среди глобальных? После того, что вообще должно их полностью запретить

2020-12-05 13:52 UTC, ritzip commented
27 dislikes in 4 hours, yikes.

2020-12-05 13:56 UTC, EmanuelG-Gaming commented
Holy s*it i dont want p2w

2020-12-05 13:57 UTC, PAP6 commented
Ohno ohno
We don't need mindustry.ru in global list
At least because p2w
Also there's enough good russian servers in the global list that are better than mindustry.ru
~~my english sucks~~

2020-12-05 13:59 UTC, VitLogArx commented
#removeMindustry.ru
Everyone is aganist this server. There are aggressive admins, p2w features.

2020-12-05 14:38 UTC, max2007-69 commented
Bruh moment №3. Вы уже третий раз пытаетесь пропихнуть свой хаб и недо-сервера в глобальный список, хватит, коммьюнити не нужен сервер с донатом, благодаря которому можно устроить дикий дизбаланс на сервере и возможностью купить разбан/размут. У вас настолько плохая репутация, что у некоторых людей из коммьюнити начинается рвотный рефлекс от одного обсуждения ваших серверов, я уже молчу, что на ваших серверах такие бэд дизайны, что любой человек, который это увидит готов выколоть себе глаза, чтобы не видеть эту ересь. К тому же ваше присутствие только увеличивает количество нубов, которые, собственно, идут потом на другие сервера, да и плохая оценка игре уж точно не сделает хорошо, а только плохо, ибо это уменьшит количество людей, которые будут скачивать миндастри, в последствии чего вы и игра помрёт из-за оценки. Попробуйте сделать получше правила, менее агрессивную модерацию, объяснять причину бана, учить игроков на своём сервере нормальным вещам, а не роутерчейнам и щиткубам. Конец.

2020-12-05 15:20 UTC, Nikolass1000 commented
🗞

2020-12-05 15:24 UTC, T1murik commented
[ЧИТАТЬ ДО КОНЦА]сервер отличный, пинг меньше чем на пандоруме, не лагает, игроки не петушатся(правда нубов многовато, хотя они слушают когда предлагаю схему лучше), НО АДМИНЫ (которые были) строили реконструкторы до т4 на выживании(сожрали медь, свинец, титан и половину кремния который я воскресил) и спамили хентаем(ИСКЛЮЧЕНИЕ BULLY ОН НОРМАЛЬНО ИГРАЛ).

2020-12-05 15:46 UTC, Arackulele commented
I will do anything for RU not to get added to the server list.

2020-12-05 15:52 UTC, Vandomas commented
**Господа, ваше место у параши.**
Закрыт Пулл.

2020-12-05 16:37 UTC, Volas171 commented
### stop it get some help
there’s already 3 russian servers at the list..... .ru shouldn’t be there anyways lul

2020-12-05 17:24 UTC, iLagSoUhax commented
No, why, here's a shit ton of reasons why .ru is shit:

Reasons for which we hate Mindustry.ru:

- Their admins abuse A LOT.
- In April, I beat a moderator on PvP, so he leaked my ip in the chat, then kicked me.
- It is pay-to-win, you can buy admin and unbans with money.
- Their moderators organise griefing sessions on the servers that compete with them.
- False advertisement: promising stuff that doesn't exist.
- Stealing popular mods and editing them without permission, then, they claim it as their own, without giving any credit to the original creator.
- Mindustry has it's own copyright. We will call it copyright A. Well, Mindustry.ru made its own client, and it has its own copyright, which we will call copyright B. And the copyright belongs to .ru instead of Anuke. They basically tried to enforce their own copyright onto Mindustry.
- They ripped gamemodes off multiple servers. Once tower defense appeared on .io (an actually good server), a few weeks later it also appeared on .ru out of nowhere, and they didn't even ask for permission. To avoid accusations, they changed the gamemode's name, even though it was actually the same as the stolen one in terms of gameplay.
- Making a pull-request about v6 on their server. The pull-request got 5 likes and 60 dislikes. Then, they made another pull-request, where they recommended people to "not make tough reactions". That PR had 0 likes and 46 dislikes. There was a good comment which said "and we also recommend you to not make the same PR twice, just because the first one got disliked". They also forced their players to go and make good reactions on the PR, but it didn't work, because there are few likes on it.
- Making people advertise their server on other servers (I saw multiple people joining .pl, and saying "go join Mindustry.ru! best server! free admin!", or having people with names like "mindustry.ru best server!" join).
- Whenever someone trash-talks mindustry.ru, the moderators literally write a complaint to Anuke himself. They can't take criticism.

List by iutisteli

And, it's a bit egocentric to put yourself on top of the server list. by a bit, i mean a lot. Go commit delete server.

2020-12-05 17:25 UTC, iLagSoUhax requested changes
Don't.

2020-12-05 17:35 UTC, DarkBrick requested changes
Don't do this? Duh

2020-12-05 17:45 UTC, Quezler commented on servers_v6.json
> +    "address": ["mindustry.ru:6567", "mindustry.ru:6577", "mindustry.ru:6587", "mindustry.ru:6597", "mindustry.ru:6667", "mindustry.ru:6676",]
```suggestion
    "address": ["mindustry.ru:6567", "mindustry.ru:6577", "mindustry.ru:6587", "mindustry.ru:6597", "mindustry.ru:6667", "mindustry.ru:6676"]
```

2020-12-05 17:48 UTC, sowseefzer commented
> > > А смысл? Ваш сервер никому не нужен, +учитывая его историю и как он вел себя. +Донат. Хоть Анюку по боку, но комьюнити не наплевать на чадо Анюка. И допустить вот такой сервер в глобал они не допустят. Против удаление вашего сервера с глобалов было выдвинуто пару пуллов, ваш пулл с добавлением в глобал потерпел фиаско. Что в этот раз изменено? Да собственно ничего. Я не хочу разводить тут срач, потому что будет плохо всем. Просто говорю факт — комьюнити против вашего сервера. +Из-за вашего сервера и понижается оценка игры в плеймаркете, что играет ключевую роль в продвижении игры в маркете. Никто же не хочет играть в игру, где плохие отзывы? И в последний раз. Нормальное, продвинутое комьюнити(а это все комьюнити миндастри) против вас и вашего сервера, потому что из-за него кучу бед.
> > 
> > 
> > что они делали? @Makc-Carbon
> 
> Как что? Пиарились даже на серверах других серверов, пропихивали свой лаунчер, в котором кстати есть вирусы, продавали админки, даже доступ к консоли, использовали хаб человека, которого же и забанили в этом хабе(я знаком с человеком, которого забанили), даже дестабилизация других серверов была. И после такого(и это не все) они достойны быть среди глобальных? После того, что вообще должно их полностью запретить

Пиздеж, я думал что будут норм аргументы, а тут опять пиздеж

2020-12-05 18:18 UTC, Volas171 requested changes

2020-12-05 18:18 UTC, Volas171 commented on servers_v6.json
> +    "address": ["mindustry.ru:6567", "mindustry.ru:6577", "mindustry.ru:6587", "mindustry.ru:6597", "mindustry.ru:6667", "mindustry.ru:6676",]
```suggestion
  
```

2020-12-05 18:20 UTC, Volas171 requested changes

2020-12-05 18:20 UTC, Volas171 commented on servers_v6.json
> +  {
```suggestion
```

2020-12-05 18:20 UTC, Volas171 commented on servers_v6.json
> +    "name": "Mindustry.ru",
```suggestion
```

2020-12-05 18:20 UTC, Volas171 commented on servers_v6.json
> +    "address": ["mindustry.ru:6567", "mindustry.ru:6577", "mindustry.ru:6587", "mindustry.ru:6597", "mindustry.ru:6667", "mindustry.ru:6676",]
```suggestion
```

2020-12-05 18:20 UTC, Volas171 commented on servers_v6.json
> +  },
```suggestion
  
```

2020-12-05 18:22 UTC, Volas171 commented
![00A560F7-4809-4FD7-BE01-86F524443EDD](https://user-images.githubusercontent.com/60143910/101260288-db124c00-36fc-11eb-9ada-2e19bdd6b92e.png)

2020-12-05 19:19 UTC, TheSlaylord commented on servers_v6.json
> +    "address": ["mindustry.ru:6567", "mindustry.ru:6577", "mindustry.ru:6587", "mindustry.ru:6597", "mindustry.ru:6667", "mindustry.ru:6676",]
completely agreed

2020-12-05 19:54 UTC, DeltaNedas requested changes
no

2020-12-05 20:16 UTC, CBS-Boss80307 commented
DON'T ADD THIS DISORGANZINED SERVER ANUKE!

2020-12-05 21:08 UTC, bvcbvc commented
this is why your server is gonna die lol

2020-12-05 21:09 UTC, bvcbvc commented
id say just sort the list by amount of players but then ru would likely be at top so no

2020-12-05 21:16 UTC, BlueWolf3682 commented
road to 50 dislikes :eyes:

2020-12-05 22:51 UTC, Bohaska commented
A better idea will be to lock the ability for Mindustry.ru to be in the server list unless they pledge to make some changes to get a higher reputation in the Mindustry community

2020-12-05 23:00 UTC, Bohaska requested changes
Not that this is a good suggestion, but order the servers by alphabetical order instead of putting yours on the top.

2020-12-05 23:05 UTC, Volas171 commented
yes but .... community won't allow the server to be on the list anyway.

2020-12-05 23:45 UTC, Bohaska commented
> yes but .... community won't allow the server to be on the list anyway.

Anuke is the final decider of this type of thing, not the community.

2020-12-05 23:48 UTC, Bohaska commented
> yes but .... community won't allow the server to be on the list anyway.

Read my previous reply

2020-12-05 23:51 UTC, Bohaska commented
> No, why, here's a shit ton of reasons why .ru is shit:
> 
> Reasons for which we hate Mindustry.ru:
> 
> * Their admins abuse A LOT.
> * In April, I beat a moderator on PvP, so he leaked my ip in the chat, then kicked me.
> * It is pay-to-win, you can buy admin and unbans with money.
> * Their moderators organise griefing sessions on the servers that compete with them.
> * False advertisement: promising stuff that doesn't exist.
> * Stealing popular mods and editing them without permission, then, they claim it as their own, without giving any credit to the original creator.
> * Mindustry has it's own copyright. We will call it copyright A. Well, Mindustry.ru made its own client, and it has its own copyright, which we will call copyright B. And the copyright belongs to .ru instead of Anuke. They basically tried to enforce their own copyright onto Mindustry.
> * They ripped gamemodes off multiple servers. Once tower defense appeared on .io (an actually good server), a few weeks later it also appeared on .ru out of nowhere, and they didn't even ask for permission. To avoid accusations, they changed the gamemode's name, even though it was actually the same as the stolen one in terms of gameplay.
> * Making a pull-request about v6 on their server. The pull-request got 5 likes and 60 dislikes. Then, they made another pull-request, where they recommended people to "not make tough reactions". That PR had 0 likes and 46 dislikes. There was a good comment which said "and we also recommend you to not make the same PR twice, just because the first one got disliked". They also forced their players to go and make good reactions on the PR, but it didn't work, because there are few likes on it.
> * Making people advertise their server on other servers (I saw multiple people joining .pl, and saying "go join Mindustry.ru! best server! free admin!", or having people with names like "mindustry.ru best server!" join).
> * Whenever someone trash-talks mindustry.ru, the moderators literally write a complaint to Anuke himself. They can't take criticism.
> 
> List by iutisteli
> 
> And, it's a bit egocentric to put yourself on top of the server list. by a bit, i mean a lot. Go commit delete server.

Add pictures that prove this please. Documentary evidence beats all other types of evidence.

2020-12-06 00:07 UTC, DeltaNedas commented
50 vs 1, i don't think you need any proof.
a server with such a poor reputation shouldn't be promoted.

2020-12-06 01:09 UTC, Volas171 commented
> > No, why, here's a shit ton of reasons why .ru is shit:
> > Reasons for which we hate Mindustry.ru:
> > 
> > * Their admins abuse A LOT.
> > * In April, I beat a moderator on PvP, so he leaked my ip in the chat, then kicked me.
> > * It is pay-to-win, you can buy admin and unbans with money.
> > * Their moderators organise griefing sessions on the servers that compete with them.
> > * False advertisement: promising stuff that doesn't exist.
> > * Stealing popular mods and editing them without permission, then, they claim it as their own, without giving any credit to the original creator.
> > * Mindustry has it's own copyright. We will call it copyright A. Well, Mindustry.ru made its own client, and it has its own copyright, which we will call copyright B. And the copyright belongs to .ru instead of Anuke. They basically tried to enforce their own copyright onto Mindustry.
> > * They ripped gamemodes off multiple servers. Once tower defense appeared on .io (an actually good server), a few weeks later it also appeared on .ru out of nowhere, and they didn't even ask for permission. To avoid accusations, they changed the gamemode's name, even though it was actually the same as the stolen one in terms of gameplay.
> > * Making a pull-request about v6 on their server. The pull-request got 5 likes and 60 dislikes. Then, they made another pull-request, where they recommended people to "not make tough reactions". That PR had 0 likes and 46 dislikes. There was a good comment which said "and we also recommend you to not make the same PR twice, just because the first one got disliked". They also forced their players to go and make good reactions on the PR, but it didn't work, because there are few likes on it.
> > * Making people advertise their server on other servers (I saw multiple people joining .pl, and saying "go join Mindustry.ru! best server! free admin!", or having people with names like "mindustry.ru best server!" join).
> > * Whenever someone trash-talks mindustry.ru, the moderators literally write a complaint to Anuke himself. They can't take criticism.
> 
> Add pictures that prove this please. Documentary evidence beats all other types of evidence and that’s why it’s the gold standard.

sure

2020-12-06 01:12 UTC, Volas171 commented
![image](https://user-images.githubusercontent.com/60143910/101268849-23019500-3736-11eb-96db-ad305d4b1a5c.png)

2020-12-06 01:12 UTC, Volas171 commented
![image](https://user-images.githubusercontent.com/60143910/101268855-33197480-3736-11eb-9648-da3558822290.png)
they used alts to merge their other pull requests

2020-12-06 01:13 UTC, Volas171 commented
![image](https://user-images.githubusercontent.com/60143910/101268869-55ab8d80-3736-11eb-948b-a145aab9f74f.png)

2020-12-06 01:30 UTC, Bohaska commented
> 50 vs 1, i don't think you need any proof.
> a server with such a poor reputation shouldn't be promoted.

That is a logical fallacy

2020-12-06 01:32 UTC, Bohaska commented
Send me the links to the message instead, the pictures are to blurry

2020-12-06 01:33 UTC, Volas171 commented
#2329

2020-12-06 01:37 UTC, Volas171 commented
aswell as https://www.virustotal.com/gui/file-analysis/ZjAwYTQ3YTE3MTBhODMzZDRjYjA0YjBiM2M0YTJiYTI6MTU5ODY2Nzg1Nw==/detection , to virustotal to flag a zip that many times means it's definetly something sketchy

2020-12-06 01:38 UTC, Volas171 commented
![image](https://user-images.githubusercontent.com/60143910/101269170-ba1c1c00-3739-11eb-804c-b870fb7cc8f2.png) not only that , their client redirects you to "non existing links" that i like to call ip grabbers

2020-12-06 03:28 UTC, Volas171 commented
they leak ips, recommend to download malware and "harass" players

2020-12-06 04:35 UTC, Bohaska commented
Ok, they seem bad. If you hate them so much, then make a better Russian Mindustry server then them. Anuke has said that one of the main reasons for not removing them is because there are no other Russian servers in Mindustry.

2020-12-06 04:55 UTC, Volas171 commented
inform yourself please, C.A.M.S server group is 2 replacements of .ru so , no this server can stay as it is without being at the list

2020-12-06 05:00 UTC, Bohaska commented
Please read pr 2329 and Anuke’ s responses

2020-12-06 05:06 UTC, Volas171 commented
i have done that but you don't understand , there's already replacements for this server

2020-12-06 05:09 UTC, Bohaska commented
@Anuken we really need to decide the fate of Mindustry.ru soon... this is getting out of hand

2020-12-06 05:10 UTC, Bohaska commented
I honestly envy the attention that mindustry.ru related pull requests get... its like MindustryRu is even more famous then Anuke

2020-12-06 05:11 UTC, Volas171 commented
It's not getting out of hand tho , it's just a server, there's currently 2 public servers hosted in russia

2020-12-06 05:13 UTC, Volas171 commented
> I honestly envy the attention that mindustry.ru related pull requests get... its like MindustryRu is even more famous then Anuke

yeah lol , community hates this server since versions ago ..... the developer decides the fate but the community hates it that's it lol

2020-12-06 05:17 UTC, Bohaska commented
Give me a history of Mindustry.ru, how it started, why it was started, and how did it become what it is now?

2020-12-06 07:51 UTC, RebornTrack970 commented
Its basicaly one of those servers where you have to pay to get stuff. P2W

2020-12-06 07:56 UTC, Slava0135 commented
The only reason they have online is cos they probably bougth advertisng on Yandex search system. One of the first links lead to mindistry.ru .Their site "tries" to look like it's official. Of course there will be a lot of people playing on it especially considering that itch.io is English and you need to buy Steam version.

2020-12-06 07:58 UTC, Slava0135 commented
All I know is that they care about money not players

2020-12-06 08:09 UTC, Slava0135 commented
The main thing is that it's COMMERCIAL project. Why should we put it on server list?

2020-12-06 11:14 UTC, sk7725 requested changes
no

2020-12-06 11:19 UTC, sk7725 commented
> Ok, they seem bad. If you hate them so much, then make a better Russian Mindustry server then them. Anuke has said that one of the main reasons for not removing them is because there are no other Russian servers in Mindustry.

Can you provide image evidence?

2020-12-06 11:20 UTC, Kieaer commented
It seems to be seeing the old griefer servers.
I need 🍿

2020-12-06 11:20 UTC, sk7725 commented
> @Volas171 Give me a history of Mindustry.ru, how it started, why it was started, and how did it become what it is now?

they are not obliged to. If you want the history, go research it yourself.

2020-12-06 11:22 UTC, sk7725 commented
> I honestly envy the attention that mindustry.ru related pull requests get... its like MindustryRu is even more famous then Anuke

Add pictures that prove this please. Documentary evidence beats all other types of evidence and that’s why it’s the gold standard.

2020-12-06 11:54 UTC, DeltaNedas commented
> Ok, they seem bad. If you hate them so much, then make a better Russian Mindustry server then them. Anuke has said that one of the main reasons for not removing them is because there are no other Russian servers in Mindustry.

pandorum and routerchain exist which are much, much better

2020-12-06 11:55 UTC, Slava0135 commented
> > Ok, they seem bad. If you hate them so much, then make a better Russian Mindustry server then them. Anuke has said that one of the main reasons for not removing them is because there are no other Russian servers in Mindustry.
> 
> pandorum and routerchain exist which are much, much better

True

2020-12-06 13:05 UTC, Bohaska commented
> > I honestly envy the attention that mindustry.ru related pull requests get... its like MindustryRu is even more famous then Anuke
> 
> Add pictures that prove this please. Documentary evidence beats all other types of evidence and that’s why it’s the gold standard.

Read someone else’s reply to that request. I need to sleep, and I’m on an iPad.

2020-12-06 13:06 UTC, Bohaska commented
And guys, you don’t need to respond to a question more then once.

2020-12-06 13:22 UTC, sk7725 commented
> > > I honestly envy the attention that mindustry.ru related pull requests get... its like MindustryRu is even more famous then Anuke
> > 
> > 
> > Add pictures that prove this please. Documentary evidence beats all other types of evidence and that’s why it’s the gold standard.
> 
> Read someone else’s reply to that request. I need to sleep, and I’m on an iPad.

Those quotes are yours, don't throw words around that you cannot accomplish yourself. This proves you just want a grudge to retort, and that we should just not pay attention to your words.

2020-12-06 14:15 UTC, Volas171 commented
After some further research I found their website has about 50 yandex ad trackers

2020-12-06 14:19 UTC, Volas171 commented
i cant show them on a screenshot since for some reason I couldn't screenshot but you can still try it yourself by using any adblocker on and it will trigger

2020-12-06 15:34 UTC, PAP6 commented
~~I saw only 4.~~
![image](https://user-images.githubusercontent.com/68839421/101284572-60484e80-382c-11eb-82e7-85b2573d021b.png)

2020-12-06 17:10 UTC, Volas171 commented
sorry I wrote 50 instead of 5

2020-12-06 18:46 UTC, BasedUser commented
Duplicate of #3039.

2020-12-06 20:08 UTC, Volas171 commented
Duplicate of #3072.

2020-12-06 20:08 UTC, Volas171 commented
Duplicate of #3072.

2020-12-06 20:40 UTC, Anuken commented
# The time has come for me to deal with this issue.

Let me examine the case against mindustry.ru. 

## Here are things I know for a **fact**.

- mindustry.ru called itself an "official" Russian server on the list. I had to step in and ask for a change.
- mindustry.ru created a public mod that stole content from another mod. The author was not notified or credited, and I had to step in and ask for them to remove the content.
- After mindustry.ru created a pull request and received a flood of -1s, they created another one in hope of avoiding hate. *(It didn't work.)*
- In my brief playtime on one of the .ru v5 servers, I saw swearing and toxicity.
- In this PR, mindustry.ru put their servers on the top of the current server list, at a time when many were still running a version of the game where servers were *not* being listed by ping.
- mindustry.ru reacted with `+1`, `smile`, `heart` and `laughing` emojis *on their own pull request*, presumably in an attempt to make the PR look better. This is very shady behavior.
- Some of the GitHub accounts supporting mindustry.ru in the initial debate were newly created (https://github.com/Anuken/Mindustry/pull/2329#issuecomment-673338214). Were these sockpuppet accounts, or just supporters wanting to make their voice heard? I don't know, but it's at least *slightly* suspicious.
- mindustry.ru sells unbans/unmutes. While I am not against some monetization on servers - *servers cost money to run, after all* - this is a very strange and questionable way of making money.
- The admin role has been sold on mindustry.ru at some point.
- I get contacted by the mindustry.ru owner rather frequently, especially when compared to other server owners.
- There are alternative Russian servers on the list now.
- The mindustry.ru launcher makes a lot of questionable requests, and sets off many anti-viruses. Are these false positives? Maybe, but I don't have the patience to look through the source code and find out.
- Many active members of the community do not like mindustry.ru. I have not seen many reputable members that do.
- mindustry.ru is easily the most controversial server, and people have been hating on it for a *very* long time.

## Here are some things that are *most likely* true.

- The owner of mindustry.ru has been known to advertise in PMs. While the last known incident of this was a long time ago, it still happened, and I doubt the images I saw were faked.
- Advertisements of mindustry.ru have appeared on other servers, in the form of message blocks. Tracing this back to the source would be impossible at this point, but the evidence is unlikely to be fake.

## Here are some things that *players have said* about mindustry.ru - these **may or may not** be true.

- The server admins abuse their powers.
- The whole server is toxic.
- They may have ties to griefer groups.
- They may encourage their players to go and advertise on other servers.
- Their admins may have posted NSFW logic art at some point.

# The Verdict

Taken separately, most of these issues are fairly minor. You could claim that many are simple missteps or mistakes. 

*However*, when I look at the whole picture, I cannot deny that this server is *problematic* (to say the least), and should not be on this list. ***I don't want to deal with this server anymore***, and neither does a large chunk of the community.

I will be closing and locking all relevant PRs. There is nothing left to discuss.
Note that mindustry.ru will *not* be removed from the 5.0 server list, as that version isn't supported anyway.

*To the mindustry.ru owner and/or staff: Please don't try to contact me or try to change my mind. This decision is final. You can still do whatever you want with the server, but it will not be placed on the public list.*

2020-12-06 20:40 UTC, closed without merging