Ore priority fix
Anuken/Mindustry pull request #3894
Opened 2020-12-09 19:34 UTC by Slava0135

Sand low priority is hard coded. Bad for mods having floors with drops.

For some reason other.floor().playerunmineable() is always true so priority doesn't work

2020-12-09 19:46 UTC, Slava0135 commented
Now it's working. The reason I am complaining about it is cos in my mod I made snow floors drop snowballs but the thing is that it makes hard to mine ores on snow...

2020-12-09 19:52 UTC, Slava0135 commented
with fix:

![now](https://user-images.githubusercontent.com/40753025/101680013-2451fb00-3a71-11eb-9ab0-dea235bb8b7b.gif)

2020-12-09 19:52 UTC, summetdev requested changes

2020-12-09 19:52 UTC, summetdev commented on core/src/mindustry/world/blocks/production/Drill.java
> +import java.util.Comparator;
`java.util` import detected :eyes:

> Do not use incompatible Java features.

2020-12-09 19:53 UTC, Slava0135 commented on core/src/mindustry/world/blocks/production/Drill.java
> +import java.util.Comparator;
oh no

2020-12-09 19:54 UTC, Slava0135 commented
no fix
![before](https://user-images.githubusercontent.com/40753025/101680286-83b00b00-3a71-11eb-964b-a5538a713964.gif)

2020-12-09 20:02 UTC, BlueWolf3682 commented
amazing item sprite, 11/10 reskin

2020-12-09 20:04 UTC, Slava0135 commented
> amazing item sprite, 11/10 reskin

~~is that a white coal or coke?~~

2020-12-09 20:09 UTC, BlueWolf3682 commented
coal's evil twin brother

2020-12-09 20:44 UTC, summetdev commented on core/src/mindustry/world/blocks/production/Drill.java
> +
two empty lines.

```suggestion

```

2020-12-09 20:45 UTC, summetdev commented on core/src/mindustry/world/blocks/production/Drill.java
> +import java.util.Comparator;
(you should remove `import` too)

2020-12-10 07:01 UTC, Slava0135 commented
a N u K e D i D i T h I m S e L f

2020-12-10 07:01 UTC, closed without merging