Update servers_v6.json
Anuken/Mindustry pull request #4194
Opened 2020-12-31 12:12 UTC by owler0954

2020-12-31 12:14 UTC, Makc-Carbon commented
Первый сервер с минигеймами :eyes: . Однозначно за

2020-12-31 12:19 UTC, SkinH commented
### **Это будет интересный сервер с веселыми режимами игры!!!**

2020-12-31 12:43 UTC, TheXeony commented
Я за

2020-12-31 14:12 UTC, summetdev requested changes

2020-12-31 14:12 UTC, summetdev commented on servers_v6.json
> +    "address": ["shizashizashiza.ml:6567"]
6567 port is default, you can omit it
```suggestion
    "address": ["shizashizashiza.ml"]
```

2020-12-31 16:02 UTC, sowseefzer commented
Иа протиф

2020-12-31 16:38 UTC, VitLogArx commented
Actually this is very good idea. Anuke, make a Christmas present to mindistry community, add server to global list.

2021-01-05 21:23 UTC, Anuken commented on servers_v6.json
> +  {
Needs a display name for the list.

2021-01-06 21:13 UTC, SkinH reviewed
Add name

2021-01-07 10:00 UTC, owler0954 commented on servers_v6.json
> +  {
Done

2021-01-08 16:21 UTC, merged