allows player to transfer items with no items if in formation
Anuken/Mindustry pull request #4273
Opened 2021-01-06 15:35 UTC by Slava0135

https://user-images.githubusercontent.com/40753025/103786687-c30c5000-504d-11eb-8aff-9c6e1660c506.mp4

Also fixes some issues while trying to transfer items with units that have no items or their item doesn't fit container requirements

2021-01-06 15:49 UTC, Slava0135 commented
Uploading Peek 2021-01-06 18-46.mp4…

2021-01-09 15:42 UTC, Anuken requested changes

2021-01-09 15:42 UTC, Anuken commented on core/src/mindustry/graphics/OverlayRenderer.java
> +            if(input.canDropItem() && tile != null && tile.interactable(player.team()) && (tile.acceptStack(player.unit().item(), player.unit().stack.amount, player.unit()) > 0 || player.unit().forma
This is buggy. I can be in a formation with no items, and yet the unload cursor will still display and I will be able to drag a non-existent item to a container.

If the player has no items and tries to drag a formation member's item into a container, the item displayed will be the last item the player used, not the actual item that will be deposited.

2021-01-09 15:42 UTC, Anuken commented on core/src/mindustry/input/InputHandler.java
> +        if(build == null || build.items == null || unit == null || unit.stack.amount <= 0) return;
Buildings should still handle items even if the unit is null. Not doing this will cause opportunities for desync.

2021-01-09 15:42 UTC, Anuken commented on core/src/mindustry/input/InputHandler.java
> +        return player.within(x, y, playerSelectRange) && (player.unit().stack.amount > 0 || player.unit().formation != null);
The player should not be tappable when there are no items in the formation.

2021-01-09 15:42 UTC, Anuken commented on core/src/mindustry/ui/fragments/BlockInventoryFragment.java
> -                Boolp canPick = () -> player.unit().acceptsItem(item) && !state.isPaused() && player.within(tile, itemTransferRange);
This means that the cursor will still display even when the player doesn't have room for the item. Not desirable.

2021-01-10 13:36 UTC, Slava0135 commented
Made that now item is not being drown while trying to transfer items in formation. I am not really sure what is the best alternative.
 
https://user-images.githubusercontent.com/40753025/104124406-c0696d80-5361-11eb-8bd3-2827e3ede9f4.mp4

2021-02-03 01:12 UTC, Transigence commented
>  Peek.2021-01-06.18-29.mp4 
> Also fixes some issues while trying to transfer items with units that have no items or their item doesn't fit container requirements
I would like to suggest a more elegant way to solve this problem. Not elegant for the person implementing it, but more elegant for the player.

Instead of allowing the player to drop from wingmen, modify the behavior of putting/dropping such that an amount, up to the space available in the container, is taken evenly from all of the members of the wing, with any remainders taken finally from the player, so that the player is always the last one left with any items.

2022-03-10 21:26 UTC, Anuken commented
(formations gone)

2022-03-10 21:26 UTC, closed without merging