Add kr server
Anuken/Mindustry pull request #4378
Opened 2021-01-19 11:47 UTC by Kieaer

There're many steam servers that ban and kick users who still enter even though warnings popup have been added. https://github.com/Anuken/Mindustry/pull/4042

I looked for other measures, change warning texts and it was https://github.com/Anuken/Mindustry/pull/4131.
but didn't work!

I recently found out that most of them are Koreans.
kr server is still under development, but it may be able to solve this problem.

The server check/maintence every Saturday/Sunday.
At the time of writing, the server was not opened because the CPU was being upgraded.

2021-01-19 12:23 UTC, Blockzilla101 requested changes

2021-01-19 12:23 UTC, Blockzilla101 commented on servers_v6.json
> +    "name": "Korea"
missing comma
```suggestion
    "name": "Korea",
```

2021-01-19 13:06 UTC, DeltaNedas commented on servers_v6.json
> +    "name": "Korea"
bruh

2021-01-19 16:08 UTC, Kieaer commented on servers_v6.json
> +    "name": "Korea"
🤦

2021-01-19 21:22 UTC, Kieaer commented
The server is open and playable, but server information can't be checked from outside.
Maybe it's presumed to be a carrier bug.

2021-01-19 23:40 UTC, Anuken commented
> The server is open and playable, but server information can't be checked from outside.
Maybe it's presumed to be a carrier bug.

That means it won't show up in the server list.

2021-01-21 12:14 UTC, Kieaer commented
@Anuken Fixed.

2021-01-21 14:13 UTC, merged