Secondary bloom layers.
Anuken/Mindustry pull request #4447
Opened 2021-01-27 02:05 UTC by MEEPofFaith

Some layers that bloom above flying units, allowing for bullets and effects that bloom above them, as well as making launchpad engine draw over flying units while still blooming.

https://user-images.githubusercontent.com/54301439/105931969-06c8f880-6001-11eb-80cd-32095cd5f033.mp4

(Note: I have no idea what performance issues, if any, this'll cause.)

2021-01-27 04:07 UTC, sk7725 requested changes
About half of current effects need to be moved above the units (ex. all StatusEffect's effects). 
Some bullets need to be moved above too (don't forget to move its shootEffect and trailEffect up the layer too!).
And maybe rename air and sky to something that implies that this layer contains bloom.

2021-01-27 04:57 UTC, MEEPofFaith commented
I had no idea what to name them so I just gave them "high altitude" sounding names.

2021-01-27 05:32 UTC, MEEPofFaith commented
![java_tIS5tpetht](https://user-images.githubusercontent.com/54301439/105947466-012ddb80-601e-11eb-8263-fea90b5e2588.png)

https://user-images.githubusercontent.com/54301439/105947471-02f79f00-601e-11eb-9916-ee460fd1d63f.mp4

2021-05-05 01:10 UTC, sk7725 commented
what why?

2021-05-05 04:05 UTC, MEEPofFaith commented
wjoops

2025-02-06 19:22 UTC, Anuken commented
Very stale PR; I think the potential performance impact and complexity isn't worth the minor improvements.

2025-02-06 19:22 UTC, closed without merging