Add servers to global list
Anuken/Mindustry pull request #4761
Opened 2021-02-23 08:58 UTC by Darkness6030

Mindurka.ru - HUB
Mindurka.ru:3000 - ATTACK
Mindurka.ru:4000 - PVP

2021-02-23 09:06 UTC, VadrixMashina commented
Yes

2021-02-23 09:43 UTC, blackosp54 commented
Normal server, deserves a global!

2021-02-23 16:29 UTC, misaka0954 approved these changes

2021-02-23 21:28 UTC, RebornTrack970 commented
Why, what is the thing with everyone trying to add Vanilla servers?
Cant you just be or original?
Isnt there already like 7 vanilla servers?
Thats just deviding the player base...

2021-02-24 02:57 UTC, unjown commented
is this another ru server?

2021-02-24 06:47 UTC, MindustryRu commented
@unjown 
No, these are not our servers.

2021-02-25 08:12 UTC, KotMilk commented
Good server

2021-02-25 08:13 UTC, KotMilk commented
> @unjown
> Нет, это не наши серверы.

Ygy

2021-02-25 10:22 UTC, Darkness6030 commented
We have also added Survival and Sandbox servers to our HUB!
You should see 'em!

2021-02-25 10:32 UTC, RebornTrack970 requested changes
You should only add the hub as you can go to others from there.

2021-02-25 13:11 UTC, blackosp54 commented
> это еще один сервер mindustry.ru?

your logic goes off scale, don't you really understand what.RU it's just a domain

2021-02-25 18:28 UTC, Darkness6030 commented
> You should only add the hub as you can go to others from there.

Hmm, i forgot

2021-02-26 07:33 UTC, RebornTrack970 commented on servers_v6.json
> +    "address": ["mindurka.ru", "mindurka.ru:3000", "mindurka.ru:4000"]
Please only add the hub.

2021-02-26 14:54 UTC, Darkness6030 commented on servers_v6.json
> +    "address": ["mindurka.ru", "mindurka.ru:3000", "mindurka.ru:4000"]
Done

2021-02-26 16:11 UTC, RebornTrack970 commented
Much better.

2021-02-26 16:11 UTC, RebornTrack970 approved these changes

2021-02-26 16:13 UTC, merged