Remove MinDurka from the global list
Anuken/Mindustry pull request #5052
Opened 2021-04-03 13:52 UTC by MindustryRu

[ENG]
This server organizes rallies, riots, calls for malicious actions.

The Administration repeatedly violated its own rules, their administrators violated even more and were not punished, everyone suggested that the administrator put a lot of effort into it and we cannot simply remove him.

Also, this server has repeatedly arranged Ddos servers, they broke the servers on purpose and the administration encouraged others to do it.

After our return, we diligently set about destroying such servers.
MinDurka was also joined by the founder of MinDurka.ru who distributed hentai (NSWF) for a long time at http://mindurka.ru/

MinDurka copies everything from our server, discord design (Changed a couple of labels and think imperceptibly), the administrator himself indicates that he is too lazy to do something and is easier to copy than to come up with something of his own.

Conspiracy and ask people to download the O7 client (mod) and break the servers.

All docks in screenshots (Spoiler)

Their user violated the rules of Discord (https://discord.com/terms | https://discord.com/guidelines) and his account was blocked, deliberately asked us to return him and return all roles, which we refused because we will not tolerate users whom Discord itself is trying to protect from society, in this regard, he joined the ranks of those same attackers who break the servers. (This is Nexor for clarification)

Uv. developer, I ask you to help deal with this, since they do not care and they think too much of themselves.
P.S These are the same guys who convinced you to remove us, but in fact it turned out that they simply did not want competition.

To all this, I want to say that Mindustry.ru does not harm their servers even in such a difficult moment, we tolerate and will solve this in a more cultured way, involving the developer.

[RUS]
Этот сервер устраивает митинги, бунты, призывают к вредоносным действиям.

Неоднократно Администрация нарушала свои же правила, их администраторы нарушали еще больше и небыли наказаны, все сводили к тому что администратор вложил много сил и мы не можем его попросту убрать.

Так же этот сервер неоднократно устраивал Ddos серверов, ломали сервера намеренно и администрация призывала это делать других.

После нашего возвращения мы усердно взялись за истребление таких серверов.
Так же к MinDurka присоединился основатель MinDurka.ru который продолжительное время распростронял hentai(NSWF) по адресу http://mindurka.ru/

MinDurka копирует все с нашего сервера, оформление discord(Изменили пару надписей и думают незаметно), сам же администратор указывает на то что ему лень что-то делать и проще скопировать чем придумать что-то свое.

Устраивают заговоры и просят людей скачивать клиент(мод) O7 и ломать сервера.

Все док-ва в скриншотах(Спойлер)

Их пользователь нарушил правила Discord [(](https://discord.com/terms) | [)](https://discord.com/guidelines) и его аккаунт был заблокирован, намеренно просил нас его вернуть и вернуть все роли, на что мы отказали так как не потерпим пользователей которых сам Discord пытается оградить от общества, в связи с этим он примкнул к рядам тех самых злоумышленников которые ломают сервера.(Это Nexor для уточнения)

Ув.разработчик, прошу вас помочь разобраться с этим, так как им плевать и они возомнили из себя слишком много.
P.S Это те самые ребята которые вас убеждали нас удалить, но по факту оказалось что они просто не хотели конкуренции.

На все это хочу сказать, что Mindustry.ru ни как не вредит их серверам даже в такую трудную минуту, мы терпим и будем решать это более культурнее привлекая разработчика.

<details> 
<summary>ScreenShots </summary>
![Screenshot_20210403-160237](https://user-images.githubusercontent.com/62647000/113480354-1b70b380-94be-11eb-8d98-efb09891bd0a.png)
![Screenshot_20210403-160310](https://user-images.githubusercontent.com/62647000/113480359-1d3a7700-94be-11eb-917c-803f2adad256.png)
![Screenshot_20210403-160415](https://user-images.githubusercontent.com/62647000/113480360-1dd30d80-94be-11eb-9adb-d95c0fd0fcfd.png)
![Screenshot_20210403-160629](https://user-images.githubusercontent.com/62647000/113480361-1dd30d80-94be-11eb-84b2-dbe3e19ed90f.png)
![Screenshot_20210403-155127](https://user-images.githubusercontent.com/62647000/113480362-1e6ba400-94be-11eb-9ed4-b45218020df1.png)
![Screenshot_20210403-155343](https://user-images.githubusercontent.com/62647000/113480363-1f043a80-94be-11eb-99ea-98f4fb9c3790.png)
![Screenshot_20210403-155953](https://user-images.githubusercontent.com/62647000/113480364-1f9cd100-94be-11eb-974d-f38e5d804ec5.png)
![Screenshot_20210403-160017](https://user-images.githubusercontent.com/62647000/113480366-1f9cd100-94be-11eb-87df-9090aa8f4958.png)
![Screenshot_20210403-160126](https://user-images.githubusercontent.com/62647000/113480367-20356780-94be-11eb-99fa-fe8fa5dff85a.png)
![Screenshot_20210403-160142](https://user-images.githubusercontent.com/62647000/113480368-20cdfe00-94be-11eb-9677-4aedc7a4ea87.png)
![Screenshot_20210403-182407](https://user-images.githubusercontent.com/62647000/113480371-24618500-94be-11eb-9415-7cac1152c676.png)
![Screenshot_20210403-182356](https://user-images.githubusercontent.com/62647000/113480372-24fa1b80-94be-11eb-8cb6-554037a4f958.png)
![Screenshot_20210403-182401](https://user-images.githubusercontent.com/62647000/113480374-2592b200-94be-11eb-8353-05a81826adb8.png)
</details>

2021-04-03 14:02 UTC, Darkness6030 commented
Не хочу начинать срач. Начните его сами, а я посмотрю

2021-04-03 14:03 UTC, Darkness6030 commented
Но ни один из аргументов не является правдой. Все это ЛОЖЬ. @Anuken, закрывай PR

2021-04-03 14:03 UTC, Somka000 commented
I like this war

2021-04-03 14:04 UTC, RoomServers commented
Картина выглядит так: мастер вбрасывает фейковую инфу против других серверов, при этом возвышая свой сервер, типо он прекрасен, и тому подобное, конкурентов тупо банит, свои слова он тоже не подтверждает, оправдывается очередными пустыми словами, на админов и збт людей ему пофиг, кто-то обосрался? Наймём нового и не важно, чел потерял аккаунт, или сделал что-то, что портит репутацию сервера, как было и со мной, я был в збт, мне основу забанил дискорд за нарушение их политики, мастер отказался выдавать мне тут збт, потому что "не хочет спорить с дискордом"  дискорд это божество, которое по лицу ударит, если ослушаться, или че? Насчёт его работы над сервером тоже скверно, ибо ддосят .ру часто, а он тупо плечами пожимает и пофиг ему как-то, ддос шёл не от миндурки даже.

2021-04-03 14:05 UTC, MindustryRu commented
Их администрация общается именно так

![Безымянный - 1](https://user-images.githubusercontent.com/62647000/113480749-23c9ee00-94c0-11eb-9cc7-477a45ac2d69.png)


После открытия PR они хотят отмазываться.
![Screenshot_20210403-190135](https://user-images.githubusercontent.com/62647000/113480766-3e9c6280-94c0-11eb-83ff-7886da350289.png)

2021-04-03 14:07 UTC, USMP-Mandarin commented
Для начала с собой разберитесь потом к другим лезьте. За вашими серверами не следит администрация, администрация вашего сервера гриферила на миндурке и осталась безнаказанна. Ваша администрация провоцировала игроков, администраторов миндурки своими действиями и словами. Фейк инфа и провокация со стороны основателя .ру и наебалово.
![image](https://user-images.githubusercontent.com/73673886/113480757-33493700-94c0-11eb-8614-f0837fc72db6.png)
![image](https://user-images.githubusercontent.com/73673886/113480773-49ef8e00-94c0-11eb-917c-7effde4f9795.png)

Так же мастер занимался чёрным пиаром и рассылкой спама игрокам миндустри в дс в личные сообщения.

2021-04-03 14:10 UTC, RoomServers commented
> Их администрация общается именно так
> 
> ![Безымянный - 1](https://user-images.githubusercontent.com/62647000/113480749-23c9ee00-94c0-11eb-9cc7-477a45ac2d69.png)
> 
> После открытия PR они хотят отмазываться.
> ![Screenshot_20210403-190135](https://user-images.githubusercontent.com/62647000/113480766-3e9c6280-94c0-11eb-83ff-7886da350289.png)

Мне вот интересно, как личные сообщения связаны с миндуркой? Ты, мастер, в лс тоже не зайчик

2021-04-03 14:11 UTC, MindustryRu commented
> Для начала с собой разберитесь потом к другим лезьте. За вашими серверами не следит администрация, администрация вашего сервера гриферила на миндурке и осталась безнаказанна. Ваша администрация провоцировала игроков, администраторов миндурки своими действиями и словами. Фейк инфа и провокация со стороны основателя .ру и наебалово.
> ![image](https://user-images.githubusercontent.com/73673886/113480757-33493700-94c0-11eb-8614-f0837fc72db6.png)
> ![image](https://user-images.githubusercontent.com/73673886/113480773-49ef8e00-94c0-11eb-917c-7effde4f9795.png)
> 
> Так же мастер занимался чёрным пиаром и рассылкой спама игрокам миндустри в дс в личные сообщения.

На скриншоте я высказал мнения и оно полностью правдивое, вы просто слизали все у нас, включая [](https://github.com/MindustryRu/RUS-Core)

Вы же в свою очередь оскорбляли меня клоуном и геем, и только тут не надо отмазываться.

Наша администрация у вас не гриферит это вы нагло лжете, наши сервера очень хорошо модерируются, о чем свидетельствует бан лист.

2021-04-03 14:12 UTC, TheRedRio commented
Можно доказательства?

2021-04-03 14:13 UTC, USMP-Mandarin commented
> > Для начала с собой разберитесь потом к другим лезьте. За вашими серверами не следит администрация, администрация вашего сервера гриферила на миндурке и осталась безнаказанна. Ваша администрация провоцировала игроков, администраторов миндурки своими действиями и словами. Фейк инфа и провокация со стороны основателя .ру и наебалово.
> > ![image](https://user-images.githubusercontent.com/73673886/113480757-33493700-94c0-11eb-8614-f0837fc72db6.png)
> > ![image](https://user-images.githubusercontent.com/73673886/113480773-49ef8e00-94c0-11eb-917c-7effde4f9795.png)
> > Так же мастер занимался чёрным пиаром и рассылкой спама игрокам миндустри в дс в личные сообщения.
> 
> На скриншоте я высказал мнения и оно полностью правдивое, вы просто слизали все у нас, включая https://github.com/MindustryRu/RUS-Core
> 
> Вы же в свою очередь оскорбляли меня клоуном и геем, и только тут не надо отмазываться.
> 
> Наша администрация у вас не гриферит это вы нагло лжете, наши сервера очень хорошо модерируются, о чем свидетельствует бан лист.

Не надо мне рассказывать. Твой админ нейтрал был забанен за вирусные процессоры и гриферство. Если придумать тебя называют все клоуном и геем т.к. ты им и являешься. Если тебе не нравится сервер ты говоришь всем что он говно и открываешь пулл на его удаление из глобала и даже не можешь аргументировать свои действия и слова.

2021-04-03 14:14 UTC, RoomServers commented
> > Для начала с собой разберитесь потом к другим лезьте. За вашими серверами не следит администрация, администрация вашего сервера гриферила на миндурке и осталась безнаказанна. Ваша администрация провоцировала игроков, администраторов миндурки своими действиями и словами. Фейк инфа и провокация со стороны основателя .ру и наебалово.
> > ![image](https://user-images.githubusercontent.com/73673886/113480757-33493700-94c0-11eb-8614-f0837fc72db6.png)
> > ![image](https://user-images.githubusercontent.com/73673886/113480773-49ef8e00-94c0-11eb-917c-7effde4f9795.png)
> > Так же мастер занимался чёрным пиаром и рассылкой спама игрокам миндустри в дс в личные сообщения.
> 
> На скриншоте я высказал мнения и оно полностью правдивое, вы просто слизали все у нас, включая https://github.com/MindustryRu/RUS-Core
> 
> Вы же в свою очередь оскорбляли меня клоуном и геем, и только тут не надо отмазываться.
> 
> Наша администрация у вас не гриферит это вы нагло лжете, наши сервера очень хорошо модерируются, о чем свидетельствует бан лист.

Бот за бесценок написан, тебя вообще не должно волновать, кто его использует по сути

2021-04-03 14:14 UTC, MindustryRu commented
Вы очень токсичны, по этому мне не приятно с вами общаться, и ваше мнение мне не интересно, я попросил помощи у разработчика а не у вас.

2021-04-03 14:15 UTC, RoomServers commented
> Вы очень токсичны, по этому мне не приятно с вами общаться, и ваше мнение мне не интересно, я попросил помощи у разработчика а не у вас.

Докажи свои слова, если у тебя конечно есть доказательства, по мимо пустых скринов

2021-04-03 14:15 UTC, USMP-Mandarin commented
> Вы очень токсичны, по этому мне не приятно с вами общаться, и ваше мнение мне не интересно, я попросил помощи у разработчика а не у вас.

Твоё мнение тоже ни кому не важно. Я токсичен только к тем людям которые делают плохие вещи

2021-04-03 14:19 UTC, Makc-Carbon commented
Ахаххахаха, чья бы корова мычала, чья бы корова мычала....

2021-04-03 14:22 UTC, Voz-Duh approved these changes

2021-04-03 14:23 UTC, Voz-Duh commented
По-моему тут предостаточно доказательств для удаления этого сервера

2021-04-03 14:25 UTC, XEN0PHIL commented
Delete both MinDurka and Mindustry.ru from the global list, everyone got enough of this bs already.
They keep fighting each other and it's not the first PR with "look they did this bad thing", let them deal with their sweet family problems in their DM, we don't have to see it

2021-04-03 14:26 UTC, Cxyali commented
> Их администрация общается именно так
> 
> ![Безымянный - 1](https://user-images.githubusercontent.com/62647000/113480749-23c9ee00-94c0-11eb-9cc7-477a45ac2d69.png)
> 
> После открытия PR они хотят отмазываться.
> ![Screenshot_20210403-190135](https://user-images.githubusercontent.com/62647000/113480766-3e9c6280-94c0-11eb-83ff-7886da350289.png)

Это лс и тут правила не прописаны. Ты хоть раз видел чтоб я так общался в чате??? Кстати прошу заметить что я тебя не оскорблял даже, а ты нагло заявляешь про какие-то "неоднократные ddos атаки" без доказательств!

2021-04-03 14:27 UTC, Voz-Duh commented
Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)

2021-04-03 14:28 UTC, Cxyali commented
> Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
> ![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)

А это кто кст?

2021-04-03 14:29 UTC, T1murik commented
> По-моему тут предостаточно доказательств для удаления этого сервера

Это доказательства? Доказательство = обвинение + аргумент + пруф
вижу только первое

2021-04-03 14:29 UTC, Voz-Duh commented
> > Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
> > ![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)
> 
> А это кто кст?

Индивид который зашел на официальный сервер Mindustry для того что бы призвать людей к митингу

2021-04-03 14:30 UTC, MindustryRu commented
Еще немного скриншотов для обозрения того что они намеренно хотят действовать против нас и собирают для этого людей(заговор)
![Screenshot_20210403-192149](https://user-images.githubusercontent.com/62647000/113481419-a7d1a500-94c3-11eb-8df5-0a8222d51a62.png)
![Screenshot_20210403-192253](https://user-images.githubusercontent.com/62647000/113481420-a86a3b80-94c3-11eb-9177-732fc6d68162.png)
![Screenshot_20210403-192402](https://user-images.githubusercontent.com/62647000/113481422-a86a3b80-94c3-11eb-90a5-b8a2754ae7bc.png)
![Screenshot_20210403-192534](https://user-images.githubusercontent.com/62647000/113481416-a607e180-94c3-11eb-9668-4037ebd5930c.png)

2021-04-03 14:31 UTC, Darkness6030 commented
Давайте я подробно отвечу на все обвинения:

1) Ни к каким бунтам и митингам мы не призываем, мы позиционируем себя, как мирный сервер. 

2) Администрация, нарушающая правила админов, была снята задолго до этого PR.

3) Я не умею устраивать Ddos, мы сами пострадали от нее пару дней назад. (И тут догадайтесь, кто ее устроил)

4) Наш старый хост, с которого мы переехали мы отдали пользователю @misaka0954. Никакого отношения к NSFW на том сайте мы не имеем.

5) Оформление Дискорд сервера типовое и никаким образом не слизано у вас. (За основу я брал оформление Дискорд сервера pandorum и petruCHIO)

6) Мы не призываем никого к использованию о7 и не распространяем его.

7) И напоследок. Вы запретили использовать нам бота, написанного не лично вами. Вы постоянно обвиняете нас в плагиате, хотя я постоянно работаю над сервером и пытаюсь сделать его лучше...

И напоследок...
Я стараюсь, как могу. Если вам не нравится сервер, это ваше ЛИЧНОЕ мнение. Я не хочу объявлять войну. Я хочу быть в мире и спокойствии и заниматься своим сервером... 
Прошу закрыть пулл реквест и прекратить срачи.

2021-04-03 14:36 UTC, Darkness6030 commented
Ни к каким активным действиям мы не предполагаем приступать и удалять ваш сервер не хотим. Нам не нужны проблемы.
И тот сервер создан просто как сборище людей, которым не нравится mindustry.ru

2021-04-03 14:39 UTC, T1murik commented
> На скриншоте я высказал мнения и оно полностью правдивое, вы просто слизали все у нас, включая https://github.com/MindustryRu/RUS-Core

По твоему предупреждению бот был удалён с сервера, аргумент отклоняется.
+ Аргументы
1) Бот был собран не администрацией нашего сервера, а КоТ2.0
2) КоТ2.0 заплатил разработчику бота за настройку этого бота
![IMG_20210403_173713](https://user-images.githubusercontent.com/73241663/113481670-75b04b00-94a3-11eb-883a-3f375c70e680.jpg)

2021-04-03 14:41 UTC, T1murik commented
> Еще немного скриншотов для обозрения того что они намеренно хотят действовать против нас и собирают для этого людей(заговор)

Ответ основателя mindustry.play на ваши очень некультурные действия против нас.

2021-04-03 14:45 UTC, RoomServers commented
> > Еще немного скриншотов для обозрения того что они намеренно хотят действовать против нас и собирают для этого людей(заговор)
> 
> Ответ основателя mindustry.play на ваши очень некультурные действия против нас.

А здесь уже интересно, миндастри.плей основал я, то бишь нексор

2021-04-03 14:51 UTC, Dark-Diamond commented
@Darkness6030 
Сейчас есть группа  по удалению .ру
В основном там нынешние участники/админы миндурки, так что как либо отказываться от этого глупо.
В свое время комьюнити в сторону .ру выдвинуло такую мысль по типу "если они косячили раньше, то значит могут накосячить и сейчас"
А это значит что по той же логике можно сказать и о миндурке. Нет гарантий что таких инцидентов, как с мандарином или ещё кем-то, не повториться.

2021-04-03 14:53 UTC, Darkness6030 commented
У вас старые админы, почти никого не убрали (а может быть и совсем не менялись)
В нашем же случае, мы убрали плохих админов.

2021-04-03 14:53 UTC, linups100 commented
Создатель сервера MinDurka и его админы не раз нарушали свои же правила. Вы можете хоть накидать вагон дизлайков, всё это было нарушения этого сервера
![2021-03-15_20-41-27](https://user-images.githubusercontent.com/81866919/113481944-16533a80-94a5-11eb-87da-060c90472807.png)
![2021-03-15_20-44-39](https://user-images.githubusercontent.com/81866919/113481945-17846780-94a5-11eb-9106-f7768e286936.png)
![2021-03-23_14-21-55](https://user-images.githubusercontent.com/81866919/113481946-181cfe00-94a5-11eb-9f41-8cd6a1db0c9c.png)
![Screenshot_20210314-222738_Discord](https://user-images.githubusercontent.com/81866919/113481947-18b59480-94a5-11eb-9e1c-63805047d6a2.jpg)
![Screenshot_20210326-001616_Discord](https://user-images.githubusercontent.com/81866919/113481948-18b59480-94a5-11eb-858e-b3fba526df20.jpg)
![Screenshot_20210314-222704_Discord](https://user-images.githubusercontent.com/81866919/113481951-19e6c180-94a5-11eb-9041-0078501a5311.jpg)
![2021-03-15_20-37-01](https://user-images.githubusercontent.com/81866919/113481952-1a7f5800-94a5-11eb-9fc7-723e9a78e626.png)
![2021-03-15_20-40-10](https://user-images.githubusercontent.com/81866919/113481953-1a7f5800-94a5-11eb-8768-a5614a246469.png)
![2021-03-15_20-42-13](https://user-images.githubusercontent.com/81866919/113481954-1b17ee80-94a5-11eb-8337-fb13a77e70f2.png)
![2021-03-26_18-28-12](https://user-images.githubusercontent.com/81866919/113481955-1bb08500-94a5-11eb-800b-c3461292c8d7.png)
![Screenshot_20210314-222720_Discord](https://user-images.githubusercontent.com/81866919/113481956-1c491b80-94a5-11eb-818d-1915188c12a3.jpg)
![Screenshot_20210314-222729_Discord](https://user-images.githubusercontent.com/81866919/113481957-1c491b80-94a5-11eb-83ae-fc7282f00f4b.jpg)
![Screenshot_20210403-172229_Discord](https://user-images.githubusercontent.com/81866919/113481959-1ce1b200-94a5-11eb-90a7-e2a23359cfe1.jpg)
![Screenshot_20210314-222937_Discord](https://user-images.githubusercontent.com/81866919/113481960-1d7a4880-94a5-11eb-9f04-419b413ba58c.jpg)

2021-04-03 14:55 UTC, Ademun-MD commented
> Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
> ![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)

С каких пор сообщение одного неадекваа, никоим образом не относящийся к нашему серверу, считается призывом администрации?

2021-04-03 14:56 UTC, linups100 commented
Так же, основатель сервера придумывал свои правила, чтобы защитить одного из админов, что видно на последнем скрине

2021-04-03 14:59 UTC, Dark-Diamond commented
> У вас старые админы, почти никого не убрали (а может быть и совсем не менялись)
> В нашем же случае, мы убрали плохих админов.

Мы сейчас не о ру говорим а о миндурке, не слезай с темы
А во-вторых за все косяки админы наказываются, а те кто до сих пор  админит у нас - заслужили свои места, хотя по-прежнему могут быть сняты за нарушения, а пока никаких нарушений от них не было

2021-04-03 15:00 UTC, Dark-Diamond commented
> > Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
> > ![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)
> 
> С каких пор сообщение одного неадеквата, никоим образом не относящийся к нашему серверу, считается призывом администрации?

Будь внимательнее, никто эти две вещи воедино не связывал

2021-04-03 15:00 UTC, Darkness6030 commented
Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.

2021-04-03 15:01 UTC, Fatonndev commented
Мастер, вот ты скажи, тебе делать нехрен? Тебе то какое дело до серверов. На свой посмотри, на то, что там творится, и тебе, да, тебе абсолютно похер на игроков. Берешь и используешь плагины которые тебе запрешщено использовать. Признаешь чужой код своим, и просто отмазываешься.  

Где твои милые глазки которые так светились когда ты хотел в глобал? Теперь от тебя только и виден негатив и игнорирование. Я видел скриншоты, которые скидывал мисака. Где прямо говорилось: мисака раб и он пишет все для нас (сформулировано по другому было но не суть)

И чтобы ты знал, вам до миндурки еще расти и расти...

2021-04-03 15:04 UTC, Ademun-MD commented
> > > Так же добавлю [сообщение](https://discord.com/channels/391020510269669376/464566756191502336/827591387364196392)
> > > ![image](https://user-images.githubusercontent.com/61590217/113481359-cf177a80-94a1-11eb-8665-1a5e748bbeba.png)
> > 
> > 
> > С каких пор сообщение одного неадеквата, никоим образом не относящийся к нашему серверу, считается призывом администрации?
> 
> Будь внимательнее, никто эти две вещи воедино не связывал

Как раз связывал, иначе зачем воздуху это предоставлять как обвинение?

2021-04-03 15:06 UTC, linups100 commented
> Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> 
> Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> Заметьте так же, что мат в #дурка разрешен

Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы

2021-04-03 15:06 UTC, Darkness6030 commented
Главная проблема нашего сервера - высокий пинг. Но она уже решается нашим техадмином.

Назовите хоть одну проблему с игровыми серверами и я ее починю/исправлю.

Но таких проблем крайне мало. И над всеми существующими ведётся работа. @Fatonndev выразил все, что не сказал я.

Приятной игры и хорошего настроения.
До связи

2021-04-03 15:07 UTC, Ademun-MD commented
> > Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> > Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> > Заметьте так же, что мат в #дурка разрешен
> 
> Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы

В таком случае зачем кидать сообщения из дурки?

2021-04-03 15:07 UTC, Darkness6030 commented
И да, идеального сервера не существует. (И тут я не говорю про петручио, он идеален)

2021-04-03 15:08 UTC, KotMilkMeoW commented
> > Для начала с собой разберитесь потом к другим лезьте. За вашими серверами не следит администрация, администрация вашего сервера гриферила на миндурке и осталась безнаказанна. Ваша администрация провоцировала игроков, администраторов миндурки своими действиями и словами. Фейк инфа и провокация со стороны основателя .ру и наебалово.
> > ![image](https://user-images.githubusercontent.com/73673886/113480757-33493700-94c0-11eb-8614-f0837fc72db6.png)
> > ![image](https://user-images.githubusercontent.com/73673886/113480773-49ef8e00-94c0-11eb-917c-7effde4f9795.png)
> > Так же мастер занимался чёрным пиаром и рассылкой спама игрокам миндустри в дс в личные сообщения.
> 
> На скриншоте я высказал мнения и оно полностью правдивое, вы просто слизали все у нас, включая https://github.com/MindustryRu/RUS-Core
> 
> Вы же в свою очередь оскорбляли меня клоуном и геем, и только тут не надо отмазываться.
> 
> Наша администрация у вас не гриферит это вы нагло лжете, наши сервера очень хорошо модерируются, о чем свидетельствует бан лист.

Так код core bot'а на гитхабе. Owler (разработчик) данного бота сделал для меня fork на гитхабе. => Я могу им пользоваться. Я ни разу не написал что написал бота целиком.

2021-04-03 15:09 UTC, RoomServers commented
> @Darkness6030
> Сейчас есть группа по удалению .ру
> В основном там нынешние участники/админы миндурки, так что как либо отказываться от этого глупо.
> В свое время комьюнити в сторону .ру выдвинуло такую мысль по типу "если они косячили раньше, то значит могут накосячить и сейчас"
> А это значит что по той же логике можно сказать и о миндурке. Нет гарантий что таких инцидентов, как с мандарином или ещё кем-то, не повториться.

Эта моя коалиция, кто там хочет быть, а кто не хочет, дело людей, я ответственный за эту группу, а не миндурка

2021-04-03 15:10 UTC, KotMilkMeoW commented
> Создатель сервера MinDurka и его админы не раз нарушали свои же правила. Вы можете хоть накидать вагон дизлайков, всё это было нарушения этого сервера
> ![2021-03-15_20-41-27](https://user-images.githubusercontent.com/81866919/113481944-16533a80-94a5-11eb-87da-060c90472807.png)
> ![2021-03-15_20-44-39](https://user-images.githubusercontent.com/81866919/113481945-17846780-94a5-11eb-9106-f7768e286936.png)
> ![2021-03-23_14-21-55](https://user-images.githubusercontent.com/81866919/113481946-181cfe00-94a5-11eb-9f41-8cd6a1db0c9c.png)
> ![Screenshot_20210314-222738_Discord](https://user-images.githubusercontent.com/81866919/113481947-18b59480-94a5-11eb-9e1c-63805047d6a2.jpg)
> ![Screenshot_20210326-001616_Discord](https://user-images.githubusercontent.com/81866919/113481948-18b59480-94a5-11eb-858e-b3fba526df20.jpg)
> ![Screenshot_20210314-222704_Discord](https://user-images.githubusercontent.com/81866919/113481951-19e6c180-94a5-11eb-9041-0078501a5311.jpg)
> ![2021-03-15_20-37-01](https://user-images.githubusercontent.com/81866919/113481952-1a7f5800-94a5-11eb-9fc7-723e9a78e626.png)
> ![2021-03-15_20-40-10](https://user-images.githubusercontent.com/81866919/113481953-1a7f5800-94a5-11eb-8768-a5614a246469.png)
> ![2021-03-15_20-42-13](https://user-images.githubusercontent.com/81866919/113481954-1b17ee80-94a5-11eb-8337-fb13a77e70f2.png)
> ![2021-03-26_18-28-12](https://user-images.githubusercontent.com/81866919/113481955-1bb08500-94a5-11eb-800b-c3461292c8d7.png)
> ![Screenshot_20210314-222720_Discord](https://user-images.githubusercontent.com/81866919/113481956-1c491b80-94a5-11eb-818d-1915188c12a3.jpg)
> ![Screenshot_20210314-222729_Discord](https://user-images.githubusercontent.com/81866919/113481957-1c491b80-94a5-11eb-83ae-fc7282f00f4b.jpg)
> ![Screenshot_20210403-172229_Discord](https://user-images.githubusercontent.com/81866919/113481959-1ce1b200-94a5-11eb-90a7-e2a23359cfe1.jpg)
> ![Screenshot_20210314-222937_Discord](https://user-images.githubusercontent.com/81866919/113481960-1d7a4880-94a5-11eb-9f04-419b413ba58c.jpg)

О. Я первый на скрине.

2021-04-03 15:12 UTC, linups100 commented
> > > Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> > > Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> > > Заметьте так же, что мат в #дурка разрешен
> > 
> > 
> > Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы
> 
> В таком случае зачем кидать сообщения из дурки?

Там прекрасно видно, что админы писали и в другие каналы, где мат запрещён

2021-04-03 15:12 UTC, XEN0PHIL commented
**Anuke's answer**: I'm not even going to scroll through it
**Ответ Анюка**: Даже не собираюсь листать этот PR
https://discord.com/channels/391020510269669376/663853133587546138/827921694614093854

2021-04-03 15:13 UTC, Ademun-MD commented
> > > > Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> > > > Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> > > > Заметьте так же, что мат в #дурка разрешен
> > > 
> > > 
> > > Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы
> > 
> > 
> > В таком случае зачем кидать сообщения из дурки?
> 
> Там прекрасно видно, что админы писали и в другие каналы, где мат запрещён

Я спросил конкретно про дурку

2021-04-03 15:14 UTC, Ademun-MD commented
> > > > > Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> > > > > Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> > > > > Заметьте так же, что мат в #дурка разрешен
> > > > 
> > > > 
> > > > Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы
> > > 
> > > 
> > > В таком случае зачем кидать сообщения из дурки?
> > 
> > 
> > Там прекрасно видно, что админы писали и в другие каналы, где мат запрещён
> 
> Я спросил конкретно про дурку

Так что не надо при помощи вбросов раздуватт из мухи слона

2021-04-03 15:15 UTC, USMP-Mandarin commented
> Мастер, вот ты скажи, тебе делать нехрен? Тебе то какое дело до серверов. На свой посмотри, на то, что там творится, и тебе, да, тебе абсолютно похер на игроков. Берешь и используешь плагины которые тебе запрещено использовать. Признаешь чужой код своим, и просто отмазываешься.
> 
> Где твои милые глазки которые так светились когда ты хотел в глобал? Теперь от тебя только и виден негатив и игнорирование. Я видел скриншоты, которые скидывал мисака. Где прямо говорилось: мисака раб и он пишет все для нас (сформулировано по другому было но не суть)
> 
> И чтобы ты знал, вам до миндурки еще расти и расти... (хотя вы скорее падаете)

Им не до расти до нас. Мы создали сервер для игроков, мастер же для получения выгоды. Олды с .ру(кем являюсь я) видели прекрасную вкладочку на их сайте с надписью ДОНАТ где можно было купить привилегию и на пвп превратится в трезубца. И я делаю акцент на **P2W**.

2021-04-03 15:17 UTC, linups100 commented
> > > > > > Никто из тех людей не админ. А я проматерился, когда сервер был почти полностью удален. Думаю, это уважительная причина.
> > > > > > Если они не забанены/не в мьюте, это значит лишь то, что мат не был замечен.
> > > > > > Заметьте так же, что мат в #дурка разрешен
> > > > > 
> > > > > 
> > > > > Никто из этих людей не в мьюте и не в бане, а это всё большая отмазка. Да в #дурке разрешён мат, но ваши админы писали мат и в других канал, и вам было всё равно, пока не пошли жалобы
> > > > 
> > > > 
> > > > В таком случае зачем кидать сообщения из дурки?
> > > 
> > > 
> > > Там прекрасно видно, что админы писали и в другие каналы, где мат запрещён
> > 
> > 
> > Я спросил конкретно про дурку
> 
> Так что не надо при помощи вбросов раздувать из мухи слона

Опять же, прекрасно видно что админы пишут не в #дурку, а именно в главный чат, да там попали некоторые сообщения из #дурка, но это нечего не отменяет

2021-04-03 15:19 UTC, KotMilkMeoW commented
> У вас старые админы, почти никого не убрали (а может быть и совсем не менялись)
> В нашем же случае, мы убрали плохих админов.

Даже меня. Хотя по правилам не было запрещено прописывать в консоль сервера rm -rf /* . Тем более с твоего разрешения…

2021-04-03 15:22 UTC, DemonicDeathbringer commented
смысл этих диалогов? анюк не будет это читать

2021-04-03 15:22 UTC, Ademun-MD commented
Спроси это у Мастера

2021-04-03 15:23 UTC, Darkness6030 commented
Анюк забил на пулл, дальнейшее обсуждение бессмысленно. Удачи и приятной игры.

2021-04-03 15:23 UTC, Ademun-MD commented
> Анюк забил на пулл, дальнейшее обсуждение бессмысленно. Удачи и приятной игры.

:/

2021-04-03 15:23 UTC, Dioo0 commented
why russian language there

2021-04-03 15:24 UTC, Koteyka-BY commented
> why russian language there

this is a russian server

2021-04-03 15:32 UTC, osp54 requested changes
There are a lot of lies.

2021-04-03 15:33 UTC, Dioo0 commented
> > Создатель сервера MinDurka и его админы не раз нарушали свои же правила. Вы можете хоть накидать вагон дизлайков, всё это было нарушения этого сервера
> > ![2021-03-15_20-41-27](https://user-images.githubusercontent.com/81866919/113481944-16533a80-94a5-11eb-87da-060c90472807.png)
> > ![2021-03-15_20-44-39](https://user-images.githubusercontent.com/81866919/113481945-17846780-94a5-11eb-9106-f7768e286936.png)
> > ![2021-03-23_14-21-55](https://user-images.githubusercontent.com/81866919/113481946-181cfe00-94a5-11eb-9f41-8cd6a1db0c9c.png)
> > ![Screenshot_20210314-222738_Discord](https://user-images.githubusercontent.com/81866919/113481947-18b59480-94a5-11eb-9e1c-63805047d6a2.jpg)
> > ![Screenshot_20210326-001616_Discord](https://user-images.githubusercontent.com/81866919/113481948-18b59480-94a5-11eb-858e-b3fba526df20.jpg)
> > ![Screenshot_20210314-222704_Discord](https://user-images.githubusercontent.com/81866919/113481951-19e6c180-94a5-11eb-9041-0078501a5311.jpg)
> > ![2021-03-15_20-37-01](https://user-images.githubusercontent.com/81866919/113481952-1a7f5800-94a5-11eb-9fc7-723e9a78e626.png)
> > ![2021-03-15_20-40-10](https://user-images.githubusercontent.com/81866919/113481953-1a7f5800-94a5-11eb-8768-a5614a246469.png)
> > ![2021-03-15_20-42-13](https://user-images.githubusercontent.com/81866919/113481954-1b17ee80-94a5-11eb-8337-fb13a77e70f2.png)
> > ![2021-03-26_18-28-12](https://user-images.githubusercontent.com/81866919/113481955-1bb08500-94a5-11eb-800b-c3461292c8d7.png)
> > ![Screenshot_20210314-222720_Discord](https://user-images.githubusercontent.com/81866919/113481956-1c491b80-94a5-11eb-818d-1915188c12a3.jpg)
> > ![Screenshot_20210314-222729_Discord](https://user-images.githubusercontent.com/81866919/113481957-1c491b80-94a5-11eb-83ae-fc7282f00f4b.jpg)
> > ![Screenshot_20210403-172229_Discord](https://user-images.githubusercontent.com/81866919/113481959-1ce1b200-94a5-11eb-90a7-e2a23359cfe1.jpg)
> > ![Screenshot_20210314-222937_Discord](https://user-images.githubusercontent.com/81866919/113481960-1d7a4880-94a5-11eb-9f04-419b413ba58c.jpg)
> 
> О. Я первый на скрине. 

у меня вопрос
какое дело до их дискорда? их дискорд ну и пусть сами разбираются

2021-04-03 22:24 UTC, BasedUser commented
> mindurka ddosses servers

that's false info, that's o7's doing

> mindurka incentivizes using the o7 client

again, false info

everything else looks on-point though

2021-04-06 15:46 UTC, Erisfiregamer1 commented
if i had to say anything about this:
can we eventually make a process of community vote for server removal? because at this point PR drama is just ridiculous.
i cant even block these fast enough before my email is flodded

2021-04-11 14:18 UTC, Dinistor commented
Интересно, почему только с серверами русскоязычного коммьюнити столько проблем :eyes: Хорошую идею предложил XEN0PHIL, по удалению и того и того, я же предлагаю _вообще все_ сервера русскоязычные убрать из глобала с такими приколами. Тут даже дело не в том, кто там в каком админ чате какого дискорда матерился. Мы говорим про сервер, а не про его изнанку - кому какое дело, как получают мясо для шашлыка, если итоговый продукт вкусный? Все сервера одинаковы в плане игры. Ты заходишь, и в 90% случаев видишь:

- схемы доставки ресурсов, не проверяющие предметы в ядре, то бишь банально вырывающие из рук игроков последние крохи ресурса. 

- схемы доставки, которые используют важных для экономики ботов - моно, поли, мег. Вспышки, зениты и горизонты в большинстве карт атаки (а тем более, выживания) как боевые единицы абсолютно бесполезны. В то время, как заставляя копать титан мег, а не квазаров, грифится отхил на стены, без поли строительство идёт годы, а без моно внезапно заканчивается медь или свинец.

- В целом, люди не обращают внимания на то, что происходит на производстве - нет никакой серьёзности в отношении к процессу, откровенный пофигизм, как будто вас заставили играть и поставили цель сделать, допустим, т4. Так же присутствует сильное влияние готовых схем - человек, ограбивший ядро схемой дистанционного т5, может, и не хотел ничего плохого, но откуда ж ему знать, что схема украла всех моно, а текущий уровень экономики не позволяет поточно клепать самых дорогих единиц в игре? Он поставил готовую схему, которая сама кушает ресурсы, и ждёт готовый результат, зачем ему _думать_?

Эти проблемы проистекают оттого, что во-первых чаще всего новичков отсылают в кампанию. В 5.0 кампания ещё более-менее готовила игрока к процессу (со своими оговорками), но сейчас, в 6.0, её пройти особых трудов не составляет, поверьте, я видел скрины, за которые на пандоруме можно было словить бан или кик за нубство, и люди утверждали, что "работает же, и смари, сектор защищает, и какое производство". Кампания 6.0 - плохой учитель. Нужны карты жёсткого выживания, по типу поля, и прочего, с рандомной генерацией руды, с изменёнными волнами - которые не выглядят как + 10 кинжалов каждые 100 волн, но это уже детали. Во-вторых, админсостав. Нет в админах того, что было раньше - желания помочь, участия в процессе. Возможно я копну слишком далеко, но во времена 3.5 на сервере индиелм, я часто видел, как одни игроки объясняли другим, как работает та или иная постройка, и сам сидел рядом и внимал. Вы назовёте меня идеалистом, но тогда царил настоящий коммунизм (иногда даже принималось коллективное решение о подрыве ядра реактором, как способ скипа скучной карты на 100 тыщ волн).  Правила и огромный онлайн превратили админов в банальных чекистов - лови и давай бан, нет времени на разборки. Это не интересно как для админа, для которого игра становится работой, ведь он один, а народу толпа, так и для игроков, которые даже иногда понять не могут, за что собсна бан, а без контроля экономика превращается в ужас. Вместо бана админ в идеале должен подойти, разъяснить и показать *возможный* вариант улучшения, и оставить игрока подумать. Конечно же при огромном онлайне и низком числе админов это невозможно - бан за гриф / реже за нубство. 
Можете считать это брюзжанием олдфага, которому раньше - лучше, но сейчас такие тёрки между серверами показывают, что вся эта разобщённость в составе тех, кто серверами занят, отрицательно влияет на тех, для кого изначально сервера и были - для игроков. В последнее время, кстати, онлайн упал, и я думаю именно из-за того, что людям надоедает так играть - заходишь приятно провести время, а в итоге получаешь головную боль из-за неконтролируемого хаоса, не позволяющего насладиться процессом игры. Возможно, будет глупо с моей стороны предлагать создать один большой сервер-хаб на русскоязычное сообщество, но я не вижу пока что иного выхода, ибо такие срачи будут продолжаться до тех пор, пока анюк действительно не искоренит все ру-сервера из листа, дабы срачей не было вообще.

> can we eventually make a process of community vote for server removal?
Не знаю, насколько это поможет, но будет весьма неплохо, если у простых игроков (у тех, кто даже не рарегистрирован в дискорде) будет возможность давать серверу оценку. Может, для этого добавить кнопку во вкладке об игре, там же, где есть ссылки на трелло, дискорд и тд.
[en] Idk if it would really help, but would be nice, if people, that even don't have Discord accounts (only game) can vote. Maybe add new button in 'about' tab.

2021-04-11 14:33 UTC, Dioo0 commented
по фактам.

2021-04-11 15:06 UTC, Ademun commented
> Интересно, почему только с серверами русскоязычного коммьюнити столько проблем 👀 Хорошую идею предложил XEN0PHIL, по удалению и того и того, я же предлагаю _вообще все_ сервера русскоязычные убрать из глобала с такими приколами. Тут даже дело не в том, кто там в каком админ чате какого дискорда матерился. Мы говорим про сервер, а не про его изнанку - кому какое дело, как получают мясо для шашлыка, если итоговый продукт вкусный? Все сервера одинаковы в плане игры. Ты заходишь, и в 90% случаев видишь:
> 
> * схемы доставки ресурсов, не проверяющие предметы в ядре, то бишь банально вырывающие из рук игроков последние крохи ресурса.
> * схемы доставки, которые используют важных для экономики ботов - моно, поли, мег. Вспышки, зениты и горизонты в большинстве карт атаки (а тем более, выживания) как боевые единицы абсолютно бесполезны. В то время, как заставляя копать титан мег, а не квазаров, грифится отхил на стены, без поли строительство идёт годы, а без моно внезапно заканчивается медь или свинец.
> * В целом, люди не обращают внимания на то, что происходит на производстве - нет никакой серьёзности в отношении к процессу, откровенный пофигизм, как будто вас заставили играть и поставили цель сделать, допустим, т4. Так же присутствует сильное влияние готовых схем - человек, ограбивший ядро схемой дистанционного т5, может, и не хотел ничего плохого, но откуда ж ему знать, что схема украла всех моно, а текущий уровень экономики не позволяет поточно клепать самых дорогих единиц в игре? Он поставил готовую схему, которая сама кушает ресурсы, и ждёт готовый результат, зачем ему _думать_?
> 
> Эти проблемы проистекают оттого, что во-первых чаще всего новичков отсылают в кампанию. В 5.0 кампания ещё более-менее готовила игрока к процессу (со своими оговорками), но сейчас, в 6.0, её пройти особых трудов не составляет, поверьте, я видел скрины, за которые на пандоруме можно было словить бан или кик за нубство, и люди утверждали, что "работает же, и смари, сектор защищает, и какое производство". Кампания 6.0 - плохой учитель. Нужны карты жёсткого выживания, по типу поля, и прочего, с рандомной генерацией руды, с изменёнными волнами - которые не выглядят как + 10 кинжалов каждые 100 волн, но это уже детали. Во-вторых, админсостав. Нет в админах того, что было раньше - желания помочь, участия в процессе. Возможно я копну слишком далеко, но во времена 3.5 на сервере индиелм, я часто видел, как одни игроки объясняли другим, как работает та или иная постройка, и сам сидел рядом и внимал. Вы назовёте меня идеалистом, но тогда царил настоящий коммунизм (иногда даже принималось коллективное решение о подрыве ядра реактором, как способ скипа скучной карты на 100 тыщ волн). Правила и огромный онлайн превратили админов в банальных чекистов - лови и давай бан, нет времени на разборки. Это не интересно как для админа, для которого игра становится работой, ведь он один, а народу толпа, так и для игроков, которые даже иногда понять не могут, за что собсна бан, а без контроля экономика превращается в ужас. Вместо бана админ в идеале должен подойти, разъяснить и показать _возможный_ вариант улучшения, и оставить игрока подумать. Конечно же при огромном онлайне и низком числе админов это невозможно - бан за гриф / реже за нубство.
> Можете считать это брюзжанием олдфага, которому раньше - лучше, но сейчас такие тёрки между серверами показывают, что вся эта разобщённость в составе тех, кто серверами занят, отрицательно влияет на тех, для кого изначально сервера и были - для игроков. В последнее время, кстати, онлайн упал, и я думаю именно из-за того, что людям надоедает так играть - заходишь приятно провести время, а в итоге получаешь головную боль из-за неконтролируемого хаоса, не позволяющего насладиться процессом игры. Возможно, будет глупо с моей стороны предлагать создать один большой сервер-хаб на русскоязычное сообщество, но я не вижу пока что иного выхода, ибо такие срачи будут продолжаться до тех пор, пока анюк действительно не искоренит все ру-сервера из листа, дабы срачей не было вообще.
> 
> > can we eventually make a process of community vote for server removal?
> 
> Не знаю, насколько это поможет, но будет весьма неплохо, если у простых игроков (у тех, кто даже не рарегистрирован в дискорде) будет возможность давать серверу оценку. Может, для этого добавить кнопку во вкладке об игре, там же, где есть ссылки на трелло, дискорд и тд.
> [en] Idk if it would really help, but would be nice, if people, that even don't have Discord accounts (only game) can vote. Maybe add new button in 'about' tab.

Тебе там это писать не надоело? .-.

2021-04-12 20:45 UTC, thedimas3007 commented
Согласен с мнением @Dinistor но на счет удаления всех ру серверов нет. Ибо есть нормальные сервера, такие как никочио, ранкед, обвилион, тот же мой сервер, которые живут себе спокойно и не вступают ни в какие конфликты

2021-04-13 13:38 UTC, bvcbvc commented
i dont speak much russian, but it seems mindurka is the return of the mindustry.ru

2021-04-14 15:54 UTC, Dinistor commented
> Тебе там это писать не надоело? .-.

Вся эта простыня по сложности написания не сравнится с бесконечным числом одинаковых игр в онлайне, где всё идёт по замкнутому циклу и не происходит ничего интересного для игроков, кроме постоянной фрустрации, их же действиями и создаваемой. Я просто вывалил мнение игрока, сравнив свой опыт игры в 3.5 на индиелме, в 5.0 в принципе и в 6.0 онлайне на разных его стадиях - когда ещё не использовали логику, и когда массово и без разбору начали тыкать схемы. (немаловажно уточнить, что я не трогал пвп, потому что не играл в групповое ни разу, а в 1 на 1 серьёзных матчей не было, кроме разве что двух с витлогом, остальные пару больше для смеха, нежели для установки скилла)

Просто создаётся ощущение, что онлайн атаки и выживания потерял планку уровня качества - красивые постройки, работающие как часы уступили место кривым и косым схемам на переключаемых процессорами разгрузчиках и юнитах, которые дают нестабильное (а иногда вовсе нерабочее) производство, поощряя лень игроков и желание полагаться на "авось проканает". Это показывает так же, что не только онлайн, но и сама игра не наказывает игрока за такую беспечность, что странно для экономической стратегии. Многие хорошие челлендж-карты могут покарать за банальный излишек термальных генераторов, ресурсы с которых могли пойти на улучшение производства/мощные башни, но зачастую в онлайне карты атаки/выживания вида "100 красивых прямоугольников с ресурсами под 20 воздушек размером, база противника не берется ничем, кроме банального клепания орды т5, а на сурве можно сидеть по 500+ волн спамя знамениями, запитанными от кинетики на ядре" не способствуют развитию понимания игры у новых игроков, и поощряют ленность тех, кому есть с чем сравнивать такую ситуацию (тех, кому приходилось _работать_, чтобы получть результат).

Алсо, было бы неплохо добавить тренировку по базовым логическим функциям в игру, уже быть может в 7.0, но это необходимо сделать. Люди _не понимают_, как изменить даже мелкие настройки  готовой схемы, а иногда это приводит к деструктивным последствиям (бинд поли на дистанционную кинетику это по сути гриф в большинстве случаев, ибо ни экономика не готова, ни юнитов на отстройку стен нет, а поменять настройки или добавить кнопку отключения никто обычно не догадывается).

2021-04-15 21:10 UTC, Volas171 reviewed
as a o7 member, i can confirm theres no o7 conspiracy about crashing the servers, server crashing is fully by nexity and mindurka *had* the tool only for testing vulnerabilities on their server (the developer of mindurka asked many times to nexity to ddos mindurka for testing) plus, o7 mod is deprecated, and don't come with that bullshit, easyplay.su (mindustry.ru) was the main user of the atomic o7 library wich contained sorter shuffle, massdriver shuffle and node disconnecter, and you may say (they changed) well no, they recently have used the mod to crash .pl and their current rival mindurka, how do I know this you say, o7 client has spyware and the developer (of the o7 client) 
leaks the results of it everyday on random discord servers.
 
![image](https://user-images.githubusercontent.com/60143910/114941919-60bfaa00-9e09-11eb-8fbb-21c1fbacf5ac.png)

2021-04-15 21:13 UTC, Volas171 commented
again , i remember everyone that easyplay.sus is mindustry.ru but rebranded so they vanished their past.

2021-04-16 11:26 UTC, Erisfiregamer1 commented
i had to delete a comment to say this
**69 comments pog**

2021-04-26 03:09 UTC, WilloIzCitron commented
oh no mindurka is .ru server?

2021-04-28 14:11 UTC, Volas171 commented
> oh no mindurka is .ru server?

no, lemme explain easily
mindurka is random new server
easyplay.sus is mindustry.ru but rebranded

2021-04-28 21:17 UTC, bvcbvc commented
@Anuken close this before my brain commits kernal panic

2021-07-20 15:00 UTC, closed without merging