they have a  n a m e
Anuken/Mindustry pull request #5074
Opened 2021-04-07 12:17 UTC by BasedUser

2021-04-07 12:23 UTC, Quezler commented on servers_v6.json
> +    "address": ["routerchain.ddns.net", "nikochio.ddns.net", "easyplay.su"]
```suggestion
    "address": ["routerchain.ddns.net", "nikochio.ddns.net", "easyplay.sus"]
```

2021-04-07 12:27 UTC, Anuken commented on servers_v6.json
> +    "address": ["routerchain.ddns.net", "nikochio.ddns.net", "easyplay.su"]
😳

2021-04-07 15:30 UTC, osp54 commented
Oh no

2021-04-07 15:30 UTC, osp54 commented
Oh no

2021-04-07 15:31 UTC, Erisfiregamer1 commented
oi no spam

2021-04-07 15:32 UTC, Erisfiregamer1 commented
@osp54 @Darkness6030 please explain the downvote? RU was already on the list, downvoting is saying that the current is IP is correct when it is no longer correct.

2021-04-07 16:06 UTC, Fatonndev commented
Нахер дурку... 
Кстати, мастер, тырить логотип, как и плагины тоже нехорошо

2021-04-07 16:48 UTC, Erisfiregamer1 commented
s h u t

2021-04-07 18:17 UTC, osp54 commented
> oi no spam

Bugs github, lol

2021-04-07 18:19 UTC, osp54 commented
> @osp54 @Darkness6030 @Fatonndev please explain the downvote? RU was already on the list, downvoting is saying that the current is IP is correct when it is no longer correct.

ru is cringe, we do not want to see them in the server list

2021-04-07 18:27 UTC, Darkness6030 commented
> Нахер дурку... 
> Кстати, мастер, тырить логотип, как и плагины тоже нехорошо

Кстати, этот логотип есть в интернете. В свободном доступе.
Тупо взяли и скачали картинку, молодцы

2021-04-07 18:40 UTC, osp54 commented
> > Нахер дурку... 
> > Кстати, мастер, тырить логотип, как и плагины тоже нехорошо
> 
> Кстати, этот логотип есть в интернете. В свободном доступе.
> Тупо взяли и скачали картинку, молодцы

И немного видоулучшили

2021-04-07 23:53 UTC, XEN0PHIL commented
роутер, а почему рот в изиплее

2021-04-08 07:16 UTC, USMP-Mandarin commented
чё за хуйня тут

2021-04-08 07:17 UTC, USMP-Mandarin commented
> > > Нахер дурку...
> > > Кстати, мастер, тырить логотип, как и плагины тоже нехорошо
> > 
> > 
> > Кстати, этот логотип есть в интернете. В свободном доступе.
> > Тупо взяли и скачали картинку, молодцы
> 
> И немного видоулучшили

в кавычках

2021-04-08 07:17 UTC, USMP-Mandarin commented
\
\
\



\
\
\
\
\
\
\
\
\
/
/
/
/
/
/
/

2021-04-08 07:17 UTC, USMP-Mandarin commented
.








































































































































.

2021-04-08 07:18 UTC, Quezler commented
@USMP-Mandarin cease the punctuation shitposts 🙄

2021-04-08 07:22 UTC, USMP-Mandarin commented
> @USMP-Mandarin cease the punctuation shitposts 🙄

nie

2021-04-08 07:25 UTC, Ademun commented
Bruh

2021-04-08 07:33 UTC, osp54 requested changes
No, please

2021-04-08 07:39 UTC, osp54 commented
and yes, I repeat

> Changing your domain will not change the opinion of the community about you.

2021-04-08 07:41 UTC, USMP-Mandarin commented
нахуй .ру

2021-04-08 11:45 UTC, Erisfiregamer1 commented
Let me grab an excerpt of what the cat said when he added the RU:
"If it bothers you, hide the server, that's an option now."
Begone and let the change go in peace.

2021-04-08 11:50 UTC, Erisfiregamer1 commented
the pull is #4697 if you are wondering

2021-04-08 11:55 UTC, RoomServers commented
У мастера рот в говне, переименуйся в MasterGayParty.suck

2021-04-08 13:55 UTC, Erisfiregamer1 commented
if I could censor stuff I would
leave the fucking pull alone

2021-04-08 14:25 UTC, osp54 commented
> if I could censor stuff I would
> leave the ****ing pull alone

Isn't it easier for you not to get into this pull and that's it? According to your "quotes"

2021-04-08 15:14 UTC, Erisfiregamer1 commented
the same goes for you. you are just mucking up a really bad cesspool already, so why don't YOU leave too?

2021-04-08 18:39 UTC, osp54 commented
> То же самое и с вами. вы просто уже вываливаете очень плохую выгребную яму, так почему бы и вам тоже не уйти?

A couple of insults at you would not hurt

2021-04-09 12:21 UTC, Erisfiregamer1 commented
@osp54 Whatever you think, stopping this pull will not remove this server. It will still be on the list.
so just let it pass so the server can be fixed.

2021-04-09 14:59 UTC, bvcbvc commented
yes

2021-04-09 20:01 UTC, BasedUser commented
are you fucking kidding me why is everything ru related getting downvoted to shit by my own community

2021-04-09 20:14 UTC, bvcbvc commented
> are you fucking kidding me why is everything ru related getting downvoted to shit by my own community

yes

2021-04-09 20:14 UTC, bvcbvc commented
a

2021-04-10 05:59 UTC, Darkness6030 requested changes
Oh no

2021-04-11 00:15 UTC, merged

2021-04-11 20:15 UTC, PolloUsami commented
reddit moment