Delete both EasyPlay and Mindurka due to conflicts
Anuken/Mindustry pull request #5104
Opened 2021-04-13 10:08 UTC by 4cr0-b47

**[RUS]**
Из-за конфликтов, которые происходят между Ру и Миндуркой. Я думаю, что единственный способ решить данную проблему - удалить оба сервера из глобального списка.

**[ENG]**
Due to the conflicts that occur between Ru and Mindurka. I think that the only way to solve this problem is to remove both servers from the global list.

2021-04-13 10:15 UTC, 4cr0-b47 commented
Недавний пулл об снятии: https://github.com/Anuken/Mindustry/pull/5052
Пулл, где прямо говорилось от администрации миндурки про ру: https://github.com/Anuken/Mindustry/pull/5074

2021-04-13 10:51 UTC, osp54 commented
В данном случае, вы начинаете этот конфликт заново, ведь этот конфликт закончился, и миндурка и ру не конфликтуют между собой. Ваш ПР также проигнорит Анюк, он не любит срачи, конфликты, как было с прошлым пуллом об удалении миндурки. Прошу угомонится.

2021-04-13 11:12 UTC, Darkness6030 commented
Конфликт решен, мы сохраняем нейтралитет. Не вижу смысла в удалении серверов, ведь куда тогда пойдут игроки? 
На RCR? 
Но это один из самых плохо настроенных серверов в игре...

2021-04-13 11:18 UTC, Dioo0 commented
u kinda late

2021-04-13 11:56 UTC, Erisfiregamer1 commented
EasyPlay has barely conflicted with MIndurka, and plus they have rewritten their originally toxic rules.
MIndurka should do the same. Still, I think that only Mindurka should be removed.

2021-04-13 12:16 UTC, Erisfiregamer1 reviewed
put the easyplay back

2021-04-13 12:25 UTC, osp54 commented
> EasyPlay has barely conflicted with MIndurka, and plus they have rewritten their originally toxic rules.
> MIndurka should do the same. Still, I think that only Mindurka should be removed.

1You are so smart with us, but did you know that the conflict started EasyPlay.co, you really, when you do not know anything, eat to agrude, and you know, judging the server by conflicts, is silly.

2021-04-13 12:25 UTC, osp54 commented
> EasyPlay has barely conflicted with MIndurka, and plus they have rewritten their originally toxic rules.
> MIndurka should do the same. Still, I think that only Mindurka should be removed.

And yes you are toxic

2021-04-13 13:10 UTC, Erisfiregamer1 commented
toxic, eh
let me list some things I know:
1. EasyPlay tried to remove Mindurks due to bad things happening there. Reputable community moments (baseduser, and 1 or 2 others) said the pull was OK. You keep defending MinDurka, choosing now to smear EasyPlay's rep. Not helping.
2. This pull was an attempt to stop the drama. I agree well that something must be done, but the community is a bit in disagreement over it. We should get a consensus first.
3. When have I been toxic? Show me an example.

2021-04-13 13:12 UTC, Erisfiregamer1 commented on servers_v6.json
> +    "address": ["routerchain.ddns.net", "nikochio.ddns.net"]
forget this.
if only MinDurka is removed, I feel worse will come.

2021-04-13 13:13 UTC, osp54 commented
> toxic, eh
> let me list some things I know:
> 
> 1. EasyPlay tried to remove Mindurks due to bad things happening there. Reputable community moments (baseduser, and 1 or 2 others) said the pull was OK. You keep defending MinDurka, choosing now to smear EasyPlay's rep. Not helping.
> 2. This pull was an attempt to stop the drama. I agree well that something must be done, but the community is a bit in disagreement over it. We should get a consensus first.
> 3. When have I been toxic? Show me an example.

It's sad to communicate with you, you scum which believes all fake information and spreads it.

2021-04-13 13:16 UTC, Erisfiregamer1 commented
I said show me an example (like from a pull), not just choosing to smear me worse.

2021-04-13 13:21 UTC, osp54 commented
> I said show me an example (like from a pull), not just choosing to smear me worse.
I shared my opinion about you, and I will not provide you with any evidence

2021-04-13 13:23 UTC, Erisfiregamer1 commented
without evidence you are just saying you don't like me very harshly. why not just say you do not like me and get over with?

2021-04-13 13:26 UTC, osp54 commented
I am ending my dialogue with you, because it is pointless to talk to you. Let the anuke decide what to do.

2021-04-13 13:28 UTC, osp54 requested changes
Bye Bye.

2021-04-13 13:32 UTC, summetdev commented
Вам ещё не надоели эти детские войны между серверами?

2021-04-13 16:19 UTC, MHeMoTexHuK commented
Calm, Anuke will ignore this pr
![IMG_20210413_191542](https://user-images.githubusercontent.com/69920617/114585915-cb97a680-9c8c-11eb-9030-6b9275092b98.jpg)

2021-04-13 20:38 UTC, Erisfiregamer1 commented
20 messages. this pull is getting T H I C C

2021-04-14 03:55 UTC, Dioo0 commented
damn, just close this dumb pr

2021-04-15 15:24 UTC, Volas171 approved these changes

2021-04-15 15:26 UTC, Volas171 approved these changes

2021-04-15 15:26 UTC, Volas171 commented
wait what

2021-04-15 15:28 UTC, Volas171 requested changes

2021-04-15 15:28 UTC, Volas171 commented on servers_v6.json
> -  },
leave mindurka, .ru just technically changed name to remove their own reputation ,

2021-04-15 22:17 UTC, Volas171 commented
**ignore above really dont know what happened**

2021-04-16 14:24 UTC, bvcbvc commented
this is dumb

2021-07-20 21:38 UTC, closed without merging