Update bundle_in_ID.properties
Anuken/Mindustry pull request #5247
Opened 2021-05-15 09:18 UTC by SAMBUYYA

Adding and change some words. Menambah dan mengubah beberapa kata.

2021-05-15 09:19 UTC, WilloIzCitron approved these changes
Nice Work

2021-05-15 09:43 UTC, DaGamerFiles requested changes
Acceptable, with some suggestions. Please review and fix.

2021-05-15 09:43 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +rules.unitcapvariable = Inti Mengaruhi Batas Unit
Inti Memengaruhi Batas Unit

2021-05-15 09:43 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +rules.deconstructrefundmultiplier = Penggandaan Penghancuran Bahan Kembali
Penggandaan Kembalinya Bahan Bangunan Dihancurkan

2021-05-15 09:43 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +research.multiplayer = Hanya host yang dapat meneliti Barang - barang.
barang-barang = bahan

2021-05-15 09:46 UTC, SAMBUYYA commented on core/assets/bundles/bundle_in_ID.properties
> +research.multiplayer = Hanya host yang dapat meneliti Barang - barang.
Tidak cocok kalau bahan, kan itu bangunan.

2021-05-15 09:47 UTC, SAMBUYYA commented on core/assets/bundles/bundle_in_ID.properties
> +rules.deconstructrefundmultiplier = Penggandaan Penghancuran Bahan Kembali
panjang amat

2021-05-15 09:48 UTC, SAMBUYYA commented on core/assets/bundles/bundle_in_ID.properties
> +rules.deconstructrefundmultiplier = Penggandaan Penghancuran Bahan Kembali
Saya tambahin yang

2021-05-15 09:58 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +research.multiplayer = Hanya host yang dapat meneliti Barang - barang.
Item yang dimaksud itu konteksnya dalam penelitian (Sumber Daya, Sektor, Bangunan).
Untuk alternatif bisa pakai barang (tanpa kata ulang).

2021-05-15 10:58 UTC, SAMBUYYA commented on core/assets/bundles/bundle_in_ID.properties
> +research.multiplayer = Hanya host yang dapat meneliti Barang - barang.
Sudah.

2021-05-15 10:59 UTC, DaGamerFiles approved these changes

2021-05-18 07:19 UTC, TheMrAlbert approved these changes

2021-05-18 13:04 UTC, merged