merge whitelisted, whitelist-add, and whitelist-remove
Anuken/Mindustry pull request #5517
Opened 2021-06-30 15:54 UTC by Susideur

2021-06-30 16:03 UTC, Quezler requested changes
the coding style is wrong, too much indentation and spaces around ifs among other things 👀

2021-06-30 16:17 UTC, genNAowl commented
Check https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md I guess?

2021-06-30 18:00 UTC, Susideur commented
chit nadly indentations 
I correct her

2021-06-30 18:03 UTC, Anuken commented
The indentation and formatting is still wildly incorrect, look at the surrounding code and the contribution guide linked above.

2021-06-30 18:12 UTC, Anuken requested changes

2021-06-30 18:12 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +        handler.register("whitelist", "[add/remove] [ID]", "Only members of the whitelist can connect to the server.", arg -> {
The description doesn't explain what the command does.

2021-06-30 18:12 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +            if (arg.length == 0) {
formatting still incorrect

2021-06-30 18:12 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +                        switch(arg[0]){
Un-enhanced switch statements with only two cases are too verbose, use ifs instead.

2021-06-30 18:12 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +                    Log.err("Invalid arguments");
Explain the actual issue, e.g. "Missing ID argument". Use a period.

2021-06-30 18:17 UTC, Susideur commented
it's good ?

2021-07-01 02:01 UTC, WilloIzCitron commented
hello, this pull is stale?

2021-07-01 02:19 UTC, Anuken commented
There are still several issues with this PR, so I decided it was faster to finish up the changes myself. See linked commit.

2021-07-01 02:19 UTC, closed without merging