update bundle_zh_CN.properties
Anuken/Mindustry pull request #5530
Opened 2021-07-03 10:14 UTC by SoMall-dumpling

Added Status Effects.
Added Navy Reinforce Units.
Some typo fixes like ‘build speed multiplier’ , ‘search’ and so on.
Phase fabric.

2021-07-04 07:17 UTC, liuxilu commented on core/assets/bundles/bundle_zh_CN.properties
> +sectors.threat = 难度
请从原文。该区块敌人“威胁”度也。

2021-07-04 07:22 UTC, liuxilu commented on core/assets/bundles/bundle_zh_CN.properties
> +threat.eradication = 极难
请从原文

2021-07-04 07:22 UTC, liuxilu commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.name = 龙王
意译 https://gist.github.com/liuxilu/0f903b79621041b3a357200b3fbeb45a#gistcomment-3798772

2021-07-04 11:32 UTC, SoMall-dumpling commented
“威胁”以及其它的改回去了。这个意译，是由于其他单位均为二字名称，故选用二字。况且anuke估计也是乱起名字的，不需按照原文翻译，按特点翻译即可。

2021-07-04 11:35 UTC, shugen002 commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.name = 龙王
> 意译 https://gist.github.com/liuxilu/0f903b79621041b3a357200b3fbeb45a#gistcomment-3798772

No

如果按照你这样得话，那就得吧前面得重置翻译一遍咯

2021-07-04 13:42 UTC, laohuaji233 commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.name = 龙王
就现在这个，好听一些

2021-07-13 00:43 UTC, shugen002 approved these changes

2021-07-20 03:04 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.name = 龙王
看上去欠妥

2021-07-20 06:17 UTC, SoMall-dumpling commented
1734 lines now.
Completely matches with bundle.properties.

2021-07-21 02:21 UTC, shugen002 approved these changes

2021-07-21 05:45 UTC, Mr-Ao-Dragon requested changes
***看看我写的新单位系列描述吧，秋梨膏***
unit.retusa.descripton = 攻击附近水面敌人。在水面布下水 雷，能被敌人触发，/n超时引爆。装载一个维修点。
unit.oxynoe.descripton = 攻击附近所有敌人。发射修复火焰 ，搭载一个裂解光束。                                    unit.cyerce.descripton = 攻击附近所有敌人。发射追踪开花 弹，可修复盟军建筑，搭载二个维修点。
unit.aegires.descripton = 攻击附近所有敌人。在自身范围内发射闪电攻击多个敌人，/n并修复受损的盟军单位与建筑。
unit.navanax.descripton = 攻击附近所有敌人。发射四束持续激光攻击敌人并点燃，/n同时发射能量弹攻击敌人并修复盟军建筑。

2021-07-21 05:46 UTC, Mr-Ao-Dragon commented
> ***看看我写的新单位系列描述吧，秋梨膏***
> unit.retusa.descripton = 攻击附近水面敌人。在水面布下水 雷，能被敌人触发，/n超时引爆。装载一个维修点。
> unit.oxynoe.descripton = 攻击附近所有敌人。发射修复火焰 ，搭载一个裂解光束。                                    unit.cyerce.descripton = 攻击附近所有敌人。发射追踪开花 弹，可修复盟军建筑，搭载二个维修点。
> unit.aegires.descripton = 攻击附近所有敌人。在自身范围内发射闪电攻击多个敌人，/n并修复受损的盟军单位与建筑。
> unit.navanax.descripton = 攻击附近所有敌人。发射四束持续激光攻击敌人并点燃，/n同时发射能量弹攻击敌人并修复盟军建筑。

发pr不知道为什么不能出现

2021-07-21 06:17 UTC, SoMall-dumpling commented
> _**看看我写的新单位系列描述吧，秋梨膏**_
> unit.retusa.descripton = 攻击附近水面敌人。在水面布下水 雷，能被敌人触发，/n超时引爆。装载一个维修点。
> unit.oxynoe.descripton = 攻击附近所有敌人。发射修复火焰 ，搭载一个裂解光束。 unit.cyerce.descripton = 攻击附近所有敌人。发射追踪开花 弹，可修复盟军建筑，搭载二个维修点。
> unit.aegires.descripton = 攻击附近所有敌人。在自身范围内发射闪电攻击多个敌人，/n并修复受损的盟军单位与建筑。
> unit.navanax.descripton = 攻击附近所有敌人。发射四束持续激光攻击敌人并点燃，/n同时发射能量弹攻击敌人并修复盟军建筑。

Anuken还没写描述呢，你先给他翻译好了可还行（

2021-07-21 06:27 UTC, liuxilu commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 易燃物
燃烧物更显“本质”，也对应爆炸物

2021-07-21 07:05 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 易燃物
pyr-为火的前缀，
-tite为矿物后缀。
故讨论得出“火石”这个翻译。

2021-07-21 09:00 UTC, liuxilu commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 易燃物
你们在哪讨论的啊；我的评论都outdated了，都resolve吧

2021-07-22 01:02 UTC, shugen002 commented
> _**看看我写的新单位系列描述吧，秋梨膏**_
> unit.retusa.descripton = 攻击附近水面敌人。在水面布下水 雷，能被敌人触发，/n超时引爆。装载一个维修点。
> unit.oxynoe.descripton = 攻击附近所有敌人。发射修复火焰 ，搭载一个裂解光束。 unit.cyerce.descripton = 攻击附近所有敌人。发射追踪开花 弹，可修复盟军建筑，搭载二个维修点。
> unit.aegires.descripton = 攻击附近所有敌人。在自身范围内发射闪电攻击多个敌人，/n并修复受损的盟军单位与建筑。
> unit.navanax.descripton = 攻击附近所有敌人。发射四束持续激光攻击敌人并点燃，/n同时发射能量弹攻击敌人并修复盟军建筑。

”装载一个维修点“和“搭载二个维修点”什么鬼？？？

2021-07-23 15:47 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.name = 龙王
不错，我也做了一个全篇review，但一直没想到好的海辅名字，这部分我先吸纳了

2021-07-23 19:20 UTC, Anuken commented
Should this be merged, over the other pull requests?

2021-07-24 03:08 UTC, xem8k5 commented
> Should this be merged, over the other pull requests?

Merge us.And close the others plz

2021-07-24 12:40 UTC, merged

2021-07-24 15:40 UTC, cigarmemr commented
Hopefully we will check the merged version in my repo. Especially the section Map Editor, Game Mode, Settings and Logic.
Yet many disagreements should be discussed.

2021-07-25 10:21 UTC, LawrenceLin2333 commented
这个 pyratite 硫改成火石是什么情况
虽然硫的英语也不是这个，但是硫看起来比火石更让人make sence吧。

2021-07-25 12:13 UTC, liuxilu commented
词根是火。火硫如何。

2021-07-25 13:26 UTC, cigarmemr commented
建议保持“硫”，或者统一改为“硫化物”。另外有个想法是把“硫（化物）”和“爆炸（混合）物”分别改为“火药”和“炸药”，简短一些，可直接适用于游戏任何位置，也能反映出他们的作用和差别。
另外，考虑下组个Discord频道集中讨论？

2021-07-25 13:35 UTC, liuxilu commented
火药 炸药+1

2021-07-25 13:37 UTC, liuxilu commented
即时聊天式不适合分条讨论

2021-07-25 13:41 UTC, liuxilu commented
要不就到我这开 issue thread
https://github.com/liuxilu/Mindustry.zh-CN

2021-07-25 16:43 UTC, cigarmemr commented
我是想找个能投票的平台，咱们针对一些“改也可以，不改似乎也行”的项目来投票决定。不然一个人改成一个样，但又都没有错误，搞得很混乱。

2021-07-26 02:24 UTC, shugen002 commented
> 我是想找个能投票的平台，咱们针对一些“改也可以，不改似乎也行”的项目来投票决定。不然一个人改成一个样，但又都没有错误，搞得很混乱。

翻了下之前的suggestion,有人提议过用crowdin，但crowdin是收费服务，anuke似乎不太想用，我觉得可以考虑弄弄 weblate https://github.com/nijel/weblate

2021-07-27 08:04 UTC, cigarmemr commented
先试试这个吧 [(https://discord.gg/G778pZFB)]

2021-07-27 08:07 UTC, cigarmemr commented
> 先试试这个吧 https://discord.gg/G778pZFB

@liuxilu @shugen002 @SoMall-dumpling @LawrenceLin2333 @Mr-Ao-Dragon