Update bundle_zh_CN.properties
Anuken/Mindustry pull request #5661
Opened 2021-07-28 16:31 UTC by cigarmemr

1 Synced most commits from the latest zh_CN bundle PR <https://github.com/Anuken/Mindustry/pull/5530>.
2 Synced the latest English bundle updating. i.e. the descriptions about derelicts, the settings.
3 Merged massive agreements between me and @liuxilu from the discarded PR.

2021-07-29 03:58 UTC, SoMall-dumpling reviewed
非常感谢。这下几乎完善了。
pyratite 和 blast-compound 是唯二问题。

2021-07-29 03:58 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
炸药...冲击反应堆里面怎么能丢炸药呢...
pyratite绝对不能叫火药。
这两者都是可以用来发电的，而这个翻译完全只考虑了攻击用途。
我认为火石很好，符合原文，且可以用作发电、弹药等。
爆炸混合物是完全按照原文blast-compound翻译，我认为无需改动。

2021-07-29 03:58 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.description = 发射爆炸性的电磁脉冲弹头, 对敌方电网造成显著破坏并修复友方建筑。具备4台自动激光发射塔,能熔化靠近的敌军。
敌军敌人最好统一。

2021-07-29 04:37 UTC, Hexrotor commented
lenum.configure→lenum.config

2021-07-29 05:16 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
据我所知，火石是由数种金属单质混合而成的固体合金，撞击、摩擦时产生的碎屑与氧气接触面增大，并具有较高温度，因而引起火花，点燃其他物质。火石本身并不可燃。正如在translation频道中描述的[那样](https://discord.com/channels/391020510269669376/395414970793459714/868507526914781185) 
不过根据qq群内讨论，也有可能是我对火石的含义认识不足。如果有对“火石”这个词在此处更恰当的解释，也请不吝赐教。
另外在群内我也发起了投票，希望在玩家范围内征求意见。参与人数虽不多，但支持“火药”“炸药”尚有一部分，而几乎没有人支持“火石”的翻译。
爆炸混合物的改动，我个人的支持理由如下：
1. （有前提）如果“火药”的翻译可以接受，那么“炸药”能体现两者的威力差别与合成路线上的层次高低。
2.  原翻译“爆炸混合物”存在一些问题：
    1. 较长，因而不得不在mixer处缩略为“爆炸物”，引入了“同一个概念在各处翻译不一致”的问题。
    2. 一部分玩家交流时为了简短将其缩略为“爆混”，但这又与mixer难以区分，导致歧义，增加交流成本。
    3. 若采取直译的策略，compound则应译为“化合物”而非“混合物”。
3. 就译后含义来说，“爆炸混合物”与“炸药”其实可以认为是同一个概念。但“炸药”较为简短，也利于统一所有出现此概念的文本。

2021-07-29 05:21 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.navanax.description = 发射爆炸性的电磁脉冲弹头, 对敌方电网造成显著破坏并修复友方建筑。具备4台自动激光发射塔,能熔化靠近的敌军。
感谢指出，已统一为“敌人”

2021-07-29 05:23 UTC, cigarmemr commented
> lenum.configure→lenum.config

Thanks for reviewing, fixed in latest commit.

2021-07-29 06:03 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
> 据我所知，火石是由数种金属单质混合而成的固体合金，撞击、摩擦时产生的碎屑与氧气接触面增大，并具有较高温度，因而引起火花，点燃其他物质。火石本身并不可燃。正如在translation频道中描述的[那样](https://discord.com/channels/391020510269669376/395414970793459714/868507526914781185)
> 不过根据qq群内讨论，也有可能是我对火石的含义认识不足。如果有对“火石”这个词在此处更恰当的解释，也请不吝赐教。
> 另外在群内我也发起了投票，希望在玩家范围内征求意见。参与人数虽不多，但支持“火药”“炸药”尚有一部分，而几乎没有人支持“火石”的翻译。
> 爆炸混合物的改动，我个人的支持理由如下：
> 
> 1. （有前提）如果“火药”的翻译可以接受，那么“炸药”能体现两者的威力差别与合成路线上的层次高低。
> 2. 原翻译“爆炸混合物”存在一些问题：
>    
>    1. 较长，因而不得不在mixer处缩略为“爆炸物”，引入了“同一个概念在各处翻译不一致”的问题。
>    2. 一部分玩家交流时为了简短将其缩略为“爆混”，但这又与mixer难以区分，导致歧义，增加交流成本。
>    3. 若采取直译的策略，compound则应译为“化合物”而非“混合物”。
> 3. 就译后含义来说，“爆炸混合物”与“炸药”其实可以认为是同一个概念。但“炸药”较为简短，也利于统一所有出现此概念的文本。

“火药”“炸药”实在和发电机没有关系。
如果改为“易燃物”和“爆炸物”如何？

2021-07-29 06:35 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
若是说与发电机的关系，可能“火石”比起“火药”会更远一些？反倒老版本译名“硫”可能还更适合。
“易燃物”我的看法是，它的外延稍大了一些。游戏中的煤、孢子荚、pyratite都可称之为易燃物，特指pyratite可能不合适。

2021-07-29 10:00 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
Pyratite叫赤炭怎么样，既有颜色特征(虽然另一个更红...)又有成分特征，，我从没听到过这个词，突然想出来的。
爆炸混合物就叫爆炸物怎么样，简单点。硬要说"炸药"与发电机的话，"炸药"确实会损坏低等发电机，而冲反的设定应该就是利用爆炸产生的冲击发电，所以叫"炸药"好像也问题不大。

2021-07-29 18:23 UTC, LawrenceLin2333 commented on core/assets/bundles/bundle_zh_CN.properties
> +status.overclock.name = 过载
electrifield 虽然也不是”麻痹“，但是这个electrifield的效果是造成移速和射速的降低，用“麻痹”比较顾名思义。

overclock 建议保持 ”超频“
”过载“ 有超出其承受能力的意思，偏负面，一般是用来形容可能会造成负面效果的情况，与其效果不符。

2021-07-30 00:13 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +schematic.importfile = 从文件导入蓝图
"导入蓝图文件"也许好一点

2021-07-30 00:29 UTC, Hexrotor requested changes

2021-07-30 00:29 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +editor.save.overwrite = 您的地图打算覆盖一张内置地图！在“地图信息”菜单里重新设置一个别的名称。
"您正试图覆盖一张内置地图"

2021-07-30 00:29 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +schematic.importfile = 从文件导入蓝图
"导入蓝图文件"也许好一点

2021-07-30 00:29 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +research.legacy = 发现了[accent]5.0[]版本的研究数据。\n您想要[accent]加载这些数据[]，还是[accent]（推荐）丢弃它们[]并在新战役中重新研究？
"丢弃它们（推荐）"

2021-07-30 00:29 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +mods.initfailed = [red]⚠[] mindustry的前一次启动失败了，可能是异常的模组导致的。\n\n为了防止连续崩溃，[red]所有模组都被禁用了。[]\n\n如果想关闭这个功能，可以在[accent]设置->游戏->游戏启动崩溃时禁用模组[]里关闭.
Mindustry记得大写

2021-07-30 00:58 UTC, SoMall-dumpling reviewed
有关unit description的一些小问题。

2021-07-30 00:58 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.eclipse.description = 向附近的敌人发射穿透性激光和分裂炮弹。
并非分裂炮弹。

2021-07-30 00:58 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
确实也是很奇怪的一点，在retusa和cyerce的英语description中，只提到了修复友方建筑，对搭载的维修点只字不提。
建议把这两个改为“并修复友方单位与建筑”；
oxynoe没有问题。
aegires原文为“shock”，游戏内看这个攻击方法为用电弧电击敌军，并非冲击波，所以建议改为“电击范围内的敌方建筑与单位”；
navanax“电磁爆弹”相比“爆炸性的电磁脉冲弹头”更为简洁美观。“具备”建议改为“搭载”，“激光发射塔”直接写作“激光炮台”更好。

2021-07-30 06:26 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +item.pyratite.name = 火药
感谢想法，关于pyratite，我也想过一些其他翻译，如松香、黄铁/黄铁矿。但从游戏中的表现来看，很难确定地说pyratite的成分就是什么（甚至怀疑只是pyrite的一个typo）。只能根据它的用途、颜色，大致选一个外延比较大的概念“火药”来表示它。接着考虑“火药”是否违和：作为燃料使用，确实**可以**（虽然并不**适合**）；作为弹头装填物，也确实只是**可以**。事实上从这两点来说，旧版本翻译“硫化物”可能还更加合适一些。
关于blast-compound，原翻译“爆炸物”和“炸药”基本可认为是同义词。当然“爆炸物”的外延稍大一些，除了“炸药”以外，也可以包括发生物理爆炸的事物。不过从游戏中的表现看，blast-compound应该更倾向于化学爆炸。

2021-07-30 06:42 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +status.overclock.name = 过载
按效果来看，electrified状态应该就是“EMP”，这也和T5海辅描述一致。我考虑“麻痹”的问题主要是，这个词一般是用在生物上的，可能不太适合机械性质的战斗单位？例如，通常我们会说“这个动物麻痹了”“这株植物受到昆虫分泌的激素影响，被麻痹了”，但不会说“这台机器麻痹了”“这架战机麻痹了”，请考虑下。

关于overclock我同意你的说法。我修改的出发点是，游戏中加速效果更多来自超速（穹顶）投影器，这里有了一个“超速”（boost）的概念。而来自单位提供的力场，我想尽量用一个与“超速”有明显区别的词，这样更明确地告诉玩家，这是两个不同的状态，让玩家看描述时哪怕一扫而过，也不容易搞混。如果这一点认同的话，也请帮我想想有没有正面一些的，更好的词\~

2021-07-30 06:43 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +editor.save.overwrite = 您的地图打算覆盖一张内置地图！在“地图信息”菜单里重新设置一个别的名称。
接受。原意是想让这里尽量”可爱“一些来缓和气氛 :)

2021-07-30 06:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +schematic.importfile = 从文件导入蓝图
这里我是想与其他地方的描述”从XX导入XX“保持一致

2021-07-30 06:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +research.legacy = 发现了[accent]5.0[]版本的研究数据。\n您想要[accent]加载这些数据[]，还是[accent]（推荐）丢弃它们[]并在新战役中重新研究？
接受

2021-07-30 06:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +mods.initfailed = [red]⚠[] mindustry的前一次启动失败了，可能是异常的模组导致的。\n\n为了防止连续崩溃，[red]所有模组都被禁用了。[]\n\n如果想关闭这个功能，可以在[accent]设置->游戏->游戏启动崩溃时禁用模组[]里关闭.
接受

2021-07-30 06:48 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.eclipse.description = 向附近的敌人发射穿透性激光和分裂炮弹。
接受

2021-07-30 06:50 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.eclipse.description = 向附近的敌人发射穿透性激光和分裂炮弹。
这些炮弹会引发blast状态，改为“爆炸性炮弹”如何？

2021-07-30 07:29 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
我也注意到，游戏中对各种物品、建筑、单位的描述，存在以下一些情况：
1. 描述与游戏内表现无关的/比游戏内容更多的，如lead的描述“Dense”（携带lead的单位并未因此而变慢，而且要说dense，thorium应该更甚于lead），blast-compound的描述“Used in bombs...”（哪怕单位携带blast-compound来kamikaze攻击，也不是将它像bomb一样扔下去）
2. 描述比游戏内容更少的，如一部分单位/建筑的描述，没有将单位所有的攻击方式与特殊能力全部列出来。
个人推测，这可能是作者在有意营造游戏氛围。具体说就是，作者为玩家展现了一个丰富的世界，而玩家实际能“玩”到的，只是这个世界中的一部分。这样可以让玩家保留对“描述中有，但现在还无法玩到”内容的期待，也让玩家在游戏中自己发现单位的这些额外功能时大呼“尤里卡”。

接受两条建议，感谢\~

2021-07-30 10:55 UTC, Hexrotor commented
对于"Pyratite"，刚刚查资料想到了一个名字。Pyrite中文别名叫硫精砂，游戏里mix可以理解为粗加工，那么叫"硫砂"如何？虽然和原翻译差别不大，但是可能比较接近"Pyratite"想表达的意思？

以下翻译是和群友交流想到的，不一定好，反正我觉得不太行……
硝石 赤炭 绯块 燃土 灼石 烙盐

2021-07-30 11:10 UTC, liuxilu commented
pyra- 火；-ite 衍生物。就这意思。无关pyrite，desert dessert

2021-07-31 00:09 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +status.overclock.name = 过载
个人觉得，电磁脉冲虽然是指一种现象，但是我们常常提起的时候都是说这种攻击手段。用在这里表示状态的话，总觉得有些奇怪？译为“电磁紊乱”如何？

2021-07-31 08:57 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +status.overclock.name = 过载
接受，这个词不错！

2021-07-31 09:01 UTC, cigarmemr commented
> pyra- 火；-ite 衍生物。也可能故意关联pyrite，毕竟是黄色。
> 反正要“火”！最好还兼容。“火硫”！

不错，“火硫”大概有两层意思：
- 这个物品可以燃烧
- 燃烧时产生火焰
另外“硫”也比较契合该物品的颜色，同时，将含有硫的物品制成”炸药“，也比较合理。这应该是目前收集的备选词中最合适的一个了，感谢！

2021-07-31 12:18 UTC, Hexrotor commented on core/assets/bundles/bundle_zh_CN.properties
> +status.overclock.name = 过载
关于overclock，其实我感觉一般不会有人把建筑和单位的性质搞混，应该无需担心这个问题。超频、超速这两个词我们都经常能见到，前者往往是指性能的提升，而不只是速度的提升。单位overclock这个状态即有速度提升也有伤害之类的提升，翻译成超频应该是很合适的，没啥问题。如果硬觉得会搞混，翻译成强化也不是不可以~

2021-08-01 14:11 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.aegires.description = 对进入范围的敌方建筑与单位释放电击，修复友方单位与建筑。
原文Shocks all enemy units and structures that enter its energy field. Repairs all allies.
energy field这里没有翻译出来。
Shock在这里是动词用法，建议直接“电击”作动词。
还有这前面是建筑与单位，后面怎么成单位与建筑了。
建议改为“电击进入能量场范围内的敌方单位与建筑，修复友方单位与建筑。”

2021-08-02 04:35 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +unit.aegires.description = 对进入范围的敌方建筑与单位释放电击，修复友方单位与建筑。
前半句的语序有意与其他单位保持一致，即“对/向 XXX 发射/释放/喷射 XXX”这样的顺序。这样如何：“产生能量场，对其中的敌方单位与建筑进行电击，对友方则进行维修。”

2021-08-03 04:38 UTC, SoMall-dumpling commented
T4海辅（aegires）翻译从“神盾”改为“玄武”如何？
神盾和海没啥关系，玄武是中国古代神话中的水神之首，与海有很大关系，而且玄武又名龟蛇，“龟”与T4海辅外形相似。

2021-08-03 11:26 UTC, cigarmemr commented
> T4海辅（aegires）翻译从“神盾”改为“玄武”如何？
> 神盾和海没啥关系，玄武是中国古代神话中的水神之首，与海有很大关系，而且玄武又名龟蛇，“龟”与T4海辅外形相似。

感觉不错，之前的“神盾”估计是从舰艇名字想出来的

2021-08-14 11:11 UTC, Hexrotor commented
还是overclock的问题
正如之前那位老哥说的，“过载”几乎算个负面词汇了，并不符合游戏想表达的原意。
“超频”和“超速”都算常见词汇吧，尽管在游戏中“boost“的意义和”超频“很相似，但是以中文来说，”超频“和”超速“并不一样

> 超頻（英語：overclocking）是把電子配件的時脈速度提升至高於廠方所定的速度運作，從而提升性能的方法。——摘自维基百科

在游戏中，单位的overclock不仅是移动速度的提升，也有其他的，总之就是性能提升了。单位是机甲，用”超频“来描述这种状态并没有什么问题（其实这种状态往往叫强化）。
而超速的意义可以很广泛，但生活中一般认为是物理移动速度快，所以不存在”容易与超频搞混“这类问题。况且玩家需要点开图标才能看见名称，而名称下方就标明了各种参数，很难让人单纯以为是”速度提升“的效果，所以我认为不用担心。

翻译为”超频“或”强化“我认为都是可以的，且”sapped“翻译为”弱化“，刚好可以与“强化”对应。但有一个问题，目前只有“overclock”一种正向状态，万一以后出了其他的正向状态，“强化”有可能就不适用于此了，所以还请多加考虑一下。
总之请不要翻译为”过载“。

另外再提一下，如果pyratite真就翻译为“火硫”的话。。感觉还不如就叫硫
回顾一下你说的：
> 这个物品可以燃烧

很明显，如果翻译为"硫"，大多数人都知道"硫"易燃
> 燃烧时产生火焰

大多数时候，燃烧会产生火焰，如果一个人知道"硫"能燃烧，那么他大概能猜到"pyratite"会产生火焰。"火硫"明示了这点，这倒也不坏，但也不是必须的。

以上

2021-08-14 15:38 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-conduit.description = 跨越任意地形或建筑物输送液体。比导管桥范围更大，但需要电力。
挑个刺，见谅。
都用传输吧。
（1477和1478“输出”无需改动）

2021-08-14 17:33 UTC, cigarmemr commented
> 还是overclock的问题
> 正如之前那位老哥说的，“过载”几乎算个负面词汇了，并不符合游戏想表达的原意。
> “超频”和“超速”都算常见词汇吧，尽管在游戏中“boost“的意义和”超频“很相似，但是以中文来说，”超频“和”超速“并不一样
> 
> > 超頻（英語：overclocking）是把電子配件的時脈速度提升至高於廠方所定的速度運作，從而提升性能的方法。——摘自维基百科
> 
> 在游戏中，单位的overclock不仅是移动速度的提升，也有其他的，总之就是性能提升了。单位是机甲，用”超频“来描述这种状态并没有什么问题（其实这种状态往往叫强化）。
> 而超速的意义可以很广泛，但生活中一般认为是物理移动速度快，所以不存在”容易与超频搞混“这类问题。况且玩家需要点开图标才能看见名称，而名称下方就标明了各种参数，很难让人单纯以为是”速度提升“的效果，所以我认为不用担心。
> 
> 翻译为”超频“或”强化“我认为都是可以的，且”sapped“翻译为”弱化“，刚好可以与“强化”对应。但有一个问题，目前只有“overclock”一种正向状态，万一以后出了其他的正向状态，“强化”有可能就不适用于此了，所以还请多加考虑一下。
> 总之请不要翻译为”过载“。
> 
> 另外再提一下，如果pyratite真就翻译为“火硫”的话。。感觉还不如就叫硫
> 回顾一下你说的：
> 
> > 这个物品可以燃烧
> 
> 很明显，如果翻译为"硫"，大多数人都知道"硫"易燃
> 
> > 燃烧时产生火焰
> 
> 大多数时候，燃烧会产生火焰，如果一个人知道"硫"能燃烧，那么他大概能猜到"pyratite"会产生火焰。"火硫"明示了这点，这倒也不坏，但也不是必须的。
> 
> 以上

“超频”与“超速”并不是含义容易搞混，而是采用区别更大的两个词，有助于在玩家一扫而过时也能马上意识到这是两个不同的东西，不需要完整看完两个字才能区分。换句话说，用”超频“和”超速“，含义上是没错，但一定会有玩家在刚接触这两个文本时将其误认为同一个东西。并不是他们不理解超频和超速的含义，而是他们压根就没仔细看。如果能设法增大两个文本的字面上的差别，将能够给玩家更多的容错空间。
我对”过载“的意愿也不强烈，期待有更好的建议。我此时想到的一个方案是”超频“和”加速“，你看如何？比如咱们来玩一下：
超频超频超频超频超频超频超频超速超频超频超频超频超频
超频超频超频超频超频超频超频超频超频超频加速超频超频
相比“超速”，“加速”更容易找到对吧 :)

关于“火硫”的翻译，其实我也没有意愿。非要带上“火”这个字，完全是出于迁就当前版本的，以及在qq群讨论中有人坚持的“火石”。但从个人角度来说，我一直认为pyratite是pyrite的一个笔误，因为无论从外观还是用途，游戏中的pyratite都与黄铁矿pyrite更接近。说是“硫”尚可，但与中文中已有的“火石”概念则搭不上边。因此实在没有必要将pyratite拆成pyr-和-atite，然后逐字翻译。对于这一条该如何取舍，目前收集到的意见是：
1. 保持老版本的“硫”，并统一为“硫化物”
2. （由 @liuxilu 推荐）更新为“火硫”
3. （个人不推荐）保持当前版本的“火石”
4. （个人推荐）更新为“火药”并同步blast-compound为“炸药”

2021-08-14 17:40 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-conduit.description = 跨越任意地形或建筑物输送液体。比导管桥范围更大，但需要电力。
接受建议\~
统一同一个概念在不同地方的用语，也是汉化/翻译中的基础。全篇review时改动了很多细节，等做到1400+行已经疲惫了，难免遗漏。非常感谢能有人帮忙“挑刺”\~

2021-08-14 23:22 UTC, Hexrotor commented
> “超频”与“超速”并不是含义容易搞混，而是采用区别更大的两个词，有助于在玩家一扫而过时也能马上意识到这是两个不同的东西，不需要完整看完两个字才能区分。换句话说，用”超频“和”超速“，含义上是没错，但一定会有玩家在刚接触这两个文本时将其误认为同一个东西。并不是他们不理解超频和超速的含义，而是他们压根就没仔细看。如果能设法增大两个文本的字面上的差别，将能够给玩家更多的容错空间。

有道理，我觉得boost译为加速很好，也可以解决你说的问题，我赞成这个改动。
关于pyratite, 我只是感觉相比"硫", 加上"火"有点多此一举，但我也想不到更多的的翻译了。物品名称的改动算是比较重要的，如果实在找不到好的替代，还是建议保持原样。(当然，如果有好的翻译那更好

2021-08-14 23:45 UTC, Hexrotor commented
想了一下，"加速"似乎会有一个问题：如果显示为 `加速 250%` 是否会容易让人认为是速度额外增加了250%，而不是变为原来的250%? 请考虑一下。

2021-08-15 05:51 UTC, SoMall-dumpling commented
> 想了一下，"加速"似乎会有一个问题：如果显示为 `加速: 250%` 是否会容易让人认为是速度额外增加了250%，而不是变为原来的250%?
> 在投影仪描述中，原文为"speed increase: 250%"，译为"提速250%"并没有什么问题。这里感觉原文就有一点歧义，再加上"加速"，感觉歧义似乎更大了？请考虑一下。
> 另外如果要改动，投影仪的名称是否有必要改动？

某种程度上来讲，那个冒号取消了歧义，使250%成为一个独立的个体，与“加速”一词间没有关系。
但是显然，如果不看冒号，歧义就体现出来了。目前也没有好的解决方法。
原文妙在speed increase是一个名词，冒号后解释了它的加速程度是250%
但是中文中有没有只有名词含义而没有动词含义的词来表示加速呢？我想不出来，能想到的只有翻译为“加速程度”或是“加速倍率”了。

2021-08-15 05:53 UTC, CPXMC commented
那个“游戏启动崩溃时不禁用模组”是不是该修复一下）

2021-08-15 05:54 UTC, CPXMC commented
> 那个“游戏启动崩溃时不禁用模组”是不是该修复一下）

正确的翻译应该是“游戏启动崩溃时禁用模组”

2021-08-15 05:59 UTC, SoMall-dumpling commented
> > 那个“游戏启动崩溃时不禁用模组”是不是该修复一下）
> 
> 正确的翻译应该是“游戏启动崩溃时禁用模组”

已经改过了。

2021-08-15 06:00 UTC, CPXMC commented
行



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 15, 2021 13:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Anuken/Mindustry] Update bundle_zh_CN.properties (#5661)




   
那个“游戏启动崩溃时不禁用模组”是不是该修复一下）
  
正确的翻译应该是“游戏启动崩溃时禁用模组”
  
已经改过了。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-15 06:46 UTC, Hexrotor commented
> 某种程度上来讲，那个冒号取消了歧义，使250%成为一个独立的个体，与“加速”一词间没有关系。
> 但是显然，如果不看冒号，歧义就体现出来了。目前也没有好的解决方法。
> 原文妙在speed increase是一个名词，冒号后解释了它的加速程度是250%
> 但是中文中有没有只有名词含义而没有动词含义的词来表示加速呢？我想不出来，能想到的只有翻译为“加速程度”或是“加速倍率”了。

看起来似乎是这样，那么如果译为"变速"呢？
`变速: 250%` 如何，虽然和"boost"直译差别有点大了

2021-08-16 14:31 UTC, cigarmemr commented
> > 某种程度上来讲，那个冒号取消了歧义，使250%成为一个独立的个体，与“加速”一词间没有关系。
> > 但是显然，如果不看冒号，歧义就体现出来了。目前也没有好的解决方法。
> > 原文妙在speed increase是一个名词，冒号后解释了它的加速程度是250%
> > 但是中文中有没有只有名词含义而没有动词含义的词来表示加速呢？我想不出来，能想到的只有翻译为“加速程度”或是“加速倍率”了。
> 
> 看起来似乎是这样，那么如果译为"变速"呢？
> `变速: 250%` 如何，虽然和"boost"直译差别有点大了。
> Edit: 这个其实也是不太准确的，它不仅能表示速度增加，也能表示减小，这不符合原意。比如电力不够用的时候，可能变成`变速: 80%`，实际上速度当然不会变成80%。如果不考虑与"boost"直译差别太大，"加速程度"也不是不行，除了四个字确实有点长以外
> Edit2: "加速倍率"也许也存在上述问题，此外倍率和百分比好像不能一概而论吧，"加速百分比"……那更长了

我试着收集了overclock这个条目在游戏UI里的截图，目前找到的包括这些：
![image](https://user-images.githubusercontent.com/26317456/129579248-4ab8f998-a83b-40bf-8865-5b6a87276009.png)
![image](https://user-images.githubusercontent.com/26317456/129579276-fc456946-4c9f-448e-a1fd-5a3e4dc9c7e6.png)
下面这是单位受到overclock光环影响时，状态栏里显示的。后面跟着的是它的粘滞时间（单位离开光环范围后，效果仍然存在的时间），同时也是产生这个光环的单位，即T2海军，刷新光环的cd：
![image](https://user-images.githubusercontent.com/26317456/129579452-89f9a8c8-2279-49df-80f2-69c2c2a87c59.png)
在T2海军描述中，只有图标，而没有overclock条目：
![image](https://user-images.githubusercontent.com/26317456/129580102-c426a256-68e9-4562-bb02-523e3c3949d7.png)

似乎没有后面跟加速倍率的场景？如果是我遗漏了，还请帮忙补充下。

2021-08-16 14:35 UTC, cigarmemr commented
> > 想了一下，"加速"似乎会有一个问题：如果显示为 `加速: 250%` 是否会容易让人认为是速度额外增加了250%，而不是变为原来的250%?
> > 在投影仪描述中，原文为"speed increase: 250%"，译为"提速250%"并没有什么问题。这里感觉原文就有一点歧义，再加上"加速"，感觉歧义似乎更大了？请考虑一下。
> > 另外如果要改动，投影仪的名称是否有必要改动？
> 
> 某种程度上来讲，那个冒号取消了歧义，使250%成为一个独立的个体，与“加速”一词间没有关系。
> 但是显然，如果不看冒号，歧义就体现出来了。目前也没有好的解决方法。
> 原文妙在speed increase是一个名词，冒号后解释了它的加速程度是250%
> 但是中文中有没有只有名词含义而没有动词含义的词来表示加速呢？我想不出来，能想到的只有翻译为“加速程度”或是“加速倍率”了。

这个加速数值的描述，似乎原文的increase就是错误的。游戏中写出来的数值包括投影器的150%，加相位物后的投影器225%，穹顶投影器250%，实际变化*后*的数值就是这么多，而非*“增加了”*这么多（按增加来算，则应该是50%、125%与150%）。因此这个地方，“boost”条目翻译成“变速”似乎比较符合。

2021-08-17 08:19 UTC, cigarmemr commented
> > 似乎没有后面跟加速倍率的场景？如果是我遗漏了，还请帮忙补充下。
> 
> 实际上这条讨论的是投影仪的boost而不是overclock😂
> 你之前提出如果将overclock翻译为超频，可能需要改一下boost的翻译。如果将boost翻译为变速的话，我也提出了一些短板，也许你们可以在你们群里讨论下这个

或者保持现有的boost为“超速”不变，而将overlock翻译为“增幅”怎么样？

2021-08-17 14:17 UTC, Hexrotor commented
> 或者保持现有的boost为“超速”不变，而将overlock翻译为“增幅”怎么样？

啊这，如果翻译成这个，一眼看过去完全意义不明吧……？

2021-08-17 15:23 UTC, SoMall-dumpling commented
> > > 似乎没有后面跟加速倍率的场景？如果是我遗漏了，还请帮忙补充下。
> > 
> > 
> > 实际上这条讨论的是投影仪的boost而不是overclock😂
> > 你之前提出如果将overclock翻译为超频，可能需要改一下boost的翻译。如果将boost翻译为变速的话，我也提出了一些短板，也许你们可以在你们群里讨论下这个
> 
> 或者保持现有的boost为“超速”不变，而将overlock翻译为“增幅”怎么样？

像我这种GemCraft深度中毒人士对于“增幅”一词的第一反应是amplification，属实和overclock关系不大。
我觉得没必要改。

2021-08-18 06:23 UTC, SoMall-dumpling commented
![已锁定](https://user-images.githubusercontent.com/57857764/129848061-e4dafe7f-2ded-485d-8ff4-f675716e9ba9.PNG)
要不把“已”字删了。
locked应该是被动而不是过去式。
“锁定”即可。

2021-08-18 07:36 UTC, Hexrotor commented
> ![已锁定](https://user-images.githubusercontent.com/57857764/129848061-e4dafe7f-2ded-485d-8ff4-f675716e9ba9.PNG)
> 要不把“已”字删了。
> locked应该是被动而不是过去式。
> “锁定”即可。

我认为不能改，意思本来就不影响，而且就算改了，"锁定"又能体现出来是被动吗？有些翻译真的不能太死板。
顺便说一下，昨天我在某平台上看到有人吐槽现在的翻译像机翻😂

2021-08-18 08:09 UTC, SoMall-dumpling commented
> 我认为不能改，意思本来就不影响，而且就算改了，"锁定"又能体现出来是被动吗？有些翻译真的不能太死板。
> 顺便说一下，昨天我在某平台上看到有人吐槽现在的翻译像机翻😂

理解，（而且我说错了应该是完成时），那么就不改了。
机翻吗，在哪里说的我要康康（
这个pr应该会好多了，不再像机翻了。

2021-08-18 08:27 UTC, Hexrotor commented
> 机翻吗，在哪里说的我要康康（
> 这个pr应该会好多了，不再像机翻了。

好游快爆，貌似他主要吐槽的是火石(
![2021-08-18 16 26 09](https://user-images.githubusercontent.com/45112661/129864688-2d137ccc-b383-41d6-9c9d-4dbec338aeea.jpg)

2021-08-19 00:11 UTC, CPXMC commented
建议把方块熔炉改成方块锻造炉
感觉"熔炉"和这个方块的功能有点相违背

2021-08-19 01:52 UTC, SoMall-dumpling commented
> 建议把方块熔炉改成方块锻造炉
> 感觉"熔炉"和这个方块的功能有点相违背

这一条已经改为了“方块建造厂”。
应该和“方块锻造炉”差距不大，不需要进一步改了。

2021-08-19 09:36 UTC, cigarmemr commented
> > 机翻吗，在哪里说的我要康康（
> > 这个pr应该会好多了，不再像机翻了。
> 
> 好游快爆，貌似他主要吐槽的是火石(
> ![2021-08-18 16 26 09](https://user-images.githubusercontent.com/45112661/129864688-2d137ccc-b383-41d6-9c9d-4dbec338aeea.jpg)

“火石”确实比较出戏，我觉得原来的“硫”其实也没什么必要改，不然就恢复成“硫”怎么样？
说机翻的话，单个词应该看不出来，可能是指大段的描述部分吧，尤其是区域描述，还有新手hint这些文字。这部分我也做了些微调，应该要好些了，各位不妨也帮我校对一下（622行和1339行附近）

2021-08-19 10:21 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.boost = 按住[accent][[L-Shift][]控制当前单位飞越障碍物。\n\n但只有少数地面单位有助推器.
句号。

2021-08-19 10:22 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.boost = 按住[accent][[L-Shift][]控制当前单位飞越障碍物。\n\n但只有少数地面单位有助推器.
句号

2021-08-19 10:22 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.presetLaunch = 灰色的[accent]降落地区块[]，如[accent]冰冻森林[]，可以从任何区域发射，不需要占领附近的区块。\n\n[accent]数字编号的区域[]，比如这个，则可以[accent]选择性[]占领。
降落地区块？
降落区块就行了吧，launch sector。

2021-08-19 10:23 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +item.spore-pod.details = 孢子。可能是人工合成的生命形式,释放对其他生物有毒的气体,极具侵略性。在某些条件下高度易燃。
逗号

2021-08-19 10:24 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +block.copper-wall.description = 保护己方建筑，挡下敌方炮弹。
block.liquid-void.description = 蒸发输入的所有液体，仅限沙盒。
block.payload-source.description = 无限输出载荷，仅限沙盒。
block.payload-void.description = 摧毁输入的任何载荷，仅限沙盒。
block.copper-wall.description = 保护己方建筑，挡下敌方炮弹。
只是提醒一下，我写好了，复制进去吧

2021-08-19 10:25 UTC, SoMall-dumpling reviewed
刚提到的，我看了下。

2021-08-19 23:52 UTC, Hexrotor commented
请恢复成"硫"吧，目前看来大多数人都支持保持"硫"。另外，请把以百分比形式显示数据的地方，改成xx百分比

2021-08-20 01:57 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
>  stat.buildspeedmultiplier = 建造速度倍率
上面Hex提到的

2021-08-20 07:36 UTC, woodjecket commented
请恢复硫吧，我在各大qq群均发表了投票，结果很明显，完全对火石极其不满意
![Uploading 821154DC-9F19-40AC-B444-FB07523C2C4B.jpeg…]()

2021-08-20 07:38 UTC, woodjecket commented
> 请恢复硫吧，我在各大qq群均发表了投票，结果很明显，完全对火石极其不满意

![IMG_1146](https://user-images.githubusercontent.com/62745850/130197846-f46778e0-2d6d-46d4-a464-4cbe7e621509.JPG)

2021-08-22 06:41 UTC, liuxilu commented
"overclock"倍频。“倍频：250%”，即2.5“倍”。
"locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。
“方块建造厂”如果是说"block constructor"，那应该是“构造”，就是还没“建”到地上，只是“构”出来了。
"multiplier"是“乘数”，即效果是这个值乘以原值，百分比是闹哪样。

2021-08-22 08:05 UTC, SoMall-dumpling commented
> "overclock"倍频。“倍频：250%”，即2.5“倍”。
> "locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。
> “方块建造厂”如果是说"block constructor"，那应该是“构造”，就是还没“建”到地上，只是“构”出来了。
> "multiplier"是“乘数”，即效果是这个值乘以原值，百分比是闹哪样。

康康我的#5809，你觉得可以这样改吗？

2021-08-22 11:50 UTC, Hexrotor commented
> "locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。

好吧，我还想请教一个问题。如果是unlocked，怎么翻译？

2021-08-22 12:52 UTC, SoMall-dumpling commented
> > "locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。
> 
> 好吧，我还想请教一个问题。如果是unlocked，怎么翻译？

那么按照他的，就是之前是“未”解锁，现在解锁了，所以翻译成“已解锁”。

2021-08-24 00:01 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.boost = 按住[accent][[L-Shift][]控制当前单位飞越障碍物。\n\n但只有少数地面单位有助推器.
多谢

2021-08-24 00:03 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.presetLaunch = 灰色的[accent]降落地区块[]，如[accent]冰冻森林[]，可以从任何区域发射，不需要占领附近的区块。\n\n[accent]数字编号的区域[]，比如这个，则可以[accent]选择性[]占领。
好的，多谢

2021-08-24 00:03 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +item.spore-pod.details = 孢子。可能是人工合成的生命形式,释放对其他生物有毒的气体,极具侵略性。在某些条件下高度易燃。
ok

2021-08-24 00:16 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.copper-wall.description = 保护己方建筑，挡下敌方炮弹。
ok，已添加

2021-08-24 00:20 UTC, cigarmemr commented
> 请恢复硫吧，我在各大qq群均发表了投票，结果很明显，完全对火石极其不满意

接受建议，我打算统一为“硫化物”，你看如何？更早的版本中，“硫化物”应该比“硫”更普遍一些，而且也比较符合混合器的功能。

2021-08-24 00:21 UTC, cigarmemr commented
> > > "locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。
> > 
> > 
> > 好吧，我还想请教一个问题。如果是unlocked，怎么翻译？
> 
> 那么按照他的，就是之前是“未”解锁，现在解锁了，所以翻译成“已解锁”。
> 这么说来，“locked”可以翻译为“未解锁”，我觉得不错。

这两条，locked用“锁定”，unlocked用“已解锁”如何？

2021-08-24 00:24 UTC, cigarmemr commented
> > "overclock"倍频。“倍频：250%”，即2.5“倍”。
> > "locked"不是被动也不是完成，而是“现在的状态”，该用“锁定”；“已”锁定，难道之前“未”锁定吗？不，一开始就是锁定的。
> > “方块建造厂”如果是说"block constructor"，那应该是“构造”，就是还没“建”到地上，只是“构”出来了。
> > "multiplier"是“乘数”，即效果是这个值乘以原值，百分比是闹哪样。
> 
> 麻烦看一下我的#5809，你觉得可以这样改吗？

似乎不错，boost那边消除歧义了，overlock目前还没看到后面有跟百分比的场景。这两条可能还需综合考虑。
“倍率”还是“百分比”那边，我觉得没有必要改，请再斟酌。

2021-08-24 02:02 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.presetLaunch = 灰色的[accent]降落地区块[]，如[accent]冰冻森林[]，可以从任何区域发射，不需要占领附近的区块。\n\n[accent]数字编号的区域[]，比如这个，则可以[accent]选择性[]占领。
稍等，这个位置原文写的是 landing zone sectors，似乎是想将有名有姓的区块和数字区块进行区分。这个landing zone应该怎么体现比较好？

2021-08-24 02:04 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +hint.presetLaunch = 灰色的[accent]降落地区块[]，如[accent]冰冻森林[]，可以从任何区域发射，不需要占领附近的区块。\n\n[accent]数字编号的区域[]，比如这个，则可以[accent]选择性[]占领。
我先改为“着陆区块”，期待进一步讨论。

2021-08-24 02:25 UTC, cigarmemr commented
此版本的“相织物”（旧版本译为“相位物”）似乎有个问题是，“相”是一个多音字，“相织”容易和“相知”“相识”搞混，或者说，第一次看到“相织物”，更容易把“相”理解成“相互”而不是正确的“相位”。完整译出“相位”则不会有歧义。
但旧版本“相位物”又少了fabric的意思。
这里改为“相位织物”怎么样？如此的话，phase weaver也可以译为“相位编织器”。
期待大家的意见。

2021-09-05 00:52 UTC, cigarmemr commented
Inherited by <https://github.com/Anuken/Mindustry/pull/5938>

2021-09-05 00:52 UTC, closed without merging