Add unitSpawnEvent
Anuken/Mindustry pull request #5876
Opened 2021-08-27 10:59 UTC by Darkness6030

Mindustry doesn't have an event which is triggered when a unit is spawned by wave. 
So i've added it

2021-08-27 23:49 UTC, buthed010203 commented on core/src/mindustry/game/EventType.java
> +    /**Called when a unit is spawned by wave. */
You forgot a space after /**

2021-08-27 23:50 UTC, buthed010203 requested changes

2021-08-27 23:50 UTC, buthed010203 commented on core/src/mindustry/game/EventType.java
> +        public UnitSpawnEvent(Unit unit) {
No space before {

2021-08-27 23:52 UTC, MEEPofFaith commented on core/src/mindustry/game/SpawnGroup.java
> +import arc.Events;
```suggestion
import arc.*;
```

Use wildcard imports.

2021-08-27 23:53 UTC, MEEPofFaith commented
Also where PR template checkboxes?

2021-08-27 23:53 UTC, buthed010203 commented
Also how does this differ from unitCreateEvent or whatever its called?

2021-08-28 13:29 UTC, Darkness6030 commented
@buthed010203, UnitCreateEvent is called when unit is created by a factory
UnitSpawnEvent is called when a unit is spawned by spawnPos

2021-08-28 14:53 UTC, merged