[RU] Translation of all latest bundles
Anuken/Mindustry pull request #5985
Opened 2021-09-13 09:19 UTC by Darkness6030

If you think i translated incorrectly, dm me: Даркнесс#3729

2021-09-13 09:28 UTC, Darkness6030 commented
Btw can i have @Translator role 👀

2021-09-14 04:55 UTC, summetdev requested changes

2021-09-14 04:55 UTC, summetdev commented on core/assets/bundles/bundle_ru.properties
> +stat.unitsCreated = Юнитов создано:[accent] {0}
Англицизм, везде "unit" переведено как "единица".

2021-09-14 04:55 UTC, summetdev commented on core/assets/bundles/bundle_ru.properties
> +editor.cliffs = Стены на Скалы
Почему "скалы" с заглавной буквы? Это нарицательное. Также перевод желательно помещать на ту строку, где был источник, чтобы было легче найти.

2021-09-14 04:55 UTC, summetdev commented on core/assets/bundles/bundle_ru.properties
> +hint.presetDifficulty = У этого сектора [scarlet]высокая сложность[].\nЗапуск на такие сектора [accent]не рекомендуется[] без достаточных технологий и подготовки.
В оригинале не "сложность", а "threat level", что можно лучше перевести как "уровень угрозы". Опять не совпадают строки перевода и источника.

2021-09-14 05:13 UTC, Darkness6030 commented
Done

2021-09-14 16:43 UTC, Darkness6030 commented
@Anuken all is fixed.
Can you merge it?

2021-09-14 16:52 UTC, merged