Better Mod/Plugin dependencies handling
Anuken/Mindustry pull request #6328
Opened 2021-11-11 23:05 UTC by Phinner

Currently, all plugins are loaded, instanciated and then sorted, this leads to `ClassNotFound` exceptions if you dare to use static Classes of other Plugins outside the `init` or if you try to create a general purpose `Plugin` classes like a `AbstractGamemodePlugin` for example that may be optimized for gamemode plugins.

The solution is simple, resolving dependencies before loading anything, it features:
- more complex dependencie trees
- detecting missing dependencies
- preventing circular dependencies

The code is tested and it works fine, It's just that the structure of `Mods` is a bit hard to follow so I need your opinion on how the missing/circular dependencies should be handled and what to do with the `dependencies` and `missingDependencies` fields of `LoadedMod`.

Thanks for reading.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2021-11-13 04:10 UTC, sk7725 commented
try the new loading structure with other mods, especially mods with UI / java mods with static references all over the place / asset-heavy java or js mods that rely on asset loading (and related events) order.
Mods like Sharustry, BetaMindy, and NH should be tested.

(for one, I know BM is heavily dependant on the order of ClientLoad, static init, mod init(), mod loadContent(), and the first Trigger.update, etc. for most of the music / sound filter / UI overlay handling, and they won't get caught by Anuke's BM check because the run is headless)

2021-11-13 09:32 UTC, Phinner commented
> try the new loading structure with other mods, especially mods with UI / java mods with static references all over the place / asset-heavy java or js mods that rely on asset loading (and related events) order.
> Mods like Sharustry, BetaMindy, and NH should be tested.
> 
> (for one, I know BM is heavily dependant on the order of ClientLoad, static init, mod init(), mod loadContent(), and the first Trigger.update, etc. for most of the music / sound filter / UI overlay handling, and they won't get caught by Anuke's BM check because the run is headless)

I tried with fakes mods to see if it orders correctly and others that I already have such as `ui-lib` or `BrainDustry`. I will try the one you mentioned later, thanks for pointing it out.

2021-11-13 11:00 UTC, sk7725 commented
(try BM's latest action, the release is far too outdated)

2021-11-14 13:43 UTC, Phinner commented
@sk7725 , I achieved crash-less-dustry :^)

![image](https://user-images.githubusercontent.com/62483793/141683563-c354aa4b-b459-414a-b998-412a0d785399.png)

2021-11-14 14:47 UTC, Phinner commented
@Anuken Ready for review

2021-11-19 21:43 UTC, Phinner commented
;-; No review ? ;-;

2021-11-20 00:06 UTC, Anuken commented
I'm fairly busy with the v7 branch at the moment.

2021-11-20 12:47 UTC, Phinner commented
ok

2021-11-25 16:23 UTC, Anuken requested changes

2021-11-25 16:23 UTC, Anuken commented on core/src/mindustry/mod/Mods.java
> +        ObjectMap<String, Fi> fileMapping = new ObjectMap<>(files.size);
Do not add the `files.size` argument to map/set constructors; `ObjectMap` capacity is significantly more complex and you're just making it slower here.

2021-11-25 16:23 UTC, Anuken commented on core/src/mindustry/mod/Mods.java
> +            ModMeta meta = findMeta(zip);
findMeta can throw an exception due to malformed JSON. You should try/catch here and continue if it throws.

2021-12-01 01:36 UTC, Anuken commented
Looks good, will test the changes with some mods later.

2021-12-01 01:37 UTC, Anuken approved these changes

2021-12-01 01:37 UTC, Anuken commented
![image](https://user-images.githubusercontent.com/10100000/144155892-32a8fba7-da9d-40ac-bc9b-b51e0da75a8d.png)

*why is this a button*

2022-01-11 04:43 UTC, merged