Customizable gameOver listener and more
Anuken/Mindustry pull request #6505
Opened 2022-01-19 08:49 UTC by Darkness6030

Why i did this?
Because i want a custom gameOver listener in my plugin. There are no ways to remove default one. But now you can change it to anything.

Why making public so many variables?
Because i am **very** tired of using Reflect.
Note that i made public only useful variables like nextMapOverride.

Also i moved 2 final variabled to Vars.java. Now you can use it anywhere.

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-01-19 09:07 UTC, LeoSko commented
Another thought: events map from Events from arc also should be public, or provide less restricted interface of removing listeners.

2022-01-27 18:55 UTC, Anuken requested changes

2022-01-27 18:55 UTC, Anuken commented on core/src/mindustry/Vars.java
> +    public static final int roundExtraTime = 12;
What is the point of placing either of these variables here? They're still static final, and they have nothing to do with "shared" variables. Either make them `Config` numbers, or don't move them.

2022-01-27 18:55 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +    public Task lastTask;
Implementation detail, confusing and should not be public. What is a "last task"? What does it refer to? Can it be null? What would canceling it do? When does accessing it change anything at all? None of these are clear from the variable alone.

2022-01-27 18:55 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +    public @Nullable Map nextMapOverride;
Should be private and set with a setter to support future changes.

2022-01-27 18:55 UTC, Anuken commented on server/src/mindustry/server/ServerControl.java
> +    public Gamemode lastMode;
Should use a different name and/or documented getter to let users know what this really stores.

2022-03-03 02:20 UTC, way-zer commented
I do this to disable default gameover logic
![Snipaste_2022-03-03_10-19-25](https://user-images.githubusercontent.com/15688938/156483685-dc4450fb-6419-43bb-ad10-8f75b55b46a6.png)
https://github.com/way-zer/ScriptAgent4MindustryExt/blob/4fb49cc79b53c5915da205a43e36c19b88166f9f/scripts/wayzer/maps.kts#L86

2022-10-04 20:02 UTC, closed without merging