in_ID v7 translation
Anuken/Mindustry pull request #6758
Opened 2022-05-07 01:48 UTC by WilloIzCitron

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-05-07 03:53 UTC, DaGamerFiles requested changes
🗿

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.crystal-cluster.name = Gugus Kristal
Bongkahan Kristal

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.vibrant-crystal-cluster.name = Gugus Kristal yang Bersinar
Bongkahan Kristal yang Bersinar

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.yellowcoral.name = Koral Kuning
Karang Kuning; Terumbu Kuning

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +liquid.cyanogen.name = Cianogen
Sianogen

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +content.team.name = Faksi
Fraksi

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.arkycite-floor.name = Lantai Arkycit
Lantai Arkisit

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.arkyic-stone.name = Batu Arkyic
Batu Arkyik

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.arkyic-vent.name = Ventilasi Arkyic
Ventilasi Arkyik

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.arkyic-wall.name = Dinding Arkyic
Dinding Arkyik

2022-05-07 03:53 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +objective.coreitem = [accent]Pindak ke Inti:\n[][lightgray]{0}[]/{1}\n{2}[lightgray]{3}
Pindahkan ke Inti

2022-05-08 05:22 UTC, DaGamerFiles requested changes
Capitalization on line 406, 866, 1089, 1102

2022-05-08 05:24 UTC, WilloIzCitron commented
done ez commit

2022-05-08 05:26 UTC, DaGamerFiles requested changes

2022-05-08 05:26 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
>  block.plasma-bore.name = Plasma Bore
Bor Plasma

2022-05-08 05:26 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.large-plasma-bore.name = Plasma Bore Besar
Bor Plasma Besar

2022-05-08 05:26 UTC, DaGamerFiles commented on core/assets/bundles/bundle_in_ID.properties
> +block.basic-assembler-module.name = Modul Assembler Dasar
Modul Perakit Dasar

2022-05-08 05:27 UTC, DaGamerFiles commented
too bad another changes to do lol

2022-05-08 05:29 UTC, WilloIzCitron commented
~~shift button on my keyboard succ~~

2022-05-08 05:33 UTC, DaGamerFiles approved these changes

2022-05-10 23:01 UTC, Anuken commented
Merged.

2022-05-10 23:01 UTC, closed without merging