Translation zh_cn partly
Anuken/Mindustry pull request #6759
Opened 2022-05-07 03:10 UTC by xem8k5

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-05-08 03:59 UTC, Cry0flu1d reviewed
but there is still some strange stuffs

2022-05-08 03:59 UTC, Cry0flu1d commented on core/assets/bundles/bundle_zh_CN.properties
> +block.carbide-wall.name = 钨钢墙
"carbide"  should be something like 碳化物" or “碳纤维”

2022-05-08 04:32 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.carbide-wall.name = 钨钢墙
碳化钨钢？

2022-05-08 05:15 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +updatedesc = 覆盖标题和描述
“重写标题和描述”

2022-05-08 05:16 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +waves.spawn.none = [scarlet]在地图上并没有找到生成点。
“地图上没有生成点”
还有，建议把句号删了，原来就没有句号

2022-05-08 05:17 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +toolmode.underliquid = 水下绘制
“液体下绘制”？
不一定是水?

2022-05-08 05:18 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +objective.nuclearlaunch = [accent]⚠ 检测到在途核发射: [lightgray]{0}
“检测到在途的核聚变打击”
高大上一点）

2022-05-08 05:20 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +announce.nuclearstrike = [red]⚠ 检测到在途核打击入境 ⚠
怎么又“在途”……

2022-05-08 05:21 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.abandon = 放弃投降
歧义。
要么放弃，要么投降。个人认为“放弃”更好。

2022-05-08 05:24 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +bullet.range = [stat]{0}[lightgray] 地面范围
改为“格射程“？

2022-05-08 05:25 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.mouseposition.name = 显示鼠标位置
“显示鼠标坐标”
“位置”有歧义。

2022-05-08 05:25 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.hidedisplays.name = 禁止逻辑绘制
隐藏！
hide不是禁止

2022-05-08 05:27 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +rules.rtsminattackweight = 最小袭击轻重
“最小攻击承重”？
这个词好像没有官方的翻译。搜也搜不到。不过“轻重”肯定是不对的。
这东西影响的是敌方单位同时参与攻击的数目。

2022-05-08 05:28 UTC, SoMall-dumpling requested changes
以上是一些建议。

2022-05-08 05:42 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.abandon = 放弃投降
已经改了，上文就是放弃，遵循放弃

2022-05-08 05:42 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.mouseposition.name = 显示鼠标位置
ok

2022-05-08 05:48 UTC, xem8k5 commented
> 以上是一些建议。

以上内容全部更正完毕。

2022-05-08 09:00 UTC, squi2rel commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.hidedisplays.name = 禁止逻辑绘制
翻译成禁止更直观

2022-05-08 12:54 UTC, woodjecket commented
建议
1974 generator 发电机
reinforced和duct翻译应统一
1385 流体路由器
1984 不应再为编织器
2009 prime怎么能直接T5呢？
1583 熔合意义不明，是否应该是融合或熔成
308 310删去多余空行
1126

2022-05-08 13:17 UTC, xem8k5 commented
> 建议 1974 generator 发电机 reinforced和duct翻译应统一 1385 流体路由器 1984 不应再为编织器 2009 prime怎么能直接T5呢？ 1583 熔合意义不明，是否应该是融合或熔成 308 310删去多余空行 1126

好，再让我看看

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +lst.flushmessage = 在屏幕上显示来自文本存储器的消息。\n将等待上一条消息完成。
「根据文本缓存中的内容，在屏幕上显示一条信息。\n上一条信息结束后才会执行。」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +lacess.speed = 单位的最高速度，单位为地块/秒 .
两个「单位」好像重复了。这样如何：「单位的最高速度（格/秒）。」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +graphicstype.col = 相当于颜色，但包装齐全。\n包装颜色以十六进制代码的形式写入，带有[accent]%??????[]前缀。\例如：[accent]%ff0000[]将是红色的。
「整合后的色彩信息。\n以[accent]%[]开头的十六进制代码形式。\n例如：[accent]%ff0000[]代表红色。」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +lenum.unbind = 完全禁用逻辑控制.\n恢复标准的AI。
建议中文句号
另外第二句「恢复标准」似乎容易被误判成一个词组。去掉「的」改为「恢复标准AI」怎么样？

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.redweed.name = 红草
我想到一个「赤藻」，不知如何

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.pur-bush.name = 普尔布什
pur也许是「纯粹」的意思？这里我想到一个「粹木」，不知如何

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.arkyic-boulder.name = 方解岩巨岩
如果arky确实是「方解（石）」的话，这里应该可以写成「方解巨岩」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.red-stone-boulder.name = 红巨石
「巨石」和「巨岩」最好能统一

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.graphitic-wall.name = 石墨矿墙
这里应该不用「矿」吧，「石墨墙」怎么样

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.silicon-arc-furnace.name = 硅弧炉
“葫芦”哈哈。「电弧硅炉」应该不错

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.surge-crucible.name = 浪涌坩埚
按照v6里翻译的讨论，surge最好统一成「合金」，如果这里也和巨浪合金有关的话

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-synthesizer.name = 相位编制器
若是为了和塞普罗星的作明显区别的话，这里建议也用「合成器」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.regen-projector.name = 再生投影仪
这里可以与塞普罗的建筑保持一致用「投影器」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.overflow-duct.name = 溢流管道门
应该是「管道溢流门」吧~

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.duct-unloader.name = 管道卸载器
「卸载器」倒是更符合原意，不过我推荐和塞普罗保持一致「装卸器」

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.unit-cargo-unload-point.name = 单位物流卸载点
这两个感觉可以统一一下。另外这个unit-cargo是不是有什么更好的说法，待定。

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.reinforced-liquid-tank.name = 强化流体储存罐
比较纠结的是现在多出了气体，但游戏里似乎又将他们都归类为liquid？也许是压缩为液体的氢、氧之类的吧。要是为了统一可以考虑下到底用「液体」还是「流体」
另外「强化液体」好像容易被误判成一个词组。「加强型液体交叉器」如何？

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.pyrolysis-generator.name = 热解制造厂
generator应该是发电厂的意思吧

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.core-citadel.name = 壁垒核心
这两个我建议换成区分度比较大的名字。参考《帝国时代》，分别叫「营垒核心」和「城堡核心」怎么样？

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.reinforced-vault.name = 强化仓库
同上，这些reinforced感觉用「加强型」不错

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.world-processor.name = 世界处理器
这里我觉得用「地图处理器」会好些，待讨论

2022-05-08 13:44 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.refabricator.name = 单位升级加工厂
似乎长了些。就叫「单位升级厂」怎么样？下同

2022-05-08 13:53 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +item.carbide.name = 碳化钨
因为原料是铍和钨，所以这样翻译了。

2022-05-08 14:02 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.carbide-crucible.name = 碳化钨坩埚
直译确实叫碳化物，但是游戏中却是以石墨和钨矿合成的，究竟是钨钢？碳化钨？碳化物？

2022-05-08 14:03 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +liquid.gallium.name = 镓液
这个可以有

2022-05-08 15:58 UTC, 24kYXH commented
> #6759

2022-05-08 22:10 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.refabricator.name = 单位升级加工厂
> 似乎长了些。就叫「单位升级厂」怎么样？下同

1.全部统一成：禁止从核心外丢物品
2.全部统一成：单位升级厂

2022-05-08 22:15 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.core-citadel.name = 壁垒核心
文中如壁垒 卫城都是带有防守、抵御的意思的，用城堡似乎不可取

2022-05-08 22:17 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.core-citadel.name = 壁垒核心
碉堡核心？

2022-05-08 22:19 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.pyrolysis-generator.name = 热解制造厂
早已更改完毕，请使用最新文档检查

2022-05-08 22:33 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +objective.enemiesapproaching = [accent]敌人将至 [lightgray]{0}[]
看上去语法有点问题，暂时不修改

2022-05-08 22:34 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.onset.name = 起始地区
onset名字可以再想想，描述不用了
二号地区描述可以再想想

2022-05-08 22:37 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.bloomintensity.name = 光彩强度
炫光会带有歧义吧，那我开花如何（（（

2022-05-08 22:39 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +liquid.arkycite.name = 方解液
完全不确定arkycite的来源，暂时只能这样翻译

2022-05-08 22:41 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-conduit.name = 相位流体导管桥
是统一错误，已经全统一成管道

2022-05-08 22:43 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +lst.setblock = 在任何位置设置地块数据。
全部改成上述语言，并且句号全都删掉

2022-05-08 22:49 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.graphitic-wall.name = 石墨矿墙
游戏中本来就是矿物的一种啊，这样容易有歧义，防守用的墙？

2022-05-08 22:54 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.unit-cargo-unload-point.name = 单位物流卸载点
一个叫loader一个叫unload-point，我估计还得游戏中找原型

2022-05-08 23:05 UTC, xem8k5 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.reinforced-liquid-tank.name = 强化流体储存罐
见qq群截图

2022-05-08 23:06 UTC, xem8k5 commented
> 似乎长了些。就叫「单位升级厂」怎么样？下同

1.全部统一成：禁止从核心外丢物品
2.全部统一成：单位升级厂
3.地图处理器可能带有歧义，不更改
4.全部统一成：加强型
5.核心名字改成碉堡核心、堡垒核心、卫城核心
6.改成 进攻队伍的最小规模
7.改成 限制地图有效区域
8.改成 与V7并不兼容
9.“检测到核弹发射”等全部改为侦测
...上文讨论过的问题大多都修复了

2022-05-09 00:14 UTC, xem8k5 commented
发觉强化不符合题意，普通容器血量220 容量300，“强化”容器血量480 容量250，反向强化是不是？故固化符合题意

2022-05-09 01:28 UTC, merged

2022-05-09 02:33 UTC, cigarmemr commented on core/assets/bundles/bundle_zh_CN.properties
> +block.core-citadel.name = 壁垒核心
「御城」怎么样