Update bundle_ko.properties
Anuken/Mindustry pull request #6848
Opened 2022-05-12 14:12 UTC by Nunting

There's something left to be revised.

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-05-14 04:46 UTC, Nunting commented
done.

2022-05-17 06:52 UTC, Sharlottes commented on core/assets/bundles/bundle_ko.properties
>  block.mech-assembler.name = 기갑 조립대
Mech의 옛 번역은 기체 였으므로 기갑 -> 기체?

2022-05-17 06:59 UTC, Sharlottes commented on core/assets/bundles/bundle_ko.properties
>  hint.boost = [accent][[L-Shift][]를 눌러 탑승한 기체로 장애물을 넘을 수 있습니다. \n\n 일부 지상 기체만 이륙할 수 있습니다.
미번역: `L-Shift` -> `왼쪽 Shift`

2022-05-17 07:11 UTC, Sharlottes requested changes
```
hint.mine = \uf8c4 주변의 구리 광석을 수동으로 채굴하려면 광석을 [accent]누르십시오[]. 마우스 오른쪽 클릭을 하면 채굴을 중단합니다.
```

`마우스 오른쪽 클릭` -> `우클릭`

2022-05-22 13:48 UTC, Nunting commented on core/assets/bundles/bundle_ko.properties
>  block.mech-assembler.name = 기갑 조립대
기체는 이미 unit에서 사용중이라서 사용하기 애매함.
기갑의 의미는 전차의 의미가 강하기에... 차라리 단어 그대로의 "기계"가 더 적절하다 생각.

2022-06-08 13:08 UTC, merged