initial german erekir translation
Anuken/Mindustry pull request #6869
Opened 2022-05-13 14:05 UTC by Catchears

Cleans up missing translation. Leaving as draft for now as Erekir is not done and missing some bundle entries (e.g. the tutorial) and because there are some things I'm not quite sure about yet.

Ich habe ein Paar der neuen Übersetzungen (von @end-me-please) geändert, damit die anderen Namen besser passen, das wären:

- Gelber Stein -> Gelbstein
- Roter Stein -> Rotstein
- Berylliumhaltiger Stein -> Berylliumstein
- Rotes Eis -> Roteis

Diese Übersetzungen sind zwar vielleicht nicht ganz richtig, aber es sollte sich jeder denken können, was gemeint ist, und sie passen bei Sachen wie "Gelbsteinschlot" meiner Meinung nach einfach besser.

Mir fehlen jedoch Ideen für viele der neuen Einheiten und Geschösse:
block.breach.name = Breach
block.sublimate.name = Sublimate
block.diffuse.name = Diffuse
unit.vanquish.name = Vanquish
unit.conquer.name = Conquer
unit.avert.name = Avert
unit.disrupt.name = Disrupt
unit.evoke.name = Evoke
unit.incite.name = Incite
unit.emanate.name = Emanate
unit.elude.name = Elude
unit.obviate.name = Obviate

Einfach die Infinitivformen im Deutschen zu nehmen ergibt keine vernünftigen Namen (Durchbrechen, Stören). Fällt vielleicht einem anderen Übersetzer etwas ein?

2022-05-13 14:10 UTC, end-me-please commented
(Was a bit on the fence for the rock names, thanks)

2022-05-13 15:05 UTC, Catchears commented
Brecher klingt schonmal gut, Sublimat klingt mir noch zusehr nach einem Gegenstand als ein Geschütz, aber bis jetzt fällt mir da wenig anderes ein.

2022-05-13 15:35 UTC, CreepTV commented
What about "Diffusor"?

2022-05-15 21:58 UTC, stacktrace-error commented
The fact that most of the names are verbs makes this rather difficult as words like "Verbreiten" don't have any ring to them at all

2022-05-17 16:19 UTC, Catchears commented
I've committed a first draft, I think the names sound alright and you can generally guess where I got the idea from. Does anyone mind these or have any suggestions? I'll mention @Shawak as I'm not sure you've seen this PR yet and would like to at least check with you.

2022-05-18 17:38 UTC, Catchears commented
I've merged the modified changes from #6899 into this PR - they fix several missed translations.

2022-05-19 06:50 UTC, Shawak requested changes

2022-05-19 06:50 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +block.door.description = Eine Mauer, die geöffnet und geschlossen werden kann.
Ein Tor

2022-05-19 06:50 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +block.door-large.description = Eine Mauer, die geöffnet und geschlossen werden kann.
Ein Tor

2022-05-19 06:50 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +block.lancer.name = Lancer
Lanze?

2022-05-19 06:50 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +block.reinforced-pump.name = Verstärkte Pump
Pumpe

2022-05-19 13:22 UTC, Shawak approved these changes

2022-06-09 20:43 UTC, end-me-please commented
oh crap, forgot about this draft before creating a new pr, thought it was already merged

https://github.com/Anuken/Mindustry/pull/6999
oh well

2022-06-10 07:39 UTC, Catchears commented
I can merge it in here if you want - then we'd have the changes combined.

2022-06-16 21:36 UTC, Catchears commented
I'm going to mark this as ready-for-review.

I will use this opportunity to offer to merge #6870 and #6999 (both by @end-me-please) into this PR to avoid merge conflicts through multiple PRs, just drop a comment below if you'd like me to.

2022-07-15 03:33 UTC, merged