Adding skip shortcut with f9.
Anuken/Mindustry pull request #6934
Opened 2022-05-24 21:59 UTC by chronikum

This pull request adds an keybinding to skip the waiting time.

A "is waiting for next wave" and admin check and server/client check is in place.
If you feel a check is missing, feel free to contribute it.

```
if(Core.input.keyTap(Binding.skipWaveCall)){
            if(net.client() && player.admin && logic.canSkipWave()){
                Call.adminRequest(player, Packets.AdminAction.wave);
            }else if (logic.canSkipWave()){
                logic.skipWave();
            }
}
```

Also, I moved `canSkipWave` from private `HudSegment` as public boolean in `Logic`, so it is accessible from HudSegment and DesktopInput to reduce code duplicates.
The key to skip a wave is f9. Feel free to suggest another default key.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-05-25 10:10 UTC, WilloIzCitron reviewed
\*sad android user noises*

2022-05-25 14:52 UTC, buthed010203 commented on core/src/mindustry/core/Logic.java
> +    /* @return if currently wave wait time can be skipped or not */
```suggestion
    /** @return if currently wave wait time can be skipped or not */
```

2022-06-08 13:19 UTC, Anuken requested changes

2022-06-08 13:19 UTC, Anuken commented on core/src/mindustry/input/Binding.java
> +import mindustry.net.Packets;
Redundant import.

2022-06-08 13:19 UTC, Anuken commented on core/src/mindustry/input/Binding.java
> +    skipWaveCall(KeyCode.f9),
Why is it suffixed with "call"?

2022-06-08 13:19 UTC, Anuken commented on core/src/mindustry/input/DesktopInput.java
> +            }else if (logic.canSkipWave()){
Incorrect formatting, space after if.

2022-06-08 13:19 UTC, Anuken commented on core/src/mindustry/input/DesktopInput.java
> +                Call.adminRequest(player, Packets.AdminAction.wave);
Inner class should be referenced directly as AdminAction instead of qualifying it.

2022-10-02 13:08 UTC, closed without merging