Update bundle_zh_CN.properties
Anuken/Mindustry pull request #7135
Opened 2022-07-06 11:16 UTC by Jackson11500

+ 大幅修改原版翻译          Greatly improve original translation
+ 保持同类词语统一性      Keep words with same category consistent
+ 语法语序调整                 Adjust gramma and word order to make them more comfortable

主要参考了学术端语言包

* 兵种、炮台请各位提议更好的，欢迎在下面提出建议     Units and turrets require more discussion，review and discussion are welcomed!

2022-07-07 02:48 UTC, xem8k5 reviewed
block.overdrive-dome.name = 超速穹顶投影
block.overdrive-projector.name = 超速投影器

block.mender.name = 修理器
block.mend-projector.name = 修理投影器


"超速穹顶投影" 是否该改成 "超速穹顶投影器" 来统一队形？

2022-07-07 02:54 UTC, xem8k5 reviewed
lst.explosion = 在某个位置制造爆炸

统一队形，"在指定位置生成爆炸"

2022-07-07 02:55 UTC, xem8k5 reviewed
editor.playtest = 游戏测试

可以改成"游戏内测试"，与游戏内编辑相同

2022-07-07 02:59 UTC, xem8k5 reviewed
rules.title.enemy = AI 对手
如果真的要改成RTS AI的话，我推荐这个也要改

2022-07-07 03:09 UTC, xem8k5 reviewed
block.illuminator.description = 释放光线。

光线只是为了研究光的折射、反射等的路径而虚拟出来的，应该为"释放光照"

2022-07-07 03:14 UTC, Cry0flu1d commented on core/assets/bundles/bundle_zh_CN.properties
> +item.phase-fabric.name = 相织物
"相织物" is a community expression, it shouldnt use in-game

2022-07-07 03:55 UTC, Cry0flu1d commented
btw, there is some **pointless** revertions, such as
`item.dormant-cyst.name = Dormant Cyst`
`liquid.neoplasm.name = Neoplasm`
`liquid.arkycite.name = Arkycite`
and so on , I'm just cant figure out what's wrong with those translations, and why you revert them

2022-07-07 03:58 UTC, Jackson11500 commented
> btw, there is some **pointless** revertions, such as `item.dormant-cyst.name = Dormant Cyst` `liquid.neoplasm.name = Neoplasm` `liquid.arkycite.name = Arkycite` and so on , I'm just cant figure out what's wrong with those translations, and why you revert them

这些词争议也很大，在性质不明确的时候就做翻译，很可能整出笑话
arkycite是等待优化版本。芳油也存在较大争议
争议较大的词暂时revert同时等最终确定。
The words with considerable controversy are reverted temporary and waited for a better translation.

2022-07-08 02:15 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +objective.enemiesapproaching = [accent]敌人来袭： [lightgray]{0}[]
英文冒号？中文冒号？

2022-07-08 02:15 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.abandon.confirm = 此区块核心将自毁.\n确认?
句号

2022-07-08 02:16 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.noswitch = 你无法在当前区块遭受攻击时切换区块.\n\n区块: [accent]{0}[] 位于 [accent]{1}[]
句号。

2022-07-08 02:16 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +lastcommanded = [lightgray]上次指挥: {0}
又是冒号

2022-07-08 02:17 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +rules.initialwavespacing = 第一波间隔:[lightgray] (秒)
换成中文冒号？

2022-07-08 02:18 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +block.constructor.description = 构筑 1x1 至 2x2 大小的方块
听说有人句号掉了

2022-07-08 02:18 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +block.payload-unloader.description = 从载荷方块卸载液体和物品
5个句号

2022-07-08 02:19 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +block.illuminator.description = 提供照明
句号甩卖

2022-07-08 02:19 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +lst.flushmessage = 在屏幕中央投影文字缓存区的内容.\n会等待上一个文字显示结束
。句号

2022-07-08 02:20 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +graphicstype.col = 颜色代码.\n为以[accent]%[]开头的十六进制代码形式。\n举例: [accent]%ff0000[] 为[red]红色
事情开始变得难以控制了,。:：.

2022-07-08 02:20 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +lenum.unbind = 完全移除逻辑控制，恢复默认AI.
最后一个句号

2022-07-08 02:21 UTC, SoMall-dumpling reviewed
标点符号问题一览

2022-07-08 03:45 UTC, Jackson11500 commented
ALL FIXED

2022-07-08 11:24 UTC, nanmenyangde requested changes

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.abandon = 遗弃
建议改成“撤离”
个人认为"弃"还是偏主观了一些，撤离更适合描述一种客观的动作

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.hail.name = 冰雹
建议和双管炮 火焰炮同为1x1炮的冰雹 也改为冰雹炮

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.surge-tower.name = 巨浪电力塔
似乎强调材料没有很大的作用，建议和节点一样单纯命名为 电力塔

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.liquid-junction.name = 液体交叉器
管道可以运输氢气，臭氧等气体，建议改为 流体交叉器
路由器同理

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.overdrive-dome.name = 超速穹顶投影
感觉 超速穹顶 即可，不需要再添加投影

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.reinforced-liquid-container.name = 强化液体容器
与上文相同，建议为流体

2022-07-08 11:24 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
>  block.core-acropolis.name = 卫城核心
感觉这个名字还是很怪..

2022-07-08 11:40 UTC, nanmenyangde requested changes
一些建议

2022-07-08 15:59 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.hail.name = 冰雹
或者都不加'炮'吧，感觉有些炮台加'炮'结尾，有些又不加，就很奇怪。就单纯的依据大小来区分也感觉不是很好
而且好像说'双管''火焰'的比说'双管炮''火焰炮'的要常见

2022-07-08 16:03 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.overdrive-dome.name = 超速穹顶投影
fix

2022-07-08 16:11 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
>  block.core-acropolis.name = 卫城核心
看看其他人意见

2022-07-08 17:30 UTC, liangliangsan approved these changes

2022-07-09 02:31 UTC, Cry0flu1d commented on core/assets/bundles/bundle_zh_CN.properties
> +block.overdrive-dome.name = 超速穹顶投影
but **technically** it's a **projector** , not a dome

2022-07-09 14:18 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +rules.onlydepositcore = 核心仅可存储资源
什么鬼，怎么又改回来了

2022-07-09 14:18 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-heater.name = 相织制热机
建议统一为相织布

2022-07-09 14:18 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +lenum.unbind = 完全移除逻辑控制，恢复默认AI
我印象里这个指令只能移除该逻辑块的控制吧，不会影响其它逻辑块的控制

2022-07-09 14:19 UTC, nanmenyangde commented on core/assets/bundles/bundle_zh_CN.properties
> +rules.onlydepositcore = 核心仅可存储资源
核心仅可存储资源  说的很不明确

2022-07-10 04:35 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
> +rules.onlydepositcore = 核心仅可存储资源
fix

2022-07-10 04:36 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
> +lenum.unbind = 完全移除逻辑控制，恢复默认AI
移除本逻辑的单位绑定？

2022-07-10 04:37 UTC, Jackson11500 commented on core/assets/bundles/bundle_zh_CN.properties
> +block.phase-heater.name = 相织制热机
不用吧，太长了。

2022-07-15 02:14 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.four.description = {临时}\n是当前的最高级区块。把这当成一个挑战！
6个句号。
720行，721行，722行，723行，724行都有小建议。在群里说。

2022-07-15 02:29 UTC, SoMall-dumpling requested changes

2022-07-15 02:29 UTC, SoMall-dumpling commented on core/assets/bundles/bundle_zh_CN.properties
> +sector.four.description = {临时}\n是当前的最高级区块。把这当成一个挑战！
sector.two.description = 敌人被护盾保护着，不过这里也探测到一台实验性的护盾破坏器。\n找到它，并为它输送一些钨作为弹药，然后摧毁敌方基地。
sector.lake.description = 这个区块的熔岩湖限制了大部分单位的移动，悬浮单位是唯一选择。\n尽快研究[accent]飞船制造厂[]并生产一个[accent]挣脱[]。
sector.three.description = 扫描显示，该区域在着陆后不久将受到多方向的攻击。\n迅速建立防御并尽快扩张。\n[accent]机甲[]单位可用于在这里的崎岖地形活动。
sector.atlas.description = 这个区块包含了各种地形，需要多兵种配合进行有效进攻。\n这里发现的一些更为坚固的敌军基地需要使用高级单位来摧毁。\n研究[accent]电解机[]和[accent]坦克重构厂[]。
sector.split.description = 该区域的敌人数量很少，非常适合测试新的运输技术。
sector.four.description = {临时}\n\n目前的最终区块。把它当作一个挑战！

2022-07-15 03:40 UTC, BlackDeluxeCat commented on core/assets/bundles/bundle_zh_CN.properties
> +lenum.unbind = 移除本逻辑的单位绑定
啥叫“本逻辑的单位绑定”，unbind是对单位AI的替换，逻辑当前的`@unit`并不变。
从代码实现角度，仍建议译原文。

> lenum.unbind = Completely disable logic control.\nResume standard AI.

推：
`lenum.unbind = 停用单位的逻辑控制\n恢复常规AI`
- 单位的：增译的定语。个人认为结合词义和语境，应让unbind应自然而然联想到是ubind的逆操作，ubind单独成指令，且ui设计和单位密切关联，unbind缺乏这样的关联，故增译。
- completely：未见程度副词在本句说明中存在的意义，个人认为没有必要译出。
- standard AI：常规AI。另译默认AI，但与词义有出入。

2022-07-17 13:01 UTC, Jackson11500 commented
@Anuken Most of translations have been discussed and are ready for merge finally. :) Thanks.

2022-07-17 13:21 UTC, merged