Update bundle_zh_CN.properties
Anuken/Mindustry pull request #7186
Opened 2022-07-17 03:08 UTC by laohuaji233

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-07-17 05:49 UTC, Cry0flu1d approved these changes

2022-07-17 11:53 UTC, xem8k5 approved these changes

2022-07-17 16:02 UTC, nanmenyangde requested changes
部分翻译不太贴合游戏内情况和英文原意。
炮塔和兵种名字不符合口语习惯，读起来有些滞涩。
目前和其他人讨论，感觉主要是兵种名字，炮塔名字，地区名字存在一些争议。

2024-03-29 07:45 UTC, Leo-MathGuy commented
Please fix the conflicts or close the PR, it has been 2 years :(

2025-02-06 21:14 UTC, Anuken commented
Not sure whether to merge this based on comments; re-open if necessary.

2025-02-06 21:14 UTC, closed without merging