Update bundle_vi.properties
Anuken/Mindustry pull request #7366
Opened 2022-08-14 17:08 UTC by Kynarc

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-08-20 03:22 UTC, NgLam2911 requested changes
Look okay, just need some change. Thanks.

2022-08-20 03:22 UTC, NgLam2911 commented on core/assets/bundles/bundle_vi.properties
> +stats.wave = Lượt đã vượt qua
You should take a look at how we translate "wave"

2022-08-20 03:22 UTC, NgLam2911 commented on core/assets/bundles/bundle_vi.properties
> +stats.unitsCreated = Đơn vị đã tạo
"Quân lính" instead of "Đơn vị"

2022-08-20 03:22 UTC, NgLam2911 commented on core/assets/bundles/bundle_vi.properties
> +sector.navalFortress.name = Pháo đài Hải quân
You shouldnt translate sector name because its make player in other country know what are you playing... or searching map infomation.

2022-08-20 03:22 UTC, NgLam2911 commented on core/assets/bundles/bundle_vi.properties
> +sector.onset.description = Chỗ này chỉ để hướng dẫn thôi, chưa hoàm thiện đâu. Đợi thêm đe.
ewww, "hoàm"

2022-10-04 19:40 UTC, Anuken commented
Criticism never addressed?

2022-10-04 19:40 UTC, closed without merging