Update bundle_pt_BR.properties
Anuken/Mindustry pull request #7614
Opened 2022-09-24 04:37 UTC by LokKol17

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-09-24 18:07 UTC, LokKol17 commented
Português: As partes "lst." foram traduzidas.

English: The "lst." got translated.

2024-03-26 06:36 UTC, DinoWattz requested changes

2024-03-26 06:36 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +lst.getlink = Pega uma conexão do processador pelo index. Começa no 0.
Change "index" to "indice" so it matches the translation at line 2120.
```suggestion
lst.getlink = Pega uma conexão do processador pelo indice. Começa no 0.
```

2024-03-26 06:36 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +lst.lookup = Procura um item/líquidp/unidade/bloco pelo ID.\nContagem total de cada tipo pode ser acessada com:\n[accent]@unitCount[] / [accent]@itemCount[] / [accent]@liquidCount[] / [accent]@blockC
- "líquidp" should be "líquido"
- "bloco pelo ID" as "tipo de bloco por ID"
```suggestion
lst.lookup = Procura um item/líquido/unidade/tipo de bloco por ID.\nContagem total de cada tipo pode ser acessada com:\n[accent]@unitCount[] / [accent]@itemCount[] / [accent]@liquidCount[] / [accent]@blockCount[]
```

2024-03-29 07:44 UTC, Leo-MathGuy commented
Please fix the conflicts or close the PR, it has been 2 years :(

2025-02-05 16:37 UTC, Anuken commented
Review comments do not seem to have been resolved.

2025-02-05 16:37 UTC, closed without merging