Better About Dialog
Anuken/Mindustry pull request #7647
Opened 2022-10-01 17:54 UTC by xStaBUx

# Visual improvements for the About dialog:
![java_dAjqIdPV8F](https://user-images.githubusercontent.com/96493687/193421983-cfcfe55b-eac5-4a7c-a893-42a1bfdd38fe.gif)

- I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- I have ensured that my code compiles, if applicable.
- I have ensured that any new features in this PR function correctly in-game, if applicable.

2022-10-01 19:59 UTC, Anuken requested changes

2022-10-01 19:59 UTC, Anuken commented on core/src/mindustry/ui/dialogs/AboutDialog.java
> +import javax.swing.*;
oh dear

2022-10-01 19:59 UTC, Anuken commented on core/src/mindustry/ui/dialogs/AboutDialog.java
> +import arc.func.Cons;
This doesn't follow style guidelines, you are not using wildcard imports and this very much looks like a redundant import.

2022-10-01 19:59 UTC, Anuken commented on core/src/mindustry/ui/Styles.java
> +    flaty,
This doesn't follow the right format. The letter at the end indicates the type of button style (i = image, t = text button, etc)  - what does "y" mean here?

2022-10-02 09:26 UTC, xStaBUx commented on core/src/mindustry/ui/Styles.java
> +    flaty,
Maybe I will give it the name of the panelі, because it's a gray panel with an image?

2022-10-03 08:08 UTC, xStaBUx commented
now everything is ok?

2022-10-04 08:23 UTC, xStaBUx commented
uh. a panel button already exists
![зображення](https://user-images.githubusercontent.com/96493687/193770493-ccf2438d-b8a6-4055-b20f-417838bac017.png)
I'd better rework my pull request

2022-10-04 08:23 UTC, closed without merging