Update bundle_es.properties
Anuken/Mindustry pull request #7767
Opened 2022-10-25 17:56 UTC by Angel-24

Updated spanish translation. Tutorials, mods messages, and more.

2022-10-25 21:19 UTC, Anuken commented
@ImUrX (can't add as a direct reviewer)

2022-11-02 00:51 UTC, ImUrX requested changes

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +gz.turrets = Investiga y construye 2 \uf861 [accent]torretas Duo[] para defender el Núcleo.\nLas torretas Duo requieren un suministro de \uf838 [accent]munición[] mediante cintas transportadoras.
Dejar torretas afuera del ``\uf861 [accent]``

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +gz.scatterammo = Suministra [accent]plomo[] a la torreta Scater mediante cintas transportadoras.
esta escrito como ``Scater`` en vez de ``Scatter``

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +onset.power = Para [accent]encender[] el perforador de plama, investiga y coloca un \uf73d [accent]nodo de energía perpendicular[].\nConecta la turbina condensadora al perforador de plasma.
typo ``perforador de plama``

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +onset.graphite = Otros bloques más complejos requieren \uf835 [accent]grafito[].\nConstruye perforadores de plasma para extraer berilio.
para extraer **``grafito``**

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +onset.arcfurnace = El horno de arco necesita \uf834 [accent]arena[] y \uf835 [accent]grafuti[] para producir \uf82f [accent]silicio[].\nTambién requiere [accent]Energía[] para funcionar.
typo ``grafuti``

``Energía`` deberia de ser en minuscula

2022-11-02 00:51 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +onset.turrets = Las unidades son efectivas, pero las [accent]torretas[] pueden ofrecer mejores capacidades defensivas si se usan de forma efectiva.\nConstruye una \uf6eb [accent]Torreta Breach[].\nLa
Construye una ``torreta \uf6eb [accent]Breach[].``

2022-11-02 08:19 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +mod.requiresversion.details = Requiere la versión del juego: [accent]{0}[]\nTu versión está obsoleta. Este mod requiere una versión más reciente del juego.
Vale

2022-11-02 08:21 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +block.mass-driver.name = Catapultador electromagnético
ok, cambiaré el nombre en todas las líneas de los "mass drivers".

2022-11-02 08:21 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.research = Abre el \ue875 árbol de tecnologías.\nInvestiga el \uf870 [accent]taladro mecánico[], luego selecciónalo en el menú inferior derecho.\nHaz clic sobre una beta de cobre para colocar el t
Sí, mejor.

2022-11-02 08:25 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +onset.arcfurnace = El horno de arco necesita \uf834 [accent]arena[] y \uf835 [accent]grafuti[] para producir \uf82f [accent]silicio[].\nTambién requiere [accent]Energía[] para funcionar.
Vaya, ¿cómo llegó eso ahí?  :-P

2022-11-02 08:39 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +block.world-processor.name = Procesador integrado
¿Entonces cómo deberíamos representar que este procesador está "integrado en el sector"? (ya que forma parte del mapa y no se puede eliminar) ¿Procesador estático? ¿Procesador por defecto? Cualquier idea es útil. Y lo mismo habría que aplicarle al bloque de "mensaje integrado".

2022-11-02 08:44 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.moveup = \ue804 Sigue explorando para más objetivos.
Pues depende, si la única dirección en la que puedes explorar es hacia arriba, como en la "Zona de impacto" en Serpulo, entonces prefiero dejarlo así. Si el mapa es más grande y el jugador puede ir en cualquier dirección, aunque el juego espera que se mueva hacia arriba, ahí sería mejor especificar la dirección. Jugaré este tutorial para ver cómo queda mejor.

2022-11-02 08:50 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
Para referirnos al Núcleo/s de un sector siempre se expresa con mayúscula. Esto ayuda a destacar la importancia de este bloque, además favorece el "lore" del juego. Casi como si albergara o se comunicara con una "inteligencia artificial", tal vez 
con conciencia propia, que es una representación del jugador. o algo así...

2022-11-02 08:51 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
Claro que esa es mi opinión personal. Creo que está más interesante así. ¿Deberíamos cambiarlo?

2022-11-02 08:53 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
[Nota: No estoy al tanto del lore del juego, más bien prefiero interpretarlo a mi manera a partir de las pistas que encuentro por ahí, y lo que leo de vez en cuando en el servidor de Discord.]

2022-11-02 08:54 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
[[Me parece bonito que cada uno pueda interpretar la historia del juego de forma diferente y luego debatir sobre ello, teorizar... etc.]

2022-11-02 15:12 UTC, ImUrX requested changes

2022-11-02 15:12 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +block.world-processor.name = Procesador integrado
Procesador estático me gusta, tiene un significado en programación que es que su tiempo de vida dura hasta terminada la ejecución del proceso.

Hey @Anuken thoughts on this? ``Static Processor`` as another way to say ``World Processor``. We currently had the translation as ``Global Processor`` but some people misunderstood the translation. The current suggestion from Angel is ``Integrated Processor`` also

2022-11-02 16:57 UTC, Anuken commented
Sure, as long as it gets the message across. It doesn't need to be exact.

2022-11-03 08:01 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
Seguro?

2022-11-03 16:29 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
No veo una mala razon para dejarlo en minuscula si tambien en ingles lo dejan asi.
Aunque veo inconsistencias a veces esta en mayuscula a veces no xd

2022-11-03 17:10 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +gz.conveyors = Investiga y construye \uf896 [accent]cintas transportadoras[] para mover los recursos minados\ndesde los taladros hasta el Núcleo.\n\nArrastra para colocar múltiples bloques de cintas
pero si queres ya esta, con todo esto esta bien en mi opinion

2022-11-05 20:59 UTC, ImUrX approved these changes

2022-11-05 21:07 UTC, merged