Update bundle_es.properties
Anuken/Mindustry pull request #7848
Opened 2022-11-09 09:27 UTC by Angel-24

Updated some descriptions strings.

2022-11-09 13:48 UTC, Anuken commented
@ImUrX

2022-11-09 19:44 UTC, ImUrX requested changes

2022-11-09 19:44 UTC, ImUrX commented on core/assets/bundles/bundle_es.properties
> +sector.coastline.description = Se han detectado restos de tecnología de unidades navales en esta ubicación. Repele los ataques enemigos, captura este sector, y consigue esa tecnología.
Decidite, ``capturé`` o ``captura``, si es el segundo entonces sería ``y consiga`` y ``Repela los``

2022-11-11 08:15 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +sector.coastline.description = Se han detectado restos de tecnología de unidades navales en esta ubicación. Repele los ataques enemigos, captura este sector, y consigue esa tecnología.
Toda la frase está en segunda forma verbal. (En español de España)

2022-11-12 01:46 UTC, ImUrX approved these changes

2022-11-13 14:58 UTC, merged