Update bundle_fr.properties
Anuken/Mindustry pull request #7883
Opened 2022-11-11 22:05 UTC by AyuKo-o

Added a french translation for those following descriptions: 
Bastion core, Citadel core, Acropolis core, 
Breach, Diffuse, Sublimate, Titan,Afflict, Disperse, Lustre, Scathe, Smite, Malign,
Silicon Arc Furnace, Oxidation Chamber, Electric Heater, Slag Heater, Phase Heater, Heat Redirector, Heat Router, Electrolyzer,Atmospheric Concentrator, Surge Crucible, Phase Synthesizer, Carbide Crucible, Cyanogen Synthesizer,  Slag Incinerator,
Vent Condenser

2022-11-11 22:28 UTC, Phinner commented
:pray: Thanks mate

2022-11-12 00:23 UTC, JojoFR1 commented
I translated what was left to translate, I PR it on your branch
I let you update!

2022-11-12 00:29 UTC, JojoFR1 commented
> Added a french translation for those following descriptions: 
- All the drills
- All the walls
- All the duct/conduit
- All energy related stuff
- All the units stuff
- and the other stuff

2022-11-12 02:15 UTC, Phinner requested changes
La traduction est bien dans son ensemble, mais parfois, on a l'impression que vous avez juste utilisé un outil de traduction sans bien vérifier car :

- Il y a de la ponctuation manquante.
- Quelques traduction incomplètes.
- Des tournures de phrase bizarres.
- etc...

Svp, validez vos traductions avec un outil comme [Language Tool](https://languagetool.org/).

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.mech-fabricator.description = Construit des unités Merui. Les unités de sortie peuvent être utilisées directement, ou transférés dans des refabricateurs pour une amélioration.
```suggestion
block.tank-fabricator.description = Construit des unités Stell. Les unités de sortie peuvent être utilisées directement, ou transférées dans des refabricateurs pour une amélioration.
block.ship-fabricator.description = Construit des unités Elude. Les unités de sortie peuvent être utilisées directement, ou transférées dans des refabricateurs pour une amélioration.
block.mech-fabricator.description = Construit des unités Merui. Les unités de sortie peuvent être utilisées directement, ou transférées dans des refabricateurs pour une amélioration.
```

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.mech-assembler.description = Assemble de grands mechs à partir de blocs et d'unités saisis. Le niveau de sortie peut être augmenté en ajoutant des modules.
```suggestion
block.tank-assembler.description = Assemble de grands tanks à partir de blocs et d'unités. Le niveau de l'unité de sortie peut être augmenté en ajoutant des modules.
block.ship-assembler.description = Assemble de grands navires à partir de blocs et d'unités. Le niveau de l'unité de sortie peut être augmenté en ajoutant des modules.
block.mech-assembler.description = Assemble de grands mechs à partir de blocs et d'unités. Le niveau de l'unité de sortie peut être augmenté en ajoutant des modules.
```

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.prime-refabricator.description = Améliore les unités saisies au troisième niveau.
```suggestion
block.tank-refabricator.description = Améliore les tanks au deuxième niveau.
block.ship-refabricator.description = Améliore les navires au deuxième niveau.
block.mech-refabricator.description = Améliore les mechs au deuxième niveau.
block.prime-refabricator.description = Améliore les unités au troisième niveau.
```

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.reinforced-payload-conveyor.description = Avance les charges utiles.
```suggestion
block.reinforced-payload-conveyor.description = Déplace les charges utiles.
```

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.reinforced-payload-router.description = Distribue les charges utiles dans les blocs adjacents. Fonctionne comme un trieur lorsqu'un filtre est défini.
```suggestion
block.reinforced-payload-router.description = Distribue les charges utiles aux les blocs adjacents. Fonctionne comme un trieur lorsqu'un filtre est défini.
```

2022-11-12 02:15 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.shockwave-tower.description = Endommage et détruire les projectiles ennemis dans un rayon. Nécessite du cyanogène.
```suggestion
block.shockwave-tower.description = Endommage et détruit les projectiles ennemis dans son rayon. Nécessite du cyanogène.
```

2022-11-12 02:26 UTC, Phinner commented
Aussi, pour pas te casser la tête a implémenter les changements toi même comme tout à l'heure, clique sur ce bouton. Cela va automatiquement merge la suggestion.
![exemple](https://docs.github.com/assets/cb-20237/images/help/pull_requests/commit-suggestion-button.png)

2022-11-12 11:39 UTC, JojoFR1 commented
> La traduction est bien dans son ensemble, mais parfois, on a l'impression que vous avez juste utilisé un outil de traduction sans bien vérifier car :
> 
> - Il y a de la ponctuation manquante.
> - Quelques traduction incomplètes.
> - Des tournures de phrase bizarres.
> - etc...

C'est bon on a régler ce que t'a suggérer de modifier, normalement tout est traduit !

2022-11-12 12:03 UTC, Phinner commented
Excellent, mais il manque 2 suggestions :

- https://github.com/Anuken/Mindustry/pull/7883/files#r1020631761

- https://github.com/Anuken/Mindustry/pull/7883/files#r1020632388

2022-11-12 12:16 UTC, Phinner approved these changes
Parfait :ok_hand:

2022-11-12 16:12 UTC, JojoFR1 commented
> Excellent, mais il manque 2 suggestions :
> 
> - https://github.com/Anuken/Mindustry/pull/7883/files#r1020631761
> 
> - https://github.com/Anuken/Mindustry/pull/7883/files#r1020632388

Ah oui j'avais pas vu, my bad

2022-11-13 09:56 UTC, Phinner reviewed
I forgor 💀

2022-11-13 09:56 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.prime-refabricator.description = Améliore les unités saisies au troisième niveau.
```suggestion
block.prime-refabricator.description = Améliore les unités au troisième niveau.
```
G oublié ce petit truc.

2022-11-13 10:02 UTC, AyuKo-o commented on core/assets/bundles/bundle_fr.properties
> +block.prime-refabricator.description = Améliore les unités saisies au troisième niveau.
ça serait pas mieux de changer "navires" en "vaisseaux"? et "mechs" en "mécha"

2022-11-13 10:48 UTC, Phinner commented on core/assets/bundles/bundle_fr.properties
> +block.prime-refabricator.description = Améliore les unités saisies au troisième niveau.
Il est vrai

2022-11-14 09:36 UTC, JojoFR1 commented
Line 159, add the new translation (la traduction ça doit être ça, regarder le dernier "Bubdle update")

```
mod.requiresversion = Requiert la version: [red]{0}
```

2022-11-14 09:41 UTC, Phinner commented
> Line 159, add the new translation (la traduction ça doit être ça, regardez le dernier "Bundle update")
> 
> ```
> mod.requiresversion = Requiert la version: [red]{0}
> ```

Il faudrait que ayuko synchronize son fork pour avoir les changements.

2022-11-14 09:43 UTC, Phinner commented
![image](https://user-images.githubusercontent.com/62483793/201627285-594cd3d1-c271-49f4-84b3-c429bc582699.png)
Clique là

2022-11-14 09:44 UTC, Phinner commented
> https://github.com/Anuken/Mindustry/pull/7883/commits/469335e99753010de7f9a88b7e93c2020ade6605
Bruh, tu l'as rajouté manuellement, tu as créé un conflit...

2022-11-14 09:45 UTC, closed without merging

2022-11-14 09:46 UTC, Phinner commented
AAAAAAAAAAAAAAAAAAAAAAH, QU'AS-TU FAIT !!! Tu aurais pu reverser ton commit, synchronizer le fork et enfin ajouter...

2022-11-14 09:48 UTC, AyuKo-o commented
> AAAAAAAAAAAAAAAAAAAAAAH, QU'AS-TU FAIT !!! Tu aurais pu reverser ton commit, synchronizer le fork et enfin ajouter la traduction...

T'as répondu après que tu m'as signaler les conflits...
Mais sinon il n'y a pas un moyen de re-ouvrir le pull request? sinon on peut en faire un autre je suppose

2022-11-14 09:50 UTC, Phinner commented
Non, il y aurait jamais eu de conflit si tu n'avais pas ajouter la ligne manuellement.
Je vais réouvrir ce PR moi même...

2022-11-14 09:53 UTC, AyuKo-o commented
> Il y aurait jamais eu de conflit si tu n'avais pas ajouter la ligne manuellement. Je vais réouvrir ce PR moi même...

J'avais aucun moyen de merge ou autre...
S'il ne fallait pas le faire dans ce cas il ne fallait pas faire la demande mais bon pas grave

2022-11-14 10:46 UTC, Phinner commented
👌