feat:pt_BR translation
Anuken/Mindustry pull request #8219
Opened 2023-01-24 22:29 UTC by RedsonBr140

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

2023-02-01 19:54 UTC, Anuken commented
Can someone review this? This translation has historically been rather controversial.

2024-03-26 06:22 UTC, DinoWattz requested changes
The translation looks right but there are extra lines added for no reason

2024-03-26 06:22 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +
There's an extra added line here

2024-03-26 06:22 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +
Extra line

2024-03-26 06:22 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +
Extra line

2024-03-26 06:38 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +
```suggestion
```

2024-03-26 06:38 UTC, DinoWattz commented on core/assets/bundles/bundle_pt_BR.properties
> +
```suggestion
```

2024-03-29 19:07 UTC, merged