Wave limit game rule in custom maps
Anuken/Mindustry pull request #8550
Opened 2023-05-01 12:15 UTC by JniTrRny

Unlocked the wave limit game rule to have it work in custom games.
![image](https://user-images.githubusercontent.com/85090668/235449349-70213627-1ae9-4d47-997f-39be77e7a883.png)
0 to disable (wave goes indefinitely), 1 to make your game win instantly (why?)
If the wave has reached the limit (say wave 30/30) and the enemy units have been cleared, game over menu will pop up.

Also rearranged wave sending and wave timer so the rules look more clean when wave timer is disabled, and make everything disabled when waves rule is off.

Note: should setting wave limit at 1 makes the game run until the wave timer goes out?
but that's kinda unintuitive, and setting your wave limit at 2 with no wave units will provide the same result anyways.

---
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

2023-05-04 06:49 UTC, Darkness6030 commented
Players of my server voted for this feature:
![Screenshot_2023-05-04-09-48-48-723_com discord-edit](https://user-images.githubusercontent.com/79508138/236131017-77ced3fc-f47f-436c-bd24-14394a1278a8.jpg)

2023-05-07 01:43 UTC, Anuken requested changes

2023-05-07 01:43 UTC, Anuken commented on core/src/mindustry/ui/dialogs/CustomRulesDialog.java
> +            }).marginLeft(14f).width(260f).height(55f).checked(a -> shown[0]).update(t -> ((Image)t.getChildren().get(1)).setDrawable(shown[0] ? Icon.upOpen : Icon.downOpen)).row();
checked() uses update(), and calling update() again overwrites the callback, so this breaks the checking

2023-05-07 01:43 UTC, Anuken commented on core/src/mindustry/ui/dialogs/CustomRulesDialog.java
> +            }).size(300f, 64f).disabled(b -> set.size == content.<T>getBy(type).select(pred).size);
`select(..).count` allocates, use `count(...)`

2023-05-07 01:43 UTC, Anuken commented on core/assets/bundles/bundle.properties
> +rules.wavelimit = Wave Limit
this doesn't make clear that the game ends when the target is hit - maybe call it "Map Ends After Wave"?

2023-05-07 03:04 UTC, merged