A couple of features for better planet modding
Anuken/Mindustry pull request #8558
Opened 2023-05-02 14:09 UTC by Slotterleet

1) `itemWhitelist`:
This makes it so that every other item not included in this list will be hidden from a planet (including modded items).

2) `allowLaunchToNumbered`:
If false, procedurally generated sectors are not landable by any normal means. This field was also set to false for Erekir.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2023-05-02 16:53 UTC, overdramaticpanromantic commented
pleasepleasepleasepleasePLEASEpleasepleasepleasepleasepleasePLEASE

2023-05-03 00:48 UTC, SpaceEarthEX commented
> pleasepleasepleasepleasePLEASEpleasepleasepleasepleasepleasePLEASE

lmao

2023-05-07 01:49 UTC, Anuken requested changes

2023-05-07 01:49 UTC, Anuken commented on core/src/mindustry/type/Planet.java
> +                hiddenItems.addAll(content.items().copy().filter(i -> !itemWhitelist.contains(i)));
```suggestion
                hiddenItems.addAll(content.items().select(i -> !itemWhitelist.contains(i)));
```

2023-05-07 01:49 UTC, Anuken commented on core/src/mindustry/type/Planet.java
> +            if (itemWhitelist.size > 0){
```suggestion
            if(itemWhitelist.size > 0){
```

2023-05-07 01:49 UTC, merged