Updated German Translation (again... but bigger)
Anuken/Mindustry pull request #8690
Opened 2023-06-08 05:39 UTC by Yoru-Kitsune

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

2023-06-08 09:32 UTC, Shawak requested changes
This is a pretty bad merge request. There are some improvements but also a lot of changes which are making sentences which were correct before incorrect in grammar or using a prett bad wording.

Wouldn't merge this as it is

2023-06-08 09:32 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +stats.enemiesDestroyed = Gegner zerstört
`Einheiten zerstört` would be better, but also the previous one was correct

2023-06-08 09:32 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +discord = Trette dem Mindustry Discord bei!
`Tritt` was correct.

2023-06-08 09:32 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +stats.unitsCreated = Einheiten erschaffen
wrong, previous one was correct

2023-06-08 09:32 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +feature.unsupported = Dein System unterstützt diese Funktion nicht.
wrong, previous one was correct

2023-06-08 09:32 UTC, Shawak commented on core/assets/bundles/bundle_de.properties
> +mods.none = [lightgray]Keine Mods wurden gefunden!
should be `Es wurden keine Mods gefunden`, also previous one was correct

2023-06-27 18:45 UTC, Anuken commented
Seems dead?

2023-06-27 18:45 UTC, closed without merging