most ability displays
Anuken/Mindustry pull request #8981
Opened 2023-08-27 21:01 UTC by stacktrace-error

surgically removed the format markers from the existing names with unsurgical precision, should fix for most latinish alphabet languages but may break others

extremely stupid usage of `waves.shields` in shield reg field, I don't know whether that has to be added as its own bundle

![image](https://github.com/Anuken/Mindustry/assets/89076920/692d6465-8be8-4e34-bf19-510955b95f1f)

![image](https://github.com/Anuken/Mindustry/assets/89076920/fda4c798-3538-472b-8b13-1ae8c72564ef)

![image](https://github.com/Anuken/Mindustry/assets/89076920/ae212c1f-f492-4a02-8616-f75e3948e0a3)

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.
  - Tested with all vanilla units.

2023-08-27 21:07 UTC, stacktrace-error commented
I don't have a fix for the minor text offset on empty displays rn, don't know whether there's something to use besides pad for it

2023-08-27 21:27 UTC, stacktrace-error commented
should there be 2 abilities per line?

2023-08-28 04:45 UTC, Darkness6030 requested changes
What is this comment?

2023-08-29 17:35 UTC, Anuken commented on core/src/mindustry/entities/abilities/ShieldRegenFieldAbility.java
> +import mindustry.world.meta.Stat;
use wildcard imports everywhere

2023-09-02 13:19 UTC, merged