`useUnitCap` fun
Anuken/Mindustry pull request #9187
Opened 2023-10-21 08:31 UTC by Mythril382

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

2023-10-21 13:17 UTC, Anuken requested changes

2023-10-21 13:17 UTC, Anuken commented on core/src/mindustry/world/blocks/units/Reconstructor.java
> +            () -> e.unit().useUnitCap ? (e.unit() == null ? 0f : (float)e.team.data().countType(e.unit()) / Units.getCap(e.team)) : 1f
This looks like it will crash if the unit is null, you should check that first.

2023-10-21 13:17 UTC, Anuken commented on core/src/mindustry/world/blocks/units/UnitFactory.java
> +            () -> e.unit().useUnitCap ? (e.unit() == null ? 0f : (float)e.team.data().countType(e.unit()) / Units.getCap(e.team)) : 1f
Crash.

2023-10-22 09:27 UTC, Mythril382 commented
~~i definitely did not press "request review" on accident~~

2023-10-22 13:14 UTC, Anuken commented on core/src/mindustry/world/blocks/units/Reconstructor.java
> +                    e.unit() == null ? Units.getStringCap(e.team) : (e.unit().useUnitCap ? Units.getStringCap(e.team) : "∞")
```suggestion
                    e.unit() == null || e.unit().useUnitCap ? Units.getStringCap(e.team) : "∞"
```

2023-10-22 13:14 UTC, merged