Fixing typos in the Russian locale bundle
Anuken/Mindustry pull request #9444
Opened 2024-01-11 08:20 UTC by Ounch1

2024-01-11 12:26 UTC, Remint32 commented
не трогай `filter` и строки редактора, особенно сеятель, это название инструмента, а не глагол `рассеивать`

2024-03-27 10:50 UTC, Leo-MathGuy requested changes
Ошибка в переводе и непоследовательность в переводе "locale"

2024-03-27 10:50 UTC, Leo-MathGuy commented on core/assets/bundles/bundle_ru.properties
> +filter.scatter = Рассеивать
Это название инстумента, не глагол

2024-03-27 10:50 UTC, Leo-MathGuy commented on core/assets/bundles/bundle_ru.properties
> +locales.applytoall = Применить изменения ко ВСЕМ locale
В линиях 609-611 "locale" и "locale bundle" надо тоже перевести, ведь в других местах тоже перевёл "locale", например 616 и 619

2024-03-27 10:50 UTC, Leo-MathGuy commented on core/assets/bundles/bundle_ru.properties
> +be.update = Доступна новая передовая сборка:
Лудше оставить

2024-03-29 19:09 UTC, closed without merging